### DISCUSSION TITLE
helm-service: deployment-strategy=user-managed discussion

### DISCUSSION THREAD

**Discussion by christian-kreuzberger-dtx** [keptn/keptn#3038] [General]
After looking at issue #2764, the resp. PR https://github.com/keptn/keptn/pull/2966, and trying out the image `keptn/helm-service:0.8.2-dev-PR-2966.202101250905`, I want to open a discussion on how things should work.

First of all, here is what I had to do to make it work:

1. Create Project
```yaml
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "test"
              properties:
                teststrategy: "functional"
            - name: "evaluation"
            - name: "release"

    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "dev.artifact-delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
            - name: "release"

    - name: "production"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "staging.artifact-delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
            - name: "release"
```

```
GIT_REMOTE_URL=https://github.com/christian-kreuzberger-dtx/keptn-080-qg.git
 GIT_USER=christian-kreuzberger-dtx
 GIT_TOKEN=<redacted>
```

```console
keptn create project keptn --shipyard=./shipyard.yaml --git-user=$GIT_USER --git-token=$GIT_TOKEN --git-remote-url=$GIT_REMOTE_URL
```

2. Create Service
```console
keptn create service --project keptn keptn-control-plane
```

3. Add Helm Chart for Keptn-Control-Plane
```console
wget https://github.com/keptn/keptn/releases/download/0.7.3/0.7.3_keptn-installer.tgz
keptn add-resource --project=keptn --service=keptn-control-plane --stage=dev --resource=0.7.3_keptn-installer.tgz --resourceUri=helm/keptn-control-plane.tgz
keptn add-resource --project=keptn --service=keptn-control-plane --stage=staging --resource=0.7.3_keptn-installer.tgz --resourceUri=helm/keptn-control-plane.tgz
keptn add-resource --project=keptn --service=keptn-control-plane --stage=production --resource=0.7.3_keptn-installer.tgz --resourceUri=helm/keptn-control-plane.tgz


rm 0.7.3_keptn-installer.tgz
```

4. Deploy Keptn-Control-Plane

```
{
  "data": {
    "configurationChange": {
      "values": {
      }
    },
    "deployment": {
      "deploymentstrategy": ""
    },
    "project": "keptn",
    "service": "keptn-control-plane",
    "stage": "dev"
  },
  "source": "https://github.com/keptn/keptn/cli#configuration-change",
  "specversion": "1.0",
  "type": "sh.keptn.event.dev.artifact-delivery.triggered",
}
```

```console
keptn send event --file new-artifact.json
```

5. Get Resulting deployment.finished event
```console
keptn get events sh.keptn.event.deployment.finished --project=keptn [--keptn-context=...]
```

Second, the whole procedure raises some questions to me, which I am putting below as comments. Please answer directly on the comments with your thoughts.

**Comment by christian-kreuzberger-dtx** [comment]
Reading issue #2764, I cannot identify the user-story. Therefore I'll give it a try. Please add a reaction or a comment.

*As a user, I want to deploy a helm-chart with Keptn without having to modify anything in the chart (URLs, pods, deployments, services, names, secrets, ...). It should feel similar to `helm upgrade my-helm-chart.tgz -n my-namespace --set=...`, whereas Keptn defines the namespace (e.g., {project}-{stage}).*

**Comment by christian-kreuzberger-dtx** [comment]
# How does it feel for the user?

I've detailed the experience I had when adding the helm-chart to my config repository. However, I wonder if we can have an automation for adding the helm-chart to all three stages automatically? I know `keptn onboard service` does the trick right now, so I guess whatever solution we come up with in #2990 (e.g., `keptn add-resource --project=sockshop --stage=all`) will work here too!

One thing that seems to be undefined is how to send a new-artifact / trigger an artifact delivery properly. I propose the following (based on the keptn-installer helm chart):
```console
keptn send-event new-artifact --project xyz --service foobar --values=continuous-delivery.enabled=true,control-plane.helmService.image.repository=docker.io/keptn/helm-service:0.7.3
```
Please focus on the part where it says `--values=...`, I believe this is the part that should be relevant for our helm charts, and it works the same way as `helm upgrade ... --set=...`.

## Extension / To be discussed

Another option would be to allow users to specify a helm-chart file (or a link to a helm-chart) with that command. In all honesty, we might have to support all options that helm supports for [`helm install`](https://helm.sh/docs/helm/helm_install/):

* By chart reference: helm install mymaria example/mariadb
* By path to a packaged chart: helm install mynginx ./nginx-1.2.3.tgz
* By path to an unpacked chart directory: helm install mynginx ./nginx
* By absolute URL: helm install mynginx https://example.com/charts/nginx-1.2.3.tgz
* By chart reference and repo url: helm install --repo https://example.com/charts/ mynginx nginx

By doing so, we could provide the content of the helm-chart either as a URI, or as a base64 encoded file, and in the end we could save ourselves the `add-resource` command, e.g.:

```console
keptn send-event new-artifact --project xyz --service foobar --chart=https://storage.googleapis.com/keptn-installer/keptn-0.7.3.tgz --values=continuous-delivery.enabled=true
```

Going one step further, maybe this is also the solution for #2990 ?

**Reply by agrimmer** [reply]
I like the idea of using a chart which is not contained in our Git repo. However, I would consider this as a follow-up issue or even a new KEP.

**Reply by christian-kreuzberger-dtx** [reply]
Thinking about Keptn, how do I update from Keptn 0.7.3 to Keptn 0.8.0?

I can not just do a `keptn send-event new-artifact` with `--values=appVersion=0.8.0`, I need to update the helm-charts aswell.
But I can not update the helm-chart of `production` stage, until I have finished artifact-delivery in dev and staging.

Or is it enough to update the helm-chart in `dev`, and we will automatically pull all changes including the updated helm-chart from `dev` into `staging`?

**Reply by johannes-b** [reply]
(just a remark) The #3007 is about triggering a sequence with the option of setting the `--values` flag. 

A question for clarification: When someone uses Keptn 0.7.3 and has already a deployed service with the Helm chart on each branch, why do we have to pull from `dev` and update  `staging`, and so forth?

**Reply by christian-kreuzberger-dtx** [reply]
> When someone uses Keptn 0.7.3 and has already a deployed service with the Helm chart on each branch, why do we have to pull from dev and update staging, and so forth?

I think our current way of CD is quite biased: Deploying a new artifact means updating the docker image (and updating the associated values.yaml file).

0.7.3 event flow:

## send configuration-change
```
{
  "data": {
    "canary": {
      "action": "set",
      "value": 100
    },
    "project": "sockshop",
    "service": "carts",
    "stage": "",
    "valuesCanary": {
      "image": "keptnexamples/carts:0.11.2"
    }
  },
  "type": "sh.keptn.event.configuration.change",
}
```

## helm-service sends deployment-finished
```
{
  "contenttype": "application/json",
  "data": {
    "deploymentURILocal": "http://carts.sockshop-dev",
    "deploymentURIPublic": "http://carts.sockshop-dev.my-host.com:80",
    "deploymentstrategy": "direct",
    "image": "keptnexamples/carts",
    "labels": null,
    "project": "sockshop",
    "service": "carts",
    "stage": "dev",
    "tag": "0.11.2",
    "teststrategy": "functional"
  },
  "source": "helm-service",
  "type": "sh.keptn.events.deployment-finished",
}
```

## promote to next stage
```
{
  "contenttype": "application/json",
  "data": {
    "canary": {
      "action": "promote"
    }
    "project": "sockshop",
    "service": "carts",
    "stage": "dev"
  },
  "source": "gatekeeper-service",
  "type": "sh.keptn.event.configuration.change",
}
```


The only thing that's being pushed between stages is
```
   "valuesCanary": {
      "image": "keptnexamples/carts:0.11.2"
    }
```

AFAIK every stage (dev, staging, production) has its own helm charts in the respectiev branches, and they are never exchanged (e.g., if I change memory limits in `dev`, I have to manually change them in `staging` and `production` too).

## Keptn 0.8.0

The same is true for Keptn 0.8.0, just the events look a bit different

## Keptn 0.8.0 + user_managed

Now comes the trouble. We want to solve the pain of shipping Keptn with Keptn, hence we wanted to introduce the user_managed deployment-strategy.

Right now the `user_managed` strategy is implemented the same way as `direct` deployments, just that we don't care about Istio and we don't care about the content of the helm-chart. 
This means the user is responsible providing helm-charts within the git repository in each stage/branch.

However, as pointed out by my before, there are cases (especially when thinking about deploying Keptn with Keptn) where I can NOT manually do that, especially when thinking about rollbacks and so on.

Hence, IMO, the helm-chart should be a parameter of the artifact-delivery cloud event.

## Alternative approach 1

I could add a step in every stage that tells me to update the helm-charts in the next stage manually. That's not CD though, that's manual deilvery then...

## Alternative approach 2

I can write my own service or use https://travis-ci.com/keptn-sandbox/generic-executor-service and implement the deployment step using `wget ${data.helmChart}` and `helm upgrade ...`.

**Comment by christian-kreuzberger-dtx** [comment]
# Limitation

Can not have a mixture of services with different deployment-strategy (blue-green / direct / user-managed)

```
keptn create service --project keptn keptn-control-plane
```

For instance, if you follow the guide above for onboarding Keptn with Keptn, you'll end up having the following `deployments` in namespace `keptn-dev`:

* api-gateway-nginx
* api-service
* bridge
* configuration-service
* lighthouse-service

What if a user now wants to create a new service called `bridge`, and onboard it with Keptn using a direct deployment? 
You'll get a conflict.

**Reply by agrimmer** [reply]
The finding is correct and this limitation was known.

**Reply by christian-kreuzberger-dtx** [reply]
How do we want to proceed with this limitation though? Do we want to document that it is not possible to mix those deployment-strategies within the same shipyard? Do we want to actually implement a check?

**Reply by johannes-b** [reply]
Am I correct that the problem is actually not the mix of deployment-strategies, but rather the conflict of the same `bridge` deployment? 
- `user_managed` deploys a `bridge` under the umbrella of the service: keptn-control-plane
- `direct` deploys a `bridge` under the umbrella of the service: bridge

From my understanding, the helm-service needs to return `result=fail` when it tries to deploy the second bridge; `message=Can`t deploy the service since there is already an identical deployment available` 

We should provide documentation for this behavior (limitation), but no check is needed from my point of view.

**Reply by christian-kreuzberger-dtx** [reply]
Correct.
But also think about the other way around:
What if the user deploys bridge using `direct` deployment, and afterwards deploys `keptn-control-plane` which also contains `bridge`.

**Comment by christian-kreuzberger-dtx** [comment]
# Problem: No deployment URIs are set

This has also already been identified in #2764, but I want to bring it up here again: Using the user-managed deployment-strategy we will not get `deploymentURIsLocal` nor `deploymentURIsPublic`.

I understand that when using user-managed deployments, we don't care about istio etc... - this is something the end-user needs to handle (it could even be that the end-user configures LoadBalancers for each deployment/service, so whatever...).

However, to be fully integrated with Keptn, helm-service needs to send a deployment.finished event with at least `deploymentURIsLocal` and maybe even `deploymentURIsPublic` set, such that follow-up tasks (e.g., tests using jmeter) can be completed successfully.

In my opinion we could introduce a config file within the repo where we define the URL, e.g., using placeholders like this:
`URL={service}.{stage}.{project}.my-awesome-host.com`
Users can then also change this, e.g., 
`URL=keptn-api.{stage}.my-super-awesome-host.io`

Alternatively, this could be something we allow the user to specify in the shipyard-file, e.g.:
```yaml
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
                deploymenturipublic: "api-gateway-nginx.{project}-{stage}.cluster.svc.local"
            - name: "test"
              properties:
                teststrategy: "functional"
            - name: "evaluation"
            - name: "release"

    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "dev.artifact-delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
                deploymenturipublic: "api-gateway-nginx.my-keptn-hardening.com"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
            - name: "release"

    - name: "production"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "staging.artifact-delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "user_managed"
                deploymenturipublic: "api-gateway-nginx.keptn.sh"
            - name: "release"
```
