### DISCUSSION TITLE
Should Keptn use ndots: 1 for dns config in all deployments?

### DISCUSSION THREAD

**Discussion by christian-kreuzberger-dtx** [keptn/keptn#3458] [Ideas]
related issue https://github.com/keptn/keptn.github.io/issues/664

Apparently using ndots 1 is much more performant and we can just overwrite this in our deployment.yamls:
```
spec:
  containers:
    - name: test
      image: nginx
  dnsConfig:
    options:
      - name: ndots
        value: "1"
```

Blog post: https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html

What's your opinion?
