### DISCUSSION TITLE
Push Any Metrics to Dynatrace

### DISCUSSION THREAD

**Discussion by ghost** [keptn/keptn#4858] [Show and tell]
Script to create a task which lets you ingest any metrics into Dynatrace:

# Create Sequence and Task
```
---
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: myshipyard
spec:
  stages:
    - name: production
      sequences:
        - name: pushmetrics
          tasks:
            - name: pushmetrics
```
Now apply: `keptn create project myproject --shipyard=shipyard.yaml`

Create your service: `keptn create service myservice --project=myproject`

# Install Generic Executor Service
Install the [generic-executor-service](https://github.com/keptn-sandbox/generic-executor-service)

# Create Task File
Create a file called `pushmetrics.triggered.py` with the following content:
```
import requests
import os

metrics_endpoint = os.getenv('DATA_METRICS_ENDPOINT','')
api_token = os.getenv('DATA_METRICS_API_TOKEN','')
metrics = os.getenv('DATA_METRICS','')

headers = {
  "Authorization": "Api-Token " + api_token,
  "Content-Type": "text/plain",
}

r = requests.post(metrics_endpoint + '/api/v2/metrics/ingest', data=metrics, headers=headers)
print(r.status_code)
print(r.text)
```

# Trigger Sequence w/ Payload

Trigger your sequence with a payload which includes the following properties inside `data`:
- `metrics_endpoint` (eg. `https://myKeptn.com` without trailing slash)
- `api_token` (Dynatrace API token with `Ingest Metrics` permissions)
- `metrics` (one per line)

```
{
  "data": {
    "project": "myproject",
    "service": "mydervice",
    "stage": "production",
    "labels": {
        "runBy": "AG"
    },
    "metrics_endpoint": "https://abc123.live.dynatrace.com",
    "metrics_api_token": "{{dynatraceAPIToken}}",
    "metrics": "postman.metric.test 1\npostman.metric.test 2"
  },
  "source": "POSTMAN",
  "specversion": "1.0",
  "shkeptnspecversion": "0.2.3",
  "contenttype": "application/json",
  "type": "sh.keptn.event.{{keptnStage}}.{{keptnSequence}}.triggered"
}
```
