### DISCUSSION TITLE
KEP 06 - Shipyard - Sequence Service Mapping

### DISCUSSION THREAD

**Discussion by christian-kreuzberger-dtx** [keptn/keptn#8999] [General]
With Keptn 0.8.0-alpha, you currently have to decide which sequence to run when sending a cloud-event to Keptn via the CLI, e.g.:

**Send new artifact for carts (-> artifact-delivery)**
```
keptn-080-alpha send event new-artifact --project=sockshop --service=carts \
     --image=docker.io/keptnexamples/carts --tag=0.12.3 --sequence=artifact-delivery
```

**Send new artifact for carts-db (-> artifact-delivery-db)**
```
keptn-080-alpha send event new-artifact --project=sockshop --service=carts-db \
                --image=docker.io/mongo --tag=4.2.2 --sequence=artifact-delivery-db
```

In addition, we have a smart-default that allows triggering evaluations without specifying a sequence, e.g:
```
keptn-080-alpha send event start-evaluation --project=sockshop --service=carts --stage=staging
```
This even works without specifying an evaluation workflow in Shipyard.yaml.

This raises several concerns:
1. As a Keptn end-user, you might not know that `carts` should be deployed using `artifact-delivery`, while `carts-db` should be deployed using `artifact-delivery-db`.
2. As a Keptn end-user, you might not know that you can run evaluations without specifying a sequence for it
3. `send event new-artifact` and `send event start-evaluation` seem to work fundamentally different and the command names have nothing to do with the actual Cloud-Events

**Comment by warber** [comment]
What makes most sense for me is something like that:

Creating the serivce (a.k.a. keptn onboard service):
`keptn create service carts-db --project=sockshop --chart=./carts-db --sequence=artifact-delivery-db`

Updating the service:
`keptn update service carts-db --sequence=artifact-delivery-db-fast`

Deploy new version of service:
`keptn deploy service carts-db --image=docker.io/monogo --tag=4.2.2`

**Reply by christian-kreuzberger-dtx** [reply]
In general I like the idea to specify a "default sequence" when creating or updating a service.

One thing that comes in my mind is: What happens when someone edits the Shipyard, and removes or renames the sequence?

One more thing: Instead of
```
keptn deploy service ...
```
I'd rather use 
```
keptn trigger deployment
```

**Reply by warber** [reply]
> What happens when someone edits the Shipyard, and removes or renames the sequence?

```
$ keptn deploy service carts-db --image=docker.io/monogo --tag=4.2.2
Error: unable to deploy service "carts-db": Sequence "artifact-delivery-db" not found. Please update your service definition.
Available sequences:
 - artifact-delivery-db-changed
 - artifact-delivery-db-fast
```

**Reply by johannes-b** [reply]
The more I think about this idea, the more I like it.

My two cents on that:
- Let's build a smart default meaning that the shipyard-controller creates or onboard a service when the user forgets about the sequence and just one sequence is defined for the first stage in the shipyard. 
- When the user forgets about the sequence, the CLI will not run into an error, but rather provide the options (`(1) artifact-delivery, (2) artifact-delivery-fast`) the user can choose from. Then creating/onboarding will be done again.  
- Technically, with the flag `--sequence=artifact-delivery-db` we create the mapping between `new-artifact` : `sequence_in_first_stage`
- Even though `keptn deploy service carts-db --image=docker.io/monogo --tag=4.2.2` is much cleaner, I would stay with `keptn send event new-artifact` because how can Keptn know that my specified sequence is actually responsible for deployment.

**Reply by bacherfl** [reply]
One thing we are still missing in the shipyard in this case is how we know which of the available sequences are actually responsible for deploying a new artifact - my thought on this would be to add a `type` property to each sequence, e.g.:

```
spec:
  stages:
    - name: "dev"
      sequences:
       - name: "artifact-delivery-default"
          type: "artifact-delivery"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
        - name: "artifact-delivery-db"
          type: "artifact-delivery"
          tasks:
            - name: "deployment"
            - name: "release"
            
       - name: "evaluation-default"
         type: "evaluation"
         tasks:
            - name: "test"
            - name: "evaluation"
```

This way, we could streamline the usage of the `send event new-artifact` and `send event start-evaluation`, and use a more generic
command, like e.g. `keptn trigger artifact-delivery`, or `keptn trigger evaluation` - by passing the type of the sequence that should be triggered, like `artifact-delivery` or `evaluation`, the CLI can fetch the available sequences for these types and ask the user which one to choose (if it has not been specified already).
The other question, when using this approach, is how to pass the required arguments for these sequences. These can be either specified explicitly at the definition of the task sequence, or maybe it is possible to automatically determine them based on the first task of the sequence (e.g. if the first task in the sequence is `deployment`, the properties of the correlating `sh.keptn.event.deployment.triggered` event should be set.

**Comment by christian-kreuzberger-dtx** [comment]
In case we want to keep the domain event `new-artifact` and the CLI like this:
```
keptn-080-alpha send event new-artifact --project=sockshop --service=carts \
     --image=docker.io/keptnexamples/carts --tag=0.12.3
```

Then we should also include it in our shipyard, and be very explicit about it:
```yaml
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          triggers:
           - "new-artifact"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
        - name: "artifact-delivery-db"
          tasks:
            - name: "deployment"
            - name: "release"

    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "dev.artifact-delivery.finished"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"

        - name: "artifact-delivery-db"
          triggers:
            - "dev.artifact-delivery-db.finished"
          tasks:
            - name: "deployment"
            - name: "release"

    - name: "production"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "staging.artifact-delivery.finished"
          tasks:
            - name: "deployment"
            - name: "release"

        - name: "artifact-delivery-db"
          triggers:
            - "staging.artifact-delivery-db.finished"
          tasks:
            - name: "deployment"
            - name: "release"
```

With this approach it is still possible to choose a different sequence by providing it as a parameter, e.g.:
```
keptn-080-alpha send event new-artifact --project=sockshop --service=carts-db \
                --image=docker.io/mongo --tag=4.2.2 --sequence=artifact-delivery-db
```

The same would be true for `start-evaluation`, e.g.:
```
keptn-080-alpha send event start-evaluation --project=sockshop --service=carts --stage=staging
```
Shipyard:
```yaml
spec:
  stages:
    - name: "hardening"
      sequences:
        - name: "my-sequence"
          triggers:
            - "start-evaluation"
          tasks:
            - name: "evaluation"
```

This way the impact on the end-user is minimalistic, as they can keep using `keptn send event start-evaluation` and `keptn send event new-artifact`.
However, we should consider that `start-evaluation` and `new-artifact` are specified as proper cloud-events.

**Reply by johannes-b** [reply]
(I have no final opinion whether I like this or the above-mentioned idea (from @warber) better but) I'm in favor of making the domain events (i.e., `new-artifact`, `start-evaluation`, `problem.open`) explicit if we go this way. 

However, we still have the limitation that each domain event (e.g., `new-artifact`) can be set just once, in other words, this won`t be allowed:

```
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          triggers:
           - "new-artifact"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
            
        - name: "artifact-delivery-db"
          triggers:
            - "new-artifact"
          tasks:
            - name: "deployment"
            - name: "release"
```

And this needs to be verified and cannot be controlled when someone edits the shipyard on the Git repo afterward. 
Besides, it is confusing why I would say (`keptn send event new-artifact`):  
```
keptn-080-alpha send event new-artifact --project=sockshop --service=carts-db \
                --image=docker.io/mongo --tag=4.2.2 --sequence=artifact-delivery-db
```
and this time the `new-artifact` is overruled by specifying the sequence name. 

(Yet, I have no idea for another option and need some time to think about it.)
