### DISCUSSION TITLE
KEP 06 - Shipyard - Allow aborting sequences / connecting failed sequence.tasks with another sequence

### DISCUSSION THREAD

**Discussion by christian-kreuzberger-dtx** [keptn/keptn#9000] [General]
Let's assume this is our sequence for `staging.artifact-delivery`:

```
    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
            - name: "release"
```

We now deploy an artifact for which the tests fail, therefore there is a cloud-event `sh.keptn.event.test.finished` with `status=fail`.

In Keptn 0.8.0-alpha this is what happens:

* `dev.artifact-delivery.triggered`
  * ...
* `dev.artifact-delivery.finished`
* `staging.artifact-delivery.triggered`
  * `staging.deployment.triggered` -> `.started` -> `.finished`
  * `staging.test.triggered` -> `.started` -> `.finished(status=fail)`
  * `staging.evaluation.triggered` -> `.started` -> `.finished` (this happens although `test` failed)
  * `staging.release.triggered` -> `.started` -> `.finished` (this is actually required to happen, als `helm-service` performs the rollback here)
* `staging.artifact-delivery.finished`
* STOP

In KEP 06 it was proposed to implement selectors / matchExpressions to trigger sequences (e.g., a rollback sequence) if a task has failed:
https://github.com/keptn/enhancement-proposals/pull/6/files#diff-bea142ed84ef95941ac378353c504971b732df7e155325ae5b79ff9794b061ffR123-R136

However, this was not implemented with Keptn 0.8.0-alpha yet.

Within this discussion we want to discuss the pro and cons of each approach.

Some things that we have already discussed:

We want a linear flow within a sequence (so we don't want if/else statements within a sequence)

**Comment by christian-kreuzberger-dtx** [comment]
In my opinion conditionals are required for many scenarios, here are some examples:

* If the deployment succeeded, but tests have failed, maybe we want to inspect the result, and be able to manually approve and continue anyway
* If the deployment succeeded, tests are also okay, but the quality-gate fails, I might have a sequence that deploys the artifact to yet another stage (e.g., `qa-urgent`) and notifies a QA team about this to look into it

In short, I believe that when a `status: failed` is returned by a task, the sequence should stop where it is and send a `sequence.finished` with `status=failed`.

If anyone wants to create a hook for this case, then it should be possible using the matchExpression feature described in KEP 06, example:
```yaml
    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
            - name: "release"

        - name: "rollback"
          triggers:
          - staging.artifact-delivery.test.finished:
              selector:
                matchLabels:
                  status: failed
          - staging.artifact-delivery.deployment.finished:
              selector:
                matchLabels:
                  status: failed
          - staging.artifact-delivery.evaluation.finished:
              selector:
                matchExpressions:
                  - {key: status, operator: In, values: [warning, failed]}
          tasks:
          - name: rollback
```

Maybe it would even be possible to simplify it using
```yaml
    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
            - name: "release"

        - name: "rollback"
          triggers:
          - staging.artifact-delivery.finished:
              selector:
                matchLabels:
                  status: failed
          tasks:
          - name: rollback
```
