### ISSUE TITLE
Configuration of custom SLI queries for prometheus SLI service

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#1018]
Allow to override SLI queries for the prometheus-sli-service. Queries should be configurable on a global level (for the complete Keptn installation) and project-specific.

Format:

### Global
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-sli-service-config
  namespace: keptn
data:
  custom-queries: |
    throughput: "rate(my_custom_metric{job='$SERVICE-$PROJECT-$STAGE',handler=~'$handler'}[$DURATION_SECONDS])"
    errorRate: "sum(rate(my_custom_metric{job='$SERVICE-$PROJECT-$STAGE',handler=~'$handler',status!~'2..'}[1s]))/sum(rate(my_custom_metric{job='$SERVICE-$PROJECT-$STAGE',handler=~'$handler'}[$DURATION_SECONDS]))"
    requestLatencyP50: "histogram_quantile(0.50,sum(rate(my_custom_response_time_metric{job='$SERVICE-$PROJECT-$STAGE'}[$DURATION_SECONDS]))by(le))"
    requestLatencyP90: "histogram_quantile(0.90,sum(rate(my_custom_response_time_metric{job='$SERVICE-$PROJECT-$STAGE'}[$DURATION_SECONDS]))by(le))"
    requestLatencyP95: "histogram_quantile(0.95,sum(rate(my_custom_response_time_metric{job='$SERVICE-$PROJECT-$STAGE'}[$DURATION_SECONDS]))by(le))"
```

### Per Project

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-sli-service-config-${PROJECT_NAME}
  namespace: keptn
data:
  custom-queries: |
"histogram_quantile(0.90,sum(rate(my_custom_response_time_metric{job='$SERVICE-$PROJECT-$STAGE'}[$DURATION_SECONDS]))by(le))"
    requestLatencyP95: "histogram_quantile(0.95,sum(rate(my_custom_response_time_metric{job='$SERVICE-$PROJECT-$STAGE'}[$DURATION_SECONDS]))by(le))"
```
