### ISSUE TITLE
Configuration of custom SLI queries for dynatrace SLI service

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1041]
Same as #1018 but for Dynatrace SLI Service.

Format: 

### Global
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynatrace-sli-service-config
  namespace: keptn
data:
  custom-queries: |
    throughput: "com.dynatrace.builtin:service.requests,count,0"
    errorRate: "com.dynatrace.builtin:service.failurerate,avg,0"
    myMetric: "whatever.io.metrics:foo.bar,..."
```

### Per Project

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynatrace-sli-service-config-${PROJECT_NAME}
  namespace: keptn
data:
  custom-queries: |
    throughput: "com.dynatrace.builtin:foo.bar,avg,0"
    myMetric: "whatever.io.metrics:foo.bar,..."
```
