### ISSUE TITLE
Blue-Green Deployment: Promotion to next stage leads to 1 minute downtime

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1086]
This just happened with the latest version within the develop branch:

edit: I'm not sure if this is a problem with our deployment/helm/tiller, or if this is a problem with sockshop. As it is close before the weekend I wanted to get this problem written down so we can investigate next week.

# Steps to reproduce
* Onboarded carts and carts-db
* new artifact 0.9.1
* installed dynatrace-service and oneagent
* installed dynatrace-sli-service
* new artifact 0.9.2

![Screenshot from 2019-11-08 13-13-23](https://user-images.githubusercontent.com/56065213/68475944-c2014800-0229-11ea-82fc-c7c0f72d8eca.png)

Between Configuration Change and Deployment Finished I was unable to access carts.sockshop-staging.*.xip.io
After deployment finished I was able to access 0.9.2.

shipyard.yaml
```
stages:
  - name: "dev"
    deployment_strategy: "direct"
    test_strategy: "functional"
  - name: "staging"
    deployment_strategy: "blue_green_service"
    test_strategy: "performance"
  - name: "production"
    deployment_strategy: "blue_green_service"
    remediation_strategy: "automated"
```

# Expected behaviour
When using deployment strategy blue-green there should be no downtime. It should seamlessly switch from 0.9.1 to 0.9.2 as soon as 0.9.2 is ready.
