### ISSUE TITLE
Bridge/Lighthouse: Empty evaluation results need to be displayed properly

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1125]
SLO File:

```yaml
---
spec_version: '1.0'
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  aggregate_function: avg
objectives:
  - sli: response_time_p95
    pass:        # pass if (relative change <= 10% AND absolute value is < 500)
      - criteria:
          - "<=+10%" # relative values require a prefixed sign (plus or minus)
          - "<600"   # absolute values only require a logical operator
    warning:     # if the response time is below 800ms, the result should be a warning
      - criteria:
          - "<=800"
  - sli: response_time_p95
      pass:        # pass if (relative change <= 10% AND absolute value is < 500)
          - criteria:
            - "<=+10%" # relative values require a prefixed sign (plus or minus)
            - "<600"   # absolute values only require a logical operator
      warning:     # if the response time is below 800ms, the result should be a warning
        - criteria:
            - "<=800"
  - sli: response_time_p50
    pass:
      - criteria:
          - "<=+20%"
          - "<500"
  - sli: throughput
  - sli: error_rate
    pass:
      - criteria:
          - "=0"
    warning:
      - criteria:
          - "<5"
total_score:
  pass: "90%"
  warning: 75%
```

# Case 1: Display Throughput in Bridge

The following evaluation result is not displayed properly in bridge:

```json
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "blue_green_service",
    "evaluationdetails": {
      "indicatorResults": [
        {
          "score": 1,
          "status": "pass",
          "targets": [
            {
              "criteria": "<=+10%",
              "targetValue": 397.2740342965678,
              "violated": false
            },
            {
              "criteria": "<600",
              "targetValue": 600,
              "violated": false
            }
          ],
          "value": {
            "metric": "response_time_p95",
            "success": true,
            "value": 304.4725251337717
          }
        },
        {
          "score": 1,
          "status": "pass",
          "targets": [
            {
              "criteria": "<=+20%",
              "targetValue": 0,
              "violated": false
            },
            {
              "criteria": "<500",
              "targetValue": 500,
              "violated": false
            }
          ],
          "value": {
            "metric": "response_time_p50",
            "success": true,
            "value": 137.07392458059311
          }
        },
        {
          "score": 0,
          "status": "",
          "targets": null,
          "value": {
            "metric": "throughput",
            "success": true,
            "value": 7
          }
        },
        {
          "score": 1,
          "status": "pass",
          "targets": [
            {
              "criteria": "=0",
              "targetValue": 0,
              "violated": false
            }
          ],
          "value": {
            "metric": "error_rate",
            "success": true,
            "value": 0
          }
        }
      ],
      "result": "warning",
      "score": 75,
      "sloFileContent": "Y29tcGFyaXNvbjoKICBhZ2dyZWdhdGVfZnVuY3Rpb246IGF2ZwogIGNvbXBhcmVfd2l0aDogc2luZ2xlX3Jlc3VsdAogIGluY2x1ZGVfcmVzdWx0X3dpdGhfc2NvcmU6IHBhc3MKICBudW1iZXJfb2ZfY29tcGFyaXNvbl9yZXN1bHRzOiAzCmZpbHRlcjogbnVsbApvYmplY3RpdmVzOgotIGtleV9zbGk6IGZhbHNlCiAgcGFzczoKICAtIGNyaXRlcmlhOgogICAgLSA8PSsxMCUKICAgIC0gPDYwMAogIHNsaTogcmVzcG9uc2VfdGltZV9wOTUKICB3YXJuaW5nOgogIC0gY3JpdGVyaWE6CiAgICAtIDw9ODAwCiAgd2VpZ2h0OiAxCi0ga2V5X3NsaTogZmFsc2UKICBwYXNzOgogIC0gY3JpdGVyaWE6CiAgICAtIDw9KzIwJQogICAgLSA8NTAwCiAgc2xpOiByZXNwb25zZV90aW1lX3A1MAogIHdhcm5pbmc6IG51bGwKICB3ZWlnaHQ6IDEKLSBrZXlfc2xpOiBmYWxzZQogIHBhc3M6IG51bGwKICBzbGk6IHRocm91Z2hwdXQKICB3YXJuaW5nOiBudWxsCiAgd2VpZ2h0OiAxCi0ga2V5X3NsaTogZmFsc2UKICBwYXNzOgogIC0gY3JpdGVyaWE6CiAgICAtID0wCiAgc2xpOiBlcnJvcl9yYXRlCiAgd2FybmluZzoKICAtIGNyaXRlcmlhOgogICAgLSA8NQogIHdlaWdodDogMQpzcGVjX3ZlcnNpb246ICIxLjAiCnRvdGFsX3Njb3JlOgogIHBhc3M6IDkwJQogIHdhcm5pbmc6IDc1JQo=",
      "timeEnd": "2019-11-20T06:36:15Z",
      "timeStart": "2019-11-20T06:34:31Z"
    },
    "project": "sockshop",
    "result": "warning",
    "service": "carts",
    "stage": "staging",
    "teststrategy": "performance"
  },
  "id": "0f0281bb-9022-403b-a1c4-dac93a21442c",
  "source": "lighthouse-service",
  "specversion": "0.2",
  "time": "2019-11-20T06:38:17.454Z",
  "type": "sh.keptn.events.evaluation-done",
  "shkeptncontext": "4a98cf33-4db3-45b2-999a-287a806e867d"
}
```

Bridge:
![Screenshot from 2019-11-20 08-34-01](https://user-images.githubusercontent.com/56065213/69218592-55fbd980-0b71-11ea-8877-c2f2bcbdea2c.png)

I believe in such a case (throughput is only listed in slo.yaml as a "value", not as something that should fail/pass), we should just display the value of throughput within bridge.

# Case 2: 

I believe this is an error of lighthouse, as the evaluation returned an emtpy result for `response_time_p50`:

```json
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "blue_green_service",
    "evaluationdetails": {
      "indicatorResults": [
        {
          "score": 0,
          "status": "failed",
          "targets": [
            {
              "criteria": "<=800",
              "targetValue": 800,
              "violated": true
            },
            {
              "criteria": "<=+10%",
              "targetValue": 0,
              "violated": false
            },
            {
              "criteria": "<600",
              "targetValue": 600,
              "violated": true
            }
          ],
          "value": {
            "metric": "response_time_p95",
            "success": true,
            "value": 1070.886915292414
          }
        },
        {
          "score": 0,
          "status": "",
          "targets": [
            {
              "criteria": "<=+20%",
              "targetValue": 0,
              "violated": false
            },
            {
              "criteria": "<500",
              "targetValue": 500,
              "violated": true
            }
          ],
          "value": {
            "metric": "response_time_p50",
            "success": true,
            "value": 1011.0745528937252
          }
        },
        {
          "score": 0,
          "status": "",
          "targets": null,
          "value": {
            "metric": "throughput",
            "success": true,
            "value": 7
          }
        },
        {
          "score": 1,
          "status": "pass",
          "targets": [
            {
              "criteria": "=0",
              "targetValue": 0,
              "violated": false
            }
          ],
          "value": {
            "metric": "error_rate",
            "success": true,
            "value": 0
          }
        }
      ],
      "result": "fail",
      "score": 25,
      "sloFileContent": "Y29tcGFyaXNvbjoKICBhZ2dyZWdhdGVfZnVuY3Rpb246IGF2ZwogIGNvbXBhcmVfd2l0aDogc2luZ2xlX3Jlc3VsdAogIGluY2x1ZGVfcmVzdWx0X3dpdGhfc2NvcmU6IHBhc3MKICBudW1iZXJfb2ZfY29tcGFyaXNvbl9yZXN1bHRzOiAzCmZpbHRlcjogbnVsbApvYmplY3RpdmVzOgotIGtleV9zbGk6IGZhbHNlCiAgcGFzczoKICAtIGNyaXRlcmlhOgogICAgLSA8PSsxMCUKICAgIC0gPDYwMAogIHNsaTogcmVzcG9uc2VfdGltZV9wOTUKICB3YXJuaW5nOgogIC0gY3JpdGVyaWE6CiAgICAtIDw9ODAwCiAgd2VpZ2h0OiAxCi0ga2V5X3NsaTogZmFsc2UKICBwYXNzOgogIC0gY3JpdGVyaWE6CiAgICAtIDw9KzIwJQogICAgLSA8NTAwCiAgc2xpOiByZXNwb25zZV90aW1lX3A1MAogIHdhcm5pbmc6IG51bGwKICB3ZWlnaHQ6IDEKLSBrZXlfc2xpOiBmYWxzZQogIHBhc3M6IG51bGwKICBzbGk6IHRocm91Z2hwdXQKICB3YXJuaW5nOiBudWxsCiAgd2VpZ2h0OiAxCi0ga2V5X3NsaTogZmFsc2UKICBwYXNzOgogIC0gY3JpdGVyaWE6CiAgICAtID0wCiAgc2xpOiBlcnJvcl9yYXRlCiAgd2FybmluZzoKICAtIGNyaXRlcmlhOgogICAgLSA8NQogIHdlaWdodDogMQpzcGVjX3ZlcnNpb246ICIxLjAiCnRvdGFsX3Njb3JlOgogIHBhc3M6IDkwJQogIHdhcm5pbmc6IDc1JQo=",
      "timeEnd": "2019-11-20T07:11:00Z",
      "timeStart": "2019-11-20T07:02:20Z"
    },
    "project": "sockshop",
    "result": "fail",
    "service": "carts",
    "stage": "staging",
    "teststrategy": "performance"
  },
  "id": "276cf082-959d-4175-892c-9b217be7c1d6",
  "source": "lighthouse-service",
  "specversion": "0.2",
  "time": "2019-11-20T07:13:02.344Z",
  "type": "sh.keptn.events.evaluation-done",
  "shkeptncontext": "3c9dfc69-4e5e-4a1a-bb2b-3bd3eaa4e81b"
}
```

Obviously this is also not displayed correctly within bridge (but I believe the issue lies within lighthouse in this case):
![Screenshot from 2019-11-20 08-41-36](https://user-images.githubusercontent.com/56065213/69218732-9bb8a200-0b71-11ea-9eb1-70814ac045c0.png)
