### ISSUE TITLE
Keptn on Openshift with Token instead of username/password

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1194]
In case someone is using Openshift with an SSO in front of Openshift, they won't be able to use the username/password combination as we ask for in `keptn install --platform=openshift`.

Instead, a token is used.

**Inofficial workaround for now** (thanks to @bacherfl ):

Apply the installer.yaml manually using `oc apply`:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: installer
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: installer
    spec:
      volumes:
      - name: kubectl
        emptyDir: {}
      containers:
      - name: keptn-installer
        image: keptn/installer:0.5.2
        env:       
        - name: PLATFORM
          value: openshift
      restartPolicy: OnFailure
```

and authenticate manually using

```console
keptn auth --endpoint=https://api.keptn.$(kubectl get cm -n keptn keptn-domain -ojsonpath={.data.app_domain}) --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)
```
