### ISSUE TITLE
Dynatrace SLI Service: Allow SLIs to be defined without scope and auto-apply a scope

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1223]
Allow users to define metrics as follows:

```
data:
  custom-queries: |
    throughput: "builtin:service.requestCount.total:merge(0):count"
    error_rate: "builtin:service.errors.total.count:merge(0):avg"
    response_time_p50: "builtin:service.response.time:merge(0):percentile(50)"
    response_time_p90: "builtin:service.response.time:merge(0):percentile(90)"
    response_time_p95: "builtin:service.response.time:merge(0):percentile(95)"
```
per metric: If no `scope=` query param is present, we can auto apply the following scope:
```
scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)
```

If a scope is present, we do not auto apply that scope.
