### ISSUE TITLE
Use https for onboarded services

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1231]
Currently, the onboarded services can be accessed via http. 
We need a way to access them via `https`.
One possible approach is to correspondingly adapt the generated `Gateways` in the `helm-service`.
@christian-kreuzberger-dtx  @bacherfl: What approach do you prefer?

**Comment by christian-kreuzberger-dtx** [comment]
Just a quick analysis:

For each project and stage we have a gateway that looks as follows:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  generation: 1
  name: someproject-staging-gateway
  namespace: someproject-staging
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

and then the virtual service looks like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  generation: 1
  name: some-service
  namespace: someproject-staging
spec:
  gateways:
  - someproject-staging-gateway.someproject-staging
  - mesh
  hosts:
  - some-service.someproject-staging.gke.demo.keptn.sh
  - some-service
  http:
  - route:
    - destination:
        host: some-service.someproject-staging.svc.cluster.local
```
