### ISSUE TITLE
Sending non-cloud events to /v1/event 

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1253]
When sending a start-evaluation event to /v1/event this is not a true cloudevent, e.g.:
```json
{
    "type": "sh.keptn.event.start-evaluation",
    "data": {...}
}
```

We need to discuss whether this should be a full cloud-event.

**Solution: We will accept non-cloud events for now. This needs to be documented and reflected in swagger.yaml.**
**enforce `type`, `data` and `source`**, everything else is optional.

**Comment by johannes-b** [comment]
In an investigation, we figured out that the CloudEvent spec defines properties as required but Swagger does not verify them. 

Swagger model: https://github.com/keptn/keptn/blob/release-0.6.0.beta2/api/swagger.yaml#L42

Required are: 
``` 
      "required": [
        "specversion",
        "id",
        "type",
        "source"
      ],
```

**Comment by christian-kreuzberger-dtx** [comment]
It seems like that the swagger library we use is not able (or not allowed to?) fetch/parse the json file referenced in `$ref`.
```
      parameters:
        - name: body
          in: body
          schema:
            $ref: "https://raw.githubusercontent.com/cloudevents/spec/v0.2/spec.json#/definitions/event"
```

The other references to local files seem to work fine

```
parameters:
  project:
    in: body
    name: project
    description: Project entity
    schema:
      $ref: "project_model.yaml#/definitions/project"
```
