### ISSUE TITLE
Helm-service does not regenerate virtualservices for direct deployments

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1315]
**Current implementation:** The helm-service regenerates VirtualServices for blue-green deployments, but they are not regenerated for direct deployments.

**Problem:** When upgrading from Keptn 0.6.0.beta2 to Keptn 0.6.0, this leads to an issue as the gateway has been changed to a single public gateway in the Istio-system namespace.

**Gateway in dev for direct deployments**
```yaml
spec:
  gateways:
  - cksockshop-dev-gateway.sockshop-dev
  - mesh
  hosts:
  - carts.sockshop-dev.KEPTN_DOMAIN
  - carts
  http:
  - route:
    - destination:
        host: carts.sockshop-dev.svc.cluster.local
```

**Gateway in staging for blue-green deployments**
```yaml
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-staging.KEPTN_DOMAIN
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.sockshop-staging.svc.cluster.local
    - destination:
        host: carts-primary.sockshop-staging.svc.cluster.local
      weight: 100
```
