### ISSUE TITLE
Quality Gates for external Deployments Tutorial: keptn_deployment tag is misleading

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1391]
In the *Quality Gates for external Deployments* tutorial and when validating a Dynatrace-monitored service, the **keptn_deployment** tag is misleading and has no meaning. There is no reason why this tag is needed. 

**Solution**: In the tutorial, the tag should be removed and a custom SLI configuration should be provided, to override the default SLI queries as implemented in the dynatrace-sli-service. The custom SLI configuration has to look as follows: 
```
---
spec_version: '1.0'
indicators:
  throughput: "builtin:service.requestCount.total:merge(0):count?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE))"
  error_rate: "builtin:service.errors.total.count:merge(0):avg?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE))"
  response_time_p50: "builtin:service.response.time:merge(0):percentile(50)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE))"
  response_time_p90: "builtin:service.response.time:merge(0):percentile(90)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE))"
  response_time_p95: "builtin:service.response.time:merge(0):percentile(95)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE))"
```
