### ISSUE TITLE
Lighthouse: Evaluating "<=5%" actually evaluates "<=5" (missing percent sign)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1498]
I know this is not defined in the spec, but it is an error that a user can easily do when defining SLOs:

```
objectives:
  - sli: response_time_p95
    pass:
      - criteria:
          - "<=10%"
```

This will actually evaluate `response_time_p95 <= 10`, as the `+` sign is missing.

This is suboptimal, as the percent sign indicates a relative value, and all that is missing is the `+`.

I believe that we should either warn the user or just accept `<=10%` as `<=+10%`
