### ISSUE TITLE
Move Keptn's MongoDB Credentials into a Kubernetes secret

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1528]
Right now the credentials for MongoDB are specified as environment variables within the deployment yaml file:
https://github.com/keptn/keptn/blob/dde5c73b09ece5cf30e48f77cbeb257584052329/mongodb-datastore/deploy/manifests-db/deployment.yaml#L20-L31

I recommend that we move them to a Kubernetes secret (and also pass the secret to the mongodb-datastore), and rewrite the deployment to use the secret:

```yaml
                  env:
                      - name: MONGODB_USER
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-credentials
                                key: user

                      - name: MONGODB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-credentials
                                key: password

                      - name: MONGODB_ADMIN_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-credentials
                                key: adminpassword
```
