### ISSUE TITLE
Make JMeter workload parameters VUsers & Loop Count configurable in git repo

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#1567]
Right now the JMeter service has a lot of the workload parameters hard coded. That includes: script name, VUCount, LoopCount, ThinkTime. 

This makes our current approach unflexible. The workaround for users is to not use these parameters but hard code their values into the JMeter script and then always have to change the JMeter scripts in case they want to run different workfloads.

My proposal is to allow users to define a jmeter.conf file in the keptn config repo that allows them to specify workload parameters per teststrategy. Here is an example

```
spec_version: '0.1.0'
workloads:
  - teststrategy: performance
    vuser: 200
    loopcount: 50
    script: load.jmx
  - teststrategy: performance_light
    vuser: 50
    loopcount: 10
    script: load.jmx
  - teststrategy: functional
    vuser: 1
    loopcount: 1
    script: func.jmx
```

This approach not only gives the user flexibilty in defining their own workload parameters - it also allows them to define additional test strategies which opens up new posiblities for the "Performance Testing as a Self-Service" Use Case. If a user defines different workloads a user of keptn can simply send deployment-finished events and pass in the teststrategy they want to execute
