### ISSUE TITLE
Enhance distributor with filtering

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1610]
Right now the distributor is able to subscribe to one or multiple events.

For future use-cases we want to be able to configure the distributor to also parse the payload and filter based on the payload.

_Example:_
```
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.internal.event.get-sli'
            - name: PUBSUB_FILTER
              value: 'data.project == "sockshop"'
            - name: PUBSUB_RECIPIENT
              value: 'dynatrace-sli-service'
```

In addition, it is important to consider that one can subscribe to multiple topics within a single distributor, e.g.:

```
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.internal.event.get-sli,sh.keptn.internal.event.configure-monitoring'
            - name: PUBSUB_FILTER
              value: 'data.project == "sockshop"'
            - name: PUBSUB_RECIPIENT
              value: 'dynatrace-sli-service'
```

For this use-case, we need to figure out what the desired behavior of `PUBSUB_FILTER` should be. Either it should apply to all topics and all events, or we need a way to specify the topic it should listen to. An alternative syntax could also look as follows:

```
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.internal.event.get-sli(data.project == "sockshop"),sh.keptn.internal.event.configure-monitoring'
            - name: PUBSUB_RECIPIENT
              value: 'dynatrace-sli-service'
```

For this implementation, please also consider that in the future the subscription will be part of the [Keptn Uniform](https://github.com/keptn/enhancement-proposals/pull/7/files), e.g.:

```yaml
version: 0.1.0
kind: Uniform
metadata:
  name: uniform-abc
spec:
  services:
    - name: dynatrace-sli-provider
      image: keptncontrib/dynatrace-sli-service:0.6.1
      events:
        - get.sli.triggered:
            selector:
              matchLabels:
                project: sockshop
```
