### ISSUE TITLE
CLI: Implement get projects, services, stages and metadata

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#1624]
From [KEP 10](https://github.com/keptn/enhancement-proposals/pull/10).

After #1621, #1622 and #1623 are done, we need to implement the same functionality within the CLI, but in a very generic way.

Examples:

* `keptn get projects` -> returns a list of projects
* `keptn get projects --project=sockshop` -> returns infos for the selected project
* `kepn get services` -> returns a list of services (for all projects)
* `keptn get services --project=sockshop` -> returns a list of services for project sockshop
* `keptn get stages` -> does not make sense, right?
* `keptn get stages --project=sockshop` -> returns a list of stages for the given project
* Every call should work with singular and plural (e.g., `keptn get project` vs. `keptn get projects`).

For every call, we just take the result from the API, and display the result (in a nice way). Do not create any "hard dependencies" in Go (e.g., models) for this, we want this to be as generic as custom resources in Kubernetes.

**Comment by agrimmer** [comment]
In order to stay consistent within our CLI commands
`keptn get projects --project=sockshop` should be `keptn get project sockshop`

Right, `keptn get stages` makes no sense without any project.

**Comment by robertjahn** [comment]
I suggest for the get project <project name> -- that this includes the upstream repo info or say NONE

Consider the verb "describe" like kubectl does `describe       Show details of a specific resource or group of resources`

**Comment by johannes-b** [comment]
The following commands should return: 

**Project:**
* `keptn get projects`:
```
NAME           CREATION DATE                 
sockshop       2020-04-06T14:35:40.210Z
musicshop      2020-04-06T14:37:45.210Z
```

* `keptn get project sockshop`:
```
NAME           CREATION DATE                 
sockshop       2020-04-06T14:35:40.210Z
```

* `keptn get project sockshop --output=yaml`:
```
projects:
- creationDate: '1587455680742808213'
  projectName: sockshop
  stages:
  - services:
    - creationDate: '1587455682123389180'
      deployedImage: docker.io/keptnexamples/carts:0.10.1
      lastConfigurationChangedEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587455897846488861'
      lastDeploymentFinishedEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587455890460007826'
      lastEvaluationDoneEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587455897836900102'
      lastTestsFinishedEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587455897784730616'
      serviceName: carts
    - creationDate: '1587455684099120704'
      deployedImage: mongo:latest
      lastConfigurationChangedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455715219926808'
      lastDeploymentFinishedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455715080359788'
      lastEvaluationDoneEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455715211049428'
      lastTestsFinishedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455715141614393'
      serviceName: carts-db
    stageName: dev
  - services:
    - creationDate: '1587455682520379441'
      deployedImage: docker.io/keptnexamples/carts:0.10.1
      lastConfigurationChangedEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587456255585813017'
      lastDeploymentFinishedEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587456043573743587'
      lastEvaluationDoneEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587456255573015663'
      lastTestsFinishedEvent:
        keptnContext: 01ad3740-53bb-47b6-bb7f-08c3707fa7f4
        time: '1587456134489806630'
      serviceName: carts
    - creationDate: '1587455684458755617'
      deployedImage: mongo:latest
      lastConfigurationChangedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455748666986438'
      lastDeploymentFinishedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455748596976925'
      lastEvaluationDoneEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455748662272091'
      lastTestsFinishedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455748635005166'
      serviceName: carts-db
    stageName: staging
  - services:
    - creationDate: '1587455682926330459'
      serviceName: carts
    - creationDate: '1587455684851895739'
      deployedImage: mongo:latest
      lastConfigurationChangedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455774134741647'
      lastDeploymentFinishedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455774073225908'
      lastEvaluationDoneEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455774128903983'
      lastTestsFinishedEvent:
        keptnContext: 01073472-e6dc-4904-a6e3-4a4e3f15302c
        time: '1587455774125038931'
      serviceName: carts-db
    stageName: production
totalCount: 1
```

**Service:**
* `keptn get services`: 
```
NAME           CREATION DATE                 
carts          2020-04-06T14:35:40.210Z
carts-db       2020-04-06T14:52:52.210Z
catalogue      2020-04-12T16:00:40.210Z
```

* `keptn get service carts --project=sockshop`:
```
NAME           CREATION DATE                 
carts          2020-04-06T14:35:40.210Z
carts-db       2020-04-06T14:52:52.210Z
```

* `keptn get service carts --project=sockshop -o=yaml`: **TBD** depends on https://github.com/keptn/keptn/issues/1673

**Stage:**
* `keptn get stages --project=sockshop`
```
NAME           CREATION DATE                 
dev            2020-04-06T14:35:40.210Z
staging        2020-04-06T14:37:45.210Z
production     2020-04-06T14:37:45.210Z
```

* `keptn get stage staging --project=sockshop`
```
NAME           CREATION DATE                 
staging        2020-04-06T14:37:45.210Z
```

* `keptn get stage staging --project=sockshop -o=yaml`: **TBD** depends on https://github.com/keptn/keptn/issues/1673
