### ISSUE TITLE
Keptn Core (gatekeeper): Read approval_strategy and send event based on configured strategy and evaluation result

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1658]
The implementation of the approval strategy is based on the event stream outlined here: #1561  

The specification of the shipyard is here: https://github.com/keptn/spec/pull/26 

**Example of Shipyard with approval strategy:** 

```yaml 
stages: 
  - name: "dev" 
    deployment_strategy: "direct" 
    test_strategy: "functional" 
  - name: "staging" 
    approval_strategy:     # approve based on evaluation result from dev 
      pass: "automatic" 
      warning: "manual" 
    deployment_strategy: "blue_green_service" 
    test_strategy: "performance" 
  - name: "production" 
    approval_strategy:     # hard stop for production – approval required 
      pass: "manual"  
      warning: "manual" 
    deployment_strategy: "blue_green_service" 
    remediation_strategy: "automated" 
``` 

**Definition of Done:**  
- [x] Sends: `sh.keptn.event.approval.finished` (+ triggered event) for automatic approval
- [x] Sends out: `sh.keptn.event.approval.triggered` for manual approval 
  
- [x] Test scenarios are available to verify the different combinations: 
  
|               | pass           | warning           | note     |  
|---------------|----------------|-------------------|----------| 
| combi 1:      | pass:automatic | warning:automatic |          | 
| combi 2:      | pass:automatic | warning:manual    |          | 
| combi 3:      | pass:manual    | warning:automatic |          | 
| combi 4:      | pass:manual    | warning:manual    |          |
