### ISSUE TITLE
Not every autogenerated virtual services needs to be public / exposed to the world  

### ISSUE THREAD

**Issue by avodaqstephan** [keptn/keptn#1713]
Hi, 

right now, keptn creats Istios virtual services automatically when you onboard a service. The things is, the hosts entry will also be filled by a FQDN which is not necessary for most of the services. Most of the time actually only one service needs to be exposed to the world. 

A short example from a Redis pod which is only used from the other pods within the same namespace.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: redis
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - redis.staging.<domain>.de 
  - redis
  http:
  - route:
    - destination:
        host: redis.staging.svc.cluster.local
```

My proposal would be, to add a flag while onboarding the service. 

`keptn onboard service redis --project=project --chart=keptn/redis/charts/ --image=redis --public=false`

Kind regards, 
Stephan
