### ISSUE TITLE
It should be possible to add a certificate to the keptn cli requests (mTLS)

### ISSUE THREAD

**Issue by avodaqstephan** [keptn/keptn#1714]
Hi, 

our Istio gateway is secured with mTLS - the client needs to authenticate with a valid certificate. 

Right now, it is not possible to add such a certificate to the keptn cli. 
So you either dig a hole in your gateway and let the keptn cli bypass without a certificate or you can't use the keptn cli anymore. 

Kind regards, 
Stephan

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the request. It would be helpful if you have an example of another cli/tool that implements this, and also if you can point us the configuration of istio in this matter.

**Comment by avodaqstephan** [comment]
My current configuration for the public-gateway looks like this:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    gateway: public-gateway
  name: public-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.domain.de'
    - '*.feature.domain.de'
    - '*.staging.domain.de'
    - '*.production.domain.de'
    - '*.keptn.domain.de'
    - api.keptn
    port:
      name: http-gw
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - '*.domain.de'
    - '*.feature.domain.de'
    - '*.staging.domain.de'
    - '*.production.domain.de'
    port:
      name: https-gw
      number: 443
      protocol: HTTPS
    tls:
      credentialName: certificate
      mode: MUTUAL
  - hosts:
    - '*.keptn.domain.de'
    - api.keptn
    port:
      name: https-keptn
      number: 443
      protocol: HTTPS
    tls:
      credentialName: certificate
      mode: SIMPLE
```

mode: MUTUAL will look for a secret with the name `certificate-cacert` and then mount it to verify client certificates. https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#configure-a-mutual-tls-ingress-gateway

I don't have an example from another CLI but I had a short talk with @agrimmer and he said it should be pretty easy to implement.
