### ISSUE TITLE
Cluster-internal traffic does not use VirtualService in B/G deployments

### ISSUE THREAD

**Issue by avodaqstephan** [keptn/keptn#1715]
Hi, 

I'm running a Django, Celery, Postgres, Redis stack but for this bug we just need to focus on Django and Postgres.
Django will mount a secret with the DATABASE_URL which it will use to connect to Postgres.

`DATABASE_URL: postgresql://x:y@postgres:5432/foo`

While onboarding postgres service, keptn automatically created a virtual service:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres
  namespace: prod
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - postgres.prod.domain.de
  - postgres
  http:
  - route:
    - destination:
        host: postgres-canary.prod.svc.cluster.local
    - destination:
        host: postgres-primary.prod.svc.cluster.local
      weight: 100
```

and the following services are getting created:

```
postgres           ClusterIP   10.100.174.169   <none>        5432/TCP
postgres-canary    ClusterIP   10.100.138.179   <none>        5432/TCP
postgres-primary   ClusterIP   10.100.164.191   <none>        5432/TCP
```

Now to the actual problem I encountered. You would except that the DATABASE_URL is still valid because the virtual service is changing the destination between the canary and primary service but this is **not** working from the pod perspective.

If the pod is now trying to connect to the postgres with the above connection string:
`DATABASE_URL: postgresql://x:y@postgres:5432/foo`
He'll end up at the service `postgres` instead of `postgres-primary` so the connection will fail because the pod is looking for the service name not the virtual service hosts.

You can overcome this, by changing the connection string to: 
`DATABASE_URL: postgresql://x:y@postgres-primary:5432/foo`
but this would mean, that the canary deployment is also using the primary database, which is not a good idea. 

I don't have a proposal to fix this issue, yet.

Kind regards,
Stephan

![image](https://user-images.githubusercontent.com/58725083/80577478-3feb2280-8a07-11ea-8195-84957a00c355.png)

**Comment by christian-kreuzberger-dtx** [comment]
Hi Stephan,

please let us know which version of Keptn, Istio and Kubernetes you are using.

Also, are you sure that this is an issue with the virtualservice? 
I'm suspecting that the issue is related to postgres not being up and running.

I know that this has been working fine on another test project we have, but I'll verify this again.

**Comment by avodaqstephan** [comment]
Hi Christian, 

you can see in the screenshot above, that the postgres is running but I can only connect via the hostname `postgres-primary` not `postgres`.

If I jump into the Django pod and run `curl -v postgres` it is resolving it to the service IP for the postgres service not the postgres-primary service. 

I'm running Istio v1.5

I would assume that from the pod perspective the first thing what it tries to resolve a host is the service level and not the virtual service. Traffic which comes through a gateway will look for a virtual service and then proceed to a service. 

You switched with keptn 0.6 to just one gateway instead of a gateway per namespace. This could be a reason as well but I can't really test this assumption.

**Comment by christian-kreuzberger-dtx** [comment]
Hi,

I just did some troubleshooting together with @agrimmer and I want to write down our finding shere.

For blue/green deployments, we use virtualservices with the following configuration:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
  namespace: ckkeptnorders-production
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - customer.ckkeptnorders-production.my-host.com
  - customer
  http:
  - route:
    - destination:
        host: customer-canary.ckkeptnorders-production.svc.cluster.local
    - destination:
        host: customer-primary.ckkeptnorders-production.svc.cluster.local
      weight: 100
```

At the same time, the following services exist:

```
customer           ClusterIP   10.0.84.246   <none>        80/TCP    140d
customer-canary    ClusterIP   10.0.88.169   <none>        80/TCP    61m
customer-primary   ClusterIP   10.0.81.204   <none>        80/TCP    61m
```

Now comes the funny part. When trying to access `http://customer/`, traffic is routed according to the virtualservices route destination weight (in the case above: `customer-primary`).
I verified this using ``curl http://customer/version``, which always provided me the correct version (either from the canary or primary deployment).
This is however also true when accessing "any IP" and overwriting the host header in curl, e.g.:
```console
curl http://1.2.3.4/version -H "Host: customer"
```
The reason behind this is the istio sidecar, which runs for namespaces with blue-green deployments. This side-car intercepts ANY HTTP traffic and routes traffic according to the Host header of the HTTP traffic.

In your case you are using Postgres, and Postgres is (obviously) not using HTTP traffic, but some other protocol. So there is no HTTP Host header to intercept for the sidecar, and the sidecar just let's traffic through to the services. Hence accessing `postgres` does not do what you want it to do (though you could and should be able to access `postgres.prod.domain.de` as a very ugly workaround for now).

Another thing you could try is to switch to `tcp` instead of `http` in the istio virtualservice, and I think at this point we also need to provide some port mappings.

**Comment by avodaqstephan** [comment]
Hi Christian, 

good catch! You are absolutely right. My postgres service and postgres itself is listening for TCP not for HTTP. So changing the virtual-service to:

```
  http:
  - route:
    - destination:
        host: postgres-canary.prod.svc.cluster.local
    - destination:
        host: postgres-primary.prod.svc.cluster.local
      weight: 100
  tcp:
  - route:
    - destination:
        host: postgres-canary.prod.svc.cluster.local
    - destination:
        host: postgres-primary.prod.svc.cluster.local
      weight: 100
```

worked. Of course the http entry wouldn't be necessary in this case. 
Now you guys need to think about, if you want to add the TCP entry to each auto-generated virtual service by default because obviously there are lot of things out there, which are not only using http. 
On one hand you would open up the virtual service by allowing another protocol but if the service does not accept it, it will be dropped. 

Looking forward to your solution :)
