### ISSUE TITLE
Remediation Service: Implement ResolveAction Behaviour

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#1734]
Please consider implementing  the "problem resolved" behaviour. For example, at present, the unleash service will correctly toggle my feature flag during a problem open event. However it should toggle off when the problem closes.

https://github.com/keptn/keptn/blob/d118d835287ada4d154abb28961a17c0545e6401/remediation-service/actions/featuretoggler.go#L63

**Considerations**
- The spec needs to be extended for `remediations.yaml`.
- For a feature flag, this would be simple and could be implemented as such
```
- name: "Failure rate increase"
  actions:
  - action: featuretoggle
    value: EnablePromotion:off:on
```
Where the first value is the "problem open" value and second is the "problem closed" value.
or more declaratively:
```
- name: "Failure rate increase"
  actions:
  - action: featuretoggle
    cause: problemopen
    value: EnablePromotion:off
  - action: featuretoggle
    cause: problemresolved
    value: EnablePromotion:on
```

- This doesn't cover the usecase of further toggling **while** a problem remains open. Consider the scaling usecase. We may want to scale further (up to a maximum) while a problem is still open. So something like this would be needed. `+10` here is relative meaning 10 more that whatever the initial value was, not a hardcoded value of `10`:
```
- name: "Response time degradation"
  actions:
  - action: scaling
    cause: problemopen
    value: +1
    maxValue: +10
```
