### ISSUE TITLE
Testing: Platform/integration test for manual approval use case

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1750]
Platform and integration tests for the manual approval use case need to be implemented.  

Supported combinations of the property *approval_strategy*:
  
|               | evaluation result: pass           | evaluation result: warning           |  expected behavior |  
|---------------|----------------|-------------------|----------| 
| combi 1:      | pass:automatic | warning:automatic | configuration-change for next stage is sent out | 
| combi 2:      | pass:automatic | warning:manual    | if the evaluation result is a **warning**, an approval.triggered event is sent out | 
| combi 3:      | pass:manual    | warning:automatic | if the evaluation result is a **pass**, an approval.triggered event is sent out | 
| combi 4:      | pass:manual    | warning:manual    | regardless of the evaluation result, an approval.triggered event is sent out |

**Test scenario:**

1. Create a project based on the following shipyard file:
```yaml
stages: 
  - name: "dev"
    deployment_strategy: "direct" 
    test_strategy: "functional" 
  - name: "combi1" 
    approval_strategy:     # approve based on evaluation result from dev 
      pass: "automatic" 
      warning: "automatic" 
    deployment_strategy: "blue_green_service" 
    test_strategy: "performance" 
  - name: "combi2" 
    approval_strategy:     # approve based on evaluation result from combi1
      pass: "manual" 
      warning: "automatic" 
    deployment_strategy: "blue_green_service" 
    test_strategy: "performance"
  - name: "combi3" 
    approval_strategy:     # approve based on evaluation result from combi2
      pass: "automatic" 
      warning: "manual" 
    deployment_strategy: "blue_green_service" 
    test_strategy: "performance" 
  - name: "combi4" 
    approval_strategy:     # approve based on evaluation result from combi3
      pass: "manual" 
      warning: "manual" 
    deployment_strategy: "blue_green_service" 
    test_strategy: "performance" 
  - name: "production" 
    deployment_strategy: "blue_green_service" 
    remediation_strategy: "automated" 
```

2. Send 3 evaluation-done events (result: pass, warning, failed) for each stage (dev, combi1, combi2, combi3) using the CLI.

3. Retrieve the open approvals using the CLI and verify the number of open approvals as shown below: 
`keptn get event approval.triggered --project=PROJECTNAME --stage=[combi1, combi2, combi3, combi4]`

*Expected number of open approvals:* 
|  Stage             | No. of open approvals   |
|---------------|----------------|
| combi 1:      | 0 open approvals | 
| combi 2:      | 1 open approvals |
| combi 3:      | 1 open approvals |
| combi 4:      | 2 open approvals |

4. For stage **combi1**, send an approval.finished event to Keptn specified by keptncontext:
`keptn send event approval-finished --project=PROJECTNAME --stage=combi1 --id=1234.5432` 
 --> verify CLI output

5. For stage **combi2**, send an approval.finished event to Keptn that has **a different image/tag** compared to the approval.triggered:
`keptn send event approval-finished --project=PROJECTNAME --stage=combi2 --id=1234.5432` 
--> verify CLI output

6. For stage **combi4**, send a valid approval.finished event to Keptn.
`keptn send event approval-finished --project=PROJECTNAME --stage=combi4 --id=1234.5432` 
--> verify the number of open approvals for this stage (using the command `keptn get events approval.triggered`)

**Definition of Done:**  
- [ ] Travis-CI is extended by the test script `test_manual_approval.sh` covering the above test scenarios of this use case 
- [ ] Test script is executed as part of a Keptn test on GKE: https://github.com/keptn/keptn/blob/master/.travis.yml#L111
