### ISSUE TITLE
Init container not starting for blue/green deployments

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#1823]
The init container is not starting when trying to do a service name resolution in the init script (only happens for me in a blue/green deployment scenario). My feeling is that it can not resolve the service name since the Istio sidecar is not available at this point in time. But the istio sidecar will only start once all other init containers have done their job. 

Please also find some discussion on this issue here: https://discuss.istio.io/t/k8s-istio-sidecar-injection-with-other-init-containers/845 

**Environment**

* Keptn Version (`keptn version`): 0.6.2
* Istio Version. 1.5 (installed with the experimental option `keptn install --istio-install-option=Reuse` (installed with 0.6.1 and then upgraded to 0.6.2 later)

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [x] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

I am pasting a fragment of my helm chart here:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      # initContainers:
      # - name: wait-frontend
      #   image: alpine:3.6
      #   command: ['sh', '-c', 'set -x;  apk add --no-cache curl && 
      #     until timeout -t 2 curl -f "http://${FRONTEND_ADDR}"; do 
      #       echo "waiting for http://${FRONTEND_ADDR}"; 
      #       sleep 2;
      #     done;']
      #   env:
      #   - name: FRONTEND_ADDR
      #     value: "frontend:80"
      containers:
      - name: server
        image: "{{ .Values.image }}"
        env:
        - name: DT_CUSTOM_PROP
          value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
        - name: FRONTEND_ADDR
          value: "frontend:80"
        - name: USERS
          value: "10"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
```

The part that is commented out is the problematic one - it won't ever finish since the service can not be accessed. Once the part is removed (like it did in this example) the server container is working fine (please note that it uses the exact same FRONTEND_ADDR) but at this point istio is already available.
