### ISSUE TITLE
Testing: Platform/integration test for self-healing use case

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#1846]
Platform and integration tests for the remediation use-case need to be implemented. Therefore, the unleash-service works as a custom remediation-provider. 

**Test scenario:** 

1. Create a project based on the following shipyard file: 

```yaml 
stages:  
  - name: "dev" 
    deployment_strategy: "direct"  
    test_strategy: "functional"  
  - name: "production"  
    deployment_strategy: "blue_green_service"  
    remediation_strategy: "automated"  
``` 

- **Test case 1:** Send `sh.keptn.event.problem.open` event for project/service using the CLI: 
    - Get the event `sh.keptn.evetn.remediation.finished` for the project/service 
    - Expected behavior/outcome: `result: Could not execute remediation action because service is not available` 
  
2. Onboard a service using the CLI. 

* **Test case 2:** Send `sh.keptn.event.problem.open` event for project/service using the CLI.  
    * Get the event `sh.keptn.evetn.remediation.finished` for the project/service 
    * Expected behavior/outcome: `result: Could not execute remediation action because no remediation file available` 

3. Add the following remediation file to the service (stage production) using the CLI: 

```yaml 
version: 0.2.0
kind: Remediation
metadata:
  name: service-remediation
spec:
  remediations:
    - problemType: Response time degradation
      actionsOnOpen:
      - action: toggle-feature
        name: toggle-feature
        description: Toggle feature ...
        value:
          EnablePromotion: off
      - action: run-snow-wf
        name: run-snow-wf
        description: Call SNOW workflow
        value:
          hook: https://myremediationlink
``` 
  
* **Test case 3:** Send `sh.keptn.event.problem.open` event for project/service using the CLI.  
    * Get the event `sh.keptn.evetn.remediation.finished` for the project/service 
    * Expected behavior: Not available yet. 
    * Wait 2 minutes 
    * Get the event `sh.keptn.evetn.remediation.finished` for the project/service 
    * Expected behavior/outcome: `result: Action toogle-feature triggered but not executed after waiting for 2 minutes.` 

4. Install `unleash-service` in Keptn deployment 

* **Test case 4:** Send `sh.keptn.event.problem.open` event for project/service using the CLI.  
    * Get the event `sh.keptn.evetn.remediation.finished` for the project/service 
    * Expected behavior/outcome: Not available yet. 
    * Wait 2 minutes 
    * Get the event `sh.keptn.evetn.remediation.finished` for the project/service 
    * Expected behavior/outcome: `result: Action run-snow-wf triggered but not executed after waiting for 2 minutes.` 
    * Get the event `sh.keptn.event.action.finished` for project/service/stage 
    * Expected behavior/outcome: `action=toggle-feature` `result=Action toggle-feature not executed, since Unleash server is not available.`  

**Definition of Done:** 

- [ ] Travis-CI is extended by the test script `test_self_healing.sh` covering the above test scenarios of this use case  
- [ ] Test script is executed as part of a Keptn test on GKE: https://github.com/keptn/keptn/blob/master/.travis.yml#L111
