### ISSUE TITLE
Helm-Service: Make Gateway in generated VirtualServices configurable via Env-Variable

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#1986]
When generating the VirtualServices, the `helm-services` assumes that there is a gateway called `public-gateway` in the `istio-system` namespace available. This gateway is used when automatically generating VirtualService, e.g.:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.sockshop-dev.demo.keptn.sh
  - carts
  http:
  - route:
    - destination:
        host: carts.sockshop-dev.svc.cluster.local
```

But by implementing [KEP 18](https://github.com/keptn/enhancement-proposals/pull/18/files), Keptn will not install Istio and no `public-gateway` anymore. Hence, we have to make the used gateway configurable.

**Tasks:**
- Introduce and use an environment for the used gateway.
- Check whether the gateway installed in an Istio demo-installation can be used as default for the gateway
- Describe in the Docs how to set the gateway

**Definition of Done:**
- The name and namespace of the used gateway can be configured via an environment variable.
