### ISSUE TITLE
Formulate spec for Shipyard 0.2.0 and implement a dedicated type in the go-utils

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2106]
For implementing KEP https://github.com/keptn/enhancement-proposals/pull/6, we introduce a new format of the shipyard. 

Example for a shipyard.yaml file:

```
---
apiVersion: spec.keptn.sh/0.1.5
kind: Shipyard
metadata:
  name: shipyard-sockshop
spec:
  stages:
  - name: "hardening"
    workflows: (or eventsequence)
    - name: artifact-delivery
      listen:   
      - dev.artifact-delivery.finished
      tasks:
      - deployment:
          strategy: blue_green
          traffic: 100
      - test:
          kind: functional
      - evaluation: 
      - test:
          kind: performance
      - evaluation:
      - release:   
```

Tasks:
- Formulate a JSON spec for Shipyard 0.2

Definition of Done:
- [ ] JSON spec is available in keptn/spec
- [ ] Go struct implements the new shipyard in keptn/go-utils
