### ISSUE TITLE
Bridge: Heatmap highlights evaluation results that are used for comparison

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2389]
With the list of event-id provided by #2388, it is possible to highlight the evaluation results that were used for comparison. 

_Example:_

Assuming the following comparison strategy is configured: 
```
comparison:
  compare_with: "several_results"
  number_of_comparison_results: 3
  include_result_with_score: "pass"
  aggregate_function: "avg"
```

Then, the lighthouse-service returns a list of three event-IDs (the last 3 passed evaluations). 

In the heatmap, this information should be displayed as shown below. Please use a highlighting mechanism for the comparison values that is most appropriate and does not hurt the look-and-feel.

![image](https://user-images.githubusercontent.com/729071/93889482-878d8600-fce9-11ea-8141-d8748c82404b.png)
