### ISSUE TITLE
Link stages based on task sequence events: sh.keptn.event.[stage.name].[sequence.name].finished

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#2534]
```yaml
---
version: 0.2.0
kind: Shipyard
metadata:
  name: shipyard
spec:
  stages:
  - name: dev
    sequences:
    - name: artifact-delivery
      tasks:
      ...
  - name: hardening
    sequences:
    - name: artifact-delivery
      triggers:
      - dev.artifact-delivery.finished
      tasks:
      ...
```

Given the above example, an `sh.keptn.event.dev.artifact-delivery.finished` event is the trigger for the `artifact-delivery` in staging as explained [here](https://github.com/keptn/enhancement-proposals/pull/6/files#diff-bea142ed84ef95941ac378353c504971b732df7e155325ae5b79ff9794b061ffR101)

**Integration Test**

Create a separate job in travis-ci that runs before quality-gate tests and before GKE tests for every branch.

Create a new Kubernetes cluster using K3s (re-use the existing code for tests please).

The shipyard used should be very simple, containing 2 stages (e.g., dev and hardening), with 1 sequence each, and let's say two simple tasks (definately not deploy/release, but something really simple, maybe we can introduce an "echo-service" that just sends a start and finished event for every event that it listens on).

The integration test needs to verify that the sequence is triggered, started, and is jumping over to the next stage.

**Definition of Done:**
- [x] Implementation of this feature
- [x] Integration test that tests the linking of stages (based on triggers)
