### ISSUE TITLE
No approval triggered/finished events fired when leaving out the approval_strategy in shipyard

### ISSUE THREAD

**Issue by warber** [keptn/keptn#2541]
Given a project using the following `shipyard.yaml`:

```
stages:
  - name: "dev"
    deployment_strategy: "direct"
  - name: "production"
    deployment_strategy: "direct"

```

Note that no `approval_strategy` for stage `production` is defined.
According to the documentation an automatic approval strategy should be used.

_[...]  Per default, an automatic approval strategy is used for evaluation result pass and warning. [...]
(see https://github.com/keptn/spec/blob/master/shipyard.md)_

However, when onboarding a service there is **no approval triggered/finished** event visible in the bridge.
When explicitly adding the `approval_strategy` to the `shipyard.yaml` these events are visible, though.

* Kubernetes version (`kubectl version`): 0.7.1

**Expected behavior**
Default approval strategy "automatic" is applied and approval triggered/finished events are fired/visible in the bridge

**Current behavior**
No approval triggered/finished events are triggered
