### ISSUE TITLE
Allow to send start-evaluation for onboarded blue-green services

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2555]
As of Keptn 0.7.2 I don't see a way to use the Keptn CLI or the API to send a start-evaluation event with the following parameters:

* project: sockshop
* service: carts
* stage: production

My use-case is as follows: I want to regularly check if the deployed version in production is still valid, e.g.:
```
keptn send event start-evaluation --project=sockshop --service=carts --stage=production --timeframe=5m 
```

However, this is in conflict with my sli.yaml for (in this case) dynatrace:
```
---
spec_version: '1.0'
indicators:
  throughput: "builtin:service.requestCount.total:merge(0):sum?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  error_rate: "builtin:service.errors.total.count:merge(0):avg?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  response_time_p50: "builtin:service.response.time:merge(0):percentile(50)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  response_time_p90: "builtin:service.response.time:merge(0):percentile(90)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
  response_time_p95: "builtin:service.response.time:merge(0):percentile(95)?scope=tag(keptn_project:$PROJECT),tag(keptn_stage:$STAGE),tag(keptn_service:$SERVICE),tag(keptn_deployment:$DEPLOYMENT)"
```

I simply can not pass `$DEPLOYMENT` with a start-evaluation event, which results in no metrics returned at all. I guess the same problem will occur with Prometheus too.

An easy fix would be to allow passing the deployment variable in the `start-evaluation` (as an optional flag).
