### ISSUE TITLE
Add dependabot config file to keep things up2date

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2648]
We should add a config file for dependabot, e.g.:

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "keptn/maintainers"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "keptn/maintainers"
```

See https://dependabot.com/docs/config-file/ for more details
