### ISSUE TITLE
distributor: lower k8s resource limits in helm charts

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2649]
Right now our distributors have quite a high limit, which they don't need:

```
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
```

We should reduce the upper cpu and memory limit to something more realistic (e.g., cpu to 200m).

**Resource requests/limits:**

```
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "32Mi"
              cpu: "250m"
```

**Task:**

* Please also update: https://github.com/keptn/keptn.github.io/pull/683
