### ISSUE TITLE
Create a GitHub Action to send CloudEvents to a Keptn installation

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2797]
The task is to create an official GitHub action for Keptn and register it in the action store.

Final goal should be to be able to use the GitHub action within a workflow, e.g.:

* For every push on master / for every tag / for every release
  * Run Unit Tests
  * Build Docker Image
  * Push Docker Image to Container Registry (e.g., DockerHub, GCR, GH Container Registry, ...)
  * **Trigger a sequence (e.g., *delivery.triggered*) for the defined project/service/stage via the Keptn API**
  * At some point: Integrate quality-gate (or generally speaking: wait for a certain CloudEvent and report the success/status flag on the GitHub Action)
    * Optimum: Provide some information contained in the evaluation.finished event within a Pull Request comment

For now it's important that we can send a cloud-event to an existing Keptn installation. 
* Parameters:
  * Secrets (can/should be configured as a GitHub secret)
    * Keptn API Token
    * Keptn API URL
  * Configuration
    * Project, Service (and optional: Stage) 
    * Payload of Cloud-Event (as JSON)

# Example Step Configuration

```yaml
      - name: Send new-artifact to Keptn
        id: keptn_send_new_artifact
        uses: keptn/gh-action-send-event@v1
        env:
          KEPTN_API_URL: ${{ secrets.KEPTN_API_URL }}
          KEPTN_API_TOKEN: ${{ secrets.KEPTN_API_TOKEN }}
        with:
          event_type: "sh.keptn.event.deployment.triggered"
          project: "sockshop"
          service: "carts"
          stage: "dev"
          configurationChange: |
            {
               "values": { "image": "my-image-name", "tag": "${{ steps.push_docker_image.outputs.TAG }}" }
            }
          deployment: |
            {
                "deploymentstrategy": ""
            }

```
whereas "with" is a key-value map, where the value can either be a string or JSON.

# Definition of Done

- [x] Create a new GH action from scratch in the repository keptn/gh-action-send-event
- [x] Create the aforementioned GitHub action
- [x] Create a solid README file with examples
- [ ] Register the GH action in GitHub Marketplace
