### ISSUE TITLE
Helm Service is not correctly replacing keptn variables in generated helm charts

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#2881]
When onboarding a service the Helm service is generating additional helm charts for e.g: canary/primary deployments.

I have observed a weird behavior that leads to incorrectly generated deployment.yamls for the primary deployment.
Here is a snippet of my initial deployment yaml including several usages of the variable .Values.keptn.deployment:

```
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simplenode
  template:
    metadata: 
      labels:
        app: simplenode
        app.kubernetes.io/name: {{ .Values.keptn.service }}
        app.kubernetes.io/part-of: "{{ .Values.keptn.project }}"
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}
    spec:
      containers:
      - name: simplenode
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        env:
        - name: DT_CUSTOM_PROP
          value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
        - name: KEPTN_PROJECT
          value: "{{ .Values.keptn.project }}"
        - name: KEPTN_STAGE
          value: "{{ .Values.keptn.stage }}"
        - name: KEPTN_SERVICE
          value: "{{ .Values.keptn.service }}"
        - name: KEPTN_DEPLOYMENT
          value: "{{ .Values.keptn.deployment }}"
``` 

When using this during `keptn onboard service` the resulting file simplenode-generated/templates/simplenode-primary-deployment.yaml looks like this where the deployment value is correctly replaced in DT_CUSTOM_PROP (shows as primary) but incorrectly in KEPTN_DEPLOYMENT (it is shown as canary)

```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplenode-primary
  template:
    metadata:
      labels:
        app: simplenode-primary
        app.kubernetes.io/name: simplenode-primary
        app.kubernetes.io/part-of: student014
        app.kubernetes.io/version: 3.0.0
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: keptn_project=student014 keptn_service=simplenode keptn_stage=prod
            keptn_deployment=primary
        - name: KEPTN_PROJECT
          value: student014
        - name: KEPTN_STAGE
          value: prod
        - name: KEPTN_SERVICE
          value: simplenode
        - name: KEPTN_DEPLOYMENT
          value: canary
```

I am not sure how it is possible that the same placeholder is replaced with two different values. This currently leads to inconsistent information as this data is passed to the monitoring tool

**Environment**
* Keptn Version (`keptn version`): 0.7.3
* Kubernetes version (`kubectl version`): 01.17

**Affected Component**
* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [x] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter
