### ISSUE TITLE
Approval not possible in the Keptn Bridge in rare cases when having the manual deployment strategy

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#2901]
When deploying a service and having the manual approval strategy for a _production_, the _approval triggered_ event is missing the (:ballot_box_with_check:  / :negative_squared_cross_mark: ) confirmation in rare cases.

In the previous stage, the evaluation is successful: There is an _configuration changed_ event with the _promote_ action for _staging_, however, it is listed after the _approval triggered_ event for _production_ in the event feed.

![current](https://user-images.githubusercontent.com/6452952/104427155-36005400-5583-11eb-9187-424a4a67eb10.png)

This seems to be an issue in the Bridge's UI as I can query and trigger the open approvals using the CLI.
After doing so, the service gets deployed and I get the expected behavior in the event feed (except the confusing ordering for the staging/production events).

I've attached the event-json of the _approval triggered_ and _configuration changed_ events.

**Environment**

* Client OS (e.g., Linux, OSX, Windows): Ubuntu 20.04 focal
* Keptn Version (`keptn version`): 0.7.3
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.16.15-gke.4300
* Browser: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [X] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**To Reproduce**

This bug occurs randomly in rare cases. I have not found a consistent way to reproduce this issue.

It noticed that if an event comes after the _approval triggered_ event in the feed, the confirmation is missing.

**Expected behavior**

![expected](https://user-images.githubusercontent.com/6452952/104424223-60501280-557f-11eb-960a-3ea77f224490.png)

**Current behavior**

![current](https://user-images.githubusercontent.com/6452952/104427155-36005400-5583-11eb-9187-424a4a67eb10.png)

**Additional context**

Shipyard.yaml:

```yaml
stages:
  - name: "dev"
    deployment_strategy: "direct"
    test_strategy: "functional"
  - name: "staging"
    approval_strategy:
      pass: "automatic"
      warning: "automatic"
    deployment_strategy: "direct"
    test_strategy: "performance"
  - name: "production"
    approval_strategy:
      pass: "manual"
      warning: "manual"
    deployment_strategy: "direct"
    remediation_strategy: "automated"
```

Approval Triggered Event (Production):
```json
{
  "contenttype": "application/json",
  "data": {
    "deploymentstrategy": "direct",
    "image": "andreastscheinig/microservice-template",
    "labels": null,
    "project": "webshop-10",
    "result": "pass",
    "service": "checkout",
    "stage": "production",
    "tag": "0.4.0",
    "teststrategy": "performance"
  },
  "id": "9cac9069-2b0d-475a-ada2-44606101e370",
  "source": "gatekeeper-service",
  "specversion": "0.2",
  "time": "2021-01-11T15:18:09.191Z",
  "type": "sh.keptn.event.approval.triggered",
  "shkeptncontext": "84809005-98b4-4a66-9cd3-cc77d4b2280a"
}
```

Configuration changed event (Staging)
```json
{
  "contenttype": "application/json",
  "data": {
    "canary": {
      "action": "promote"
    },
    "labels": null,
    "project": "webshop-10",
    "service": "checkout",
    "stage": "staging"
  },
  "id": "b8814ffd-734a-4fa6-b066-b41ad566e67b",
  "source": "gatekeeper-service",
  "specversion": "0.2",
  "time": "2021-01-11T15:18:09.191Z",
  "type": "sh.keptn.event.configuration.change",
  "shkeptncontext": "84809005-98b4-4a66-9cd3-cc77d4b2280a"
}
```
