### ISSUE TITLE
Create an integration test to test the "multiple parallel stages" with cont.delivery claim of our control-plane / Shipyard.yaml

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#2970]
For Keptn 0.8.0 and the Shipyard we claim that we can handle multiple parallel stages.

Let's create an example (maybe in keptn/examples onboarding-carts?) and an integration test for this.

**Acceptance Criteria**
Shipyard must contain the steps test, deployment and evaluation for at least 2 normal stages and in addition 2 parallel stages, e.g.:
* dev
* hardening
* production-a, production-b

The test itself should be a full-blown continuous-delivery integration test on GKE, similar to the existing onboard service test
https://github.com/keptn/keptn/blob/83c5f7aa08b139c5dac0004c523164085e39db0e/.github/workflows/integration_tests.yml#L430-L442

Don't forget to update the [test-report](https://github.com/keptn/keptn/blob/76418b37d3ed876a8783cb0ea5e7d303d063b8f8/.github/workflows/integration_tests.yml#L523-L530).

# Definition of Done
- [ ] Integration Test "multiple parallel stages" is implemented and reported in test-report

---

**More Info**

To run stages in parallel, please define `triggers` in shipyard.yaml as follows:

```
---
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: shipyard-abc
spec:
  stages:
  - name: "dev"
  - name: "hardening"
  - name: "pre-prod"
     sequences:
     - name: artifact-delivery
       tasks:
       - name: deployment
           strategy: blue_green
       - name: approval
       - name: release
      
  - name: "prod-customer-A"
     sequences:
     - name: artifact-delivery
       trigger:
       - pre-prod.artifact-delivery.finished 
       tasks:
       - name: deployment
           strategy: blue_green
       - name: approval
       - name: release

  - name: "prod-customer-B"
     sequences:
     - name: artifact-delivery      
       trigger:
       - pre-prod.artifact-delivery.finished
       tasks:
       - name: deployment
           strategy: blue_green
       - name: approval
       - name: release

```
