### ISSUE TITLE
Keptn Bridge: Manual approval does not trigger next task in sequence

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3013]
**Environment**
* Client OS (e.g., Linux, OSX, Windows): Ubuntu 20.04
* Keptn Version (`keptn version`): 0.8.0-alpha
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): v1.16.15-gke.6000

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [X] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

The task sequence is not continued when manually approving the approval step from the Bridge UI.
It works, however, when sending the `approval.finished` event from the CLI.

Reason:

The `approval.finished` event is received by the shipyard-controller. It then tries to find a related `approval.started` event - which does not exist -> task sequence stops.

When using the CLI, the shipyard controller receives a `approval.started` and `approval.finished` event. The next task is executed afterwards.

**To Reproduce**

Create a new project with provided shipyard.yaml.
Onboard and deploy any service.
Click on approve.

**Expected behavior**
The next task in the sequence (e.g. `deployment`) is triggered.

**Current behavior**
The next task is not triggered.

**Screenshots**

![image (1)](https://user-images.githubusercontent.com/6452952/105984849-ffeec400-609a-11eb-8a96-13c7bd6c903e.png)

**Additional context**
Shipyard:
```yaml
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: demo
spec:
  stages:
  - name: foobar
    sequences:
    - name: artifact-delivery
      tasks:
      - name: approval
        properties:
          pass: manual
          warning: manual
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: release
```
