### ISSUE TITLE
Introduce golangci-lint into build chain

### ISSUE THREAD

**Issue by warber** [keptn/keptn#3019]
## Action Item
As we want to switch from `golint` to `golangci-lint` we need to adapt our build chain.
Besides the linters which are enabled by default, the following linters shall be enabled as well:

`bodyclose, exportloopref, funlen, gocyclo, gosec, nestif, unparam`

## Definition of Done
- [ ] golangci-lint is used on each PR to analyze the code changes contained in the PR
- [ ] current golang-lint execution is removed

## Resources
[golangci-lint-action](https://github.com/golangci/golangci-lint-action)
[reviewdog/golangci](https://github.com/reviewdog/action-golangci-lint)

**Comment by rahul799** [comment]
Hey @warber 
I will like to take this issue.
Can you please assign it to me?

**Comment by warber** [comment]
Hi @rahul799, sure, go for it. If you have questions, I am happy to help.

**Comment by warber** [comment]
hi, @rahul799 can you give an update on this issue? Do you still have time to work on it?

**Comment by christian-kreuzberger-dtx** [comment]
I tried the existing action `golangci/golangci-lint-action` (see , https://github.com/golangci/golangci-lint-action/ ), e.g.,
```
      # we are a monorepo, let's lint every Go sub-project
      - name: lint/api
        uses: golangci/golangci-lint-action@v2
        with:
          # working-directory where a go.mod file can be found
          working-directory: api
          # Optional: golangci-lint command line arguments.
          args: ${{ env.GOLANGCI_LINT_ARGS }}
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true

```
Unfortunately it is not possible to combine `working-directory` with `only-new-issues`, and hence the action will report all existing errors, rather than just new ones.

I'll continue with looking at golangci-lint in combination with reviewdog, which should work in this scenario.
