### ISSUE TITLE
Shipyard-controller stops sequence when a task returns `result=fail`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3027]
Currently, the shipyard-controller stops the orchestration of a sequence when a task returns status=errored. 

Given the following shipyard, the shipyard-controller also stops orchestrating the task sequence when `result=fail` for any task. 

```
- name: "staging"
  sequences:
  - name: "artifact-delivery"
    tasks:
    - name: "deployment"
      properties:
        deploymentstrategy: "blue_green_service"
    - name: "test"
      properties:
        teststrategy: "performance"
    - name: "evaluation"
    - name: "release"
```

**Task:**
* Change the behavior of the shipyard-controller to stop on `result=fail`
* Consider: #3008 (which can be closed afterwards)

**Definition of done:**
* [ ] A failed test will stop, e.g., the `artifact-delivery` sequence.
