### ISSUE TITLE
Allow filtering sequence triggers based on match properties

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3028]
It should be possible to add a filter to the trigger of a sequence. The filter works on the payload of a stage event. Given the below example, the shipyard-controller would start the `rollback` sequence, when the `staging.artifact-delivery.finished` event has the property `result` set to `failed`.

```
- name: "staging"
  sequences:
  - name: "artifact-delivery"
    tasks:
    - name: "deployment"
      properties:
        deploymentstrategy: "blue_green_service"
    - name: "test"
      properties:
        teststrategy: "performance"
    - name: "evaluation"
    - name: "release"

- name: "rollback"
  on:
  - staging.artifact-delivery.finished:
    selector:
      match:
        result: failed
  tasks:
  - name: rollback
```

**Task:**
* The shipyard-controller considers the filters for kicking-off a sequence
* Write an integration test

**Definition of Done:**
* [ ] The shipyard shows the rollback sequence and the demo use-case for delivery rolls back the 0.11.2 version of carts since it failed the evaluation (failed evaluation concluded in a `staging.artifact-delivery.finished` with `result=failed`)
