### ISSUE TITLE
Incorporate shellcheck into CI pipeline

### ISSUE THREAD

**Issue by unacceptable** [keptn/keptn#3170]
Overview
---
[shellcheck](https://github.com/koalaman/shellcheck) is a command-line tool to ensure the quality of shell scripts.

Why this is important
---
It is extremely easy to make mistakes in bash, and extremely hard to write unit tests for shell scripts.  shellcheck is a stop-gap to help ensure that common issues are avoided in shell scripts.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the suggestion.

If we include it, I'd like to do it as a GH action, e.g., https://github.com/marketplace/actions/shellcheck

Also, are you willing to take this task?

**Comment by unacceptable** [comment]
@christian-kreuzberger-dtx,

Yeah, I can incorporate it as a GitHub action, but I am not a fan of that one in the marketplace.  I would probably do something like this: 

```
name: shellcheck

on: [push]

jobs:
  lint_shellscripts:
    runs-on: [ubuntu-latest]
    container:
      image: koalaman/shellcheck-alpine:latest
      options: --entrypoint /bin/sh
    steps:
      - uses: actions/checkout@v1
      - run: |
            #!/usr/bin/env sh
            set -ex
            shellcheck --version
            shellcheck *.sh
```

I haven't done too much with GitHub actions since I mostly use GitLab, but I am sure I can figure it out (and maybe simplify the above example).

Do you all use `latest` for your GitHub action container tags or do you all want to pin versions?  I have no strong feelings about either way.

Respectfully,
Robert J.
