### ISSUE TITLE
Propagate configurationChange through all tasks of a sequence

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3199]
Currently, the configurationChange property is added to the `.triggered` event of the first task. If this is a deployment tasks, the payload looks as follows:

```
{
  "data": {
    "configurationChange": {
      "values": {
        "image": "docker.io/keptnexamples/carts:0.11.1"
      }
    },
    "deployment": {
      "deploymentstrategy": "direct"
    },
    "labels": null,
    "message": "",
    "project": "sockshop",
    "result": "",
    "service": "carts",
    "stage": "dev",
    "status": ""
  },
  "id": "dfb74c08-d865-4703-8c66-956acfddc4ea",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2021-02-08T09:12:50.663Z",
  "type": "sh.keptn.event.deployment.triggered",
  "shkeptncontext": "50ee9fdc-9239-411b-afbc-15b13f67487e"
}
```

**Problem:**
However, the second task in the sequence won`t receive the `configurationChange`. --> If a user adds a task before the deployment task, the deployment task (executed by the helm-service) won't receive the configurationChange. See example below:

```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "custom_event"
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
```

**Task:**
- Adapt the shipyard-controller to propagate the `configurationChange` through all tasks. 

**Defintion of Done:**
- [ ]  Given the example above, the "release" tasks could also consume data from the initial `configurationChange`
