### ISSUE TITLE
shipyard-controller api returns shipyard version 0.1.7, although 0.2.0 is used

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#3335]
Keptn-Version: 0.8.0-dev.202102191239 (last nightly)

For no apparent reason, my sockshop project is listed as "0.1.7" spec project in Keptn Bridge:
![image](https://user-images.githubusercontent.com/56065213/108723119-34339400-7524-11eb-9953-7ef9940c3a14.png)

This information is returned by the API call

GET /api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50

Shipyard.yaml looks as follows:
```yaml
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
...
```

This would be the relevant code:
https://github.com/keptn/keptn/blob/1a0e88b4fb48e9ee076d9acce0b01cecd7aea774/shipyard-controller/db/projects_materialized_view.go#L84-L101
