### ISSUE TITLE
Smart Helm Chart values merger

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3341]
This issue is related to the discussion here: https://github.com/keptn/keptn/discussions/3038 

**Current state**: Currently, the helm-service can replace the image and tag of a Helm Chart as shown below. In other words, a values.yaml must have the `image` and `tag` property on the top level: 
```
image: docker.io/keptn/api
tag: 0.8.1
```

**Use Case:** As a user, I have a Helm Chart that has a values.yaml file similar to: 

```
apiService:
  image:
    repository: docker.io/keptn/api
    tag: 0.8.1

shipyardController:
  image:
    repository: docker.io/keptn/shipyardController
    tag: 0.8.1
```
When the CI builds a new version of, e.g., shipyardController 0.8.2-dev20210222, I would like to trigger Keptn to update the tag of the shipyardController (from 0.8.1 to 0.8.2-dev20210222) and to trigger the deployment of the Helm Chart. 

**Usage:**
```
keptn trigger delivery --project=xyz --service=zyx --values="shipyardController.image.tag=0.8.2-dev20210222"
```

**Cloud Event:**
```
"configurationChange": {
  "values": {
    "shipyard": {
      "image": {
        "tag": "0.8.2-dev20210222"
      }
    }
  }

```

**Task:**
- Extend the helm-service to set values based on the specified key, e.g.: shipyard.image.tag (a prototype is available here: https://github.com/keptn/keptn/pull/3318 
- Extend the CLI to support the above-shown use-case

**Definition of Done:**
- [ ] I can trigger a delivery of a custom Helm Chart in which a portion of the values changed
