### ISSUE TITLE
new-artefact event is sent a number of times instead of once due to timeout

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#335]
**Describe the bug**
The internal docker registry sends the notification about a new artifact that has been pushed several times instead of once. I found the following line in the log of the docker registry

```
time="2019-05-08T06:06:19.847743693Z" level=error msg="retryingsink: error writing events: httpSink{http://event-broker.keptn.svc.cluster.local/docker}: error posting: Post http://event-broker.keptn.svc.cluster.local/docker: net/http: request canceled (Client.Timeout exceeded while awaiting headers), retrying"
```

While retrying it follows the configuration from the configMap `docker-registry`:

```
...
    notifications:
      endpoints:
        - name: listener
          url: http://event-broker.keptn.svc.cluster.local/docker
          Headers:
            Content-Type: application/json
          timeout: 5000ms
          threshold: 5
          backoff: 1s
```

The events arrive with 5 seconds time different, which corresponds to the configured timeout. I've also tried changing the timeout to 8 seconds, which caused the events to arrive with 8 seconds time difference.

It seems like the first event is not acknowledged by the event-broker, although both events arrive there because the CD workflow starts twice.

**Expected behavior**
The event must only be sent once.
