### ISSUE TITLE
Declining approval still executes the task sequence

### ISSUE THREAD

**Issue by GustavAT** [keptn/keptn#3366]
**Environment**

* Client OS (e.g., Linux, OSX, Windows): `Ubunut 20.04`
* Keptn Version (`keptn version`): `0.8.0-dev.202102191239`
* Kubernetes Cloud Provider (e.g., GKE, AKS): `GKE`
* Kubernetes version (`kubectl version`): `v1.16.15-gke.7800`

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [X] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
After declining an open approval via the Bridge UI, the remaining tasks in that sequence are still executed.

For example when onboarding a service with the following task sequence

```yaml
- name: approval
  properties:
    pass: manual
    warning: manual
- name: deployment
  properties:
    deploymentstrategy: direct
- name: release
```
and declining the approval, the tasks `deployment` and `release` are still executed successfully and the service is deployed.

![image](https://user-images.githubusercontent.com/6452952/108982439-171ad480-768e-11eb-861b-86bcc3cc2d3c.png)

See approval event payload json: [approval-event-payload.json.txt](https://github.com/keptn/keptn/files/6035111/approval-event-payload.json.txt)

**To Reproduce**

Use the following shipyard

```yaml
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: approval
spec:
  stages:
  - name: production
    sequences:
    - name: artifact-delivery
      tasks:
      - name: approval
        properties:
          pass: manual
          warning: manual
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: release
```

onboard a service and trigger a deployment.

Note: I also tried out multiple stages (staging and prod) with a test and evaluation task. Still got the same result.

**Expected behavior**

A declined approval serves as a full-stop in a sequence. No further tasks are executed in that sequence.

**Current behavior**

Remaining tasks in a sequence are executed although the approval was declined.
