### ISSUE TITLE
Show `keptn trigger evaluation` when no delivery sequence is configured

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3445]
**Current behavior**: As a user, I have a project with stages and no sequences in these stages. Hence, it is not possible to `trigger a delivery sequence`, but it would be possible to `trigger an evaluation` which is a built-in capability of Keptn. 

Example of the shipyard of my project:
```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "hardening"
    - name: "production"
```
*Bridge shows:*

![image](https://user-images.githubusercontent.com/729071/110085875-efb0bf80-7d91-11eb-84ca-dfbdc6bfcdc0.png)

**Task:**
- ❓ Which API endpoint do we need to retrieve the information on whether a sequence is defined or not?

**Definition of Done:**
- [ ] When I do not have a sequence in the first stage of the shipyard, the Bridge shows: `Use keptn trigger evaluation to trigger a quality gate evaluation` (instead of `Service not deployed yet. Use ... `)
