### ISSUE TITLE
deploymentURI shows up twice in shipyard controller test.triggered event

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#3449]
Hi. I just started with 0.8 and I am using keptn for performance test automation. Whats interesting is that when I am sending in ONE deploymentURIPublic it seems that the shipyard controller duplicates that URL into two

Here is my shipyard
```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-performance-as-selfservice"
spec:
  stages:
  - name: "performance"
    sequences:
      - name: testing
        tasks:
        - name: test
          properties:
            teststrategy: performance
        - name: evaluation
```

Here is the event I send in

```
  {
    "data": {
      "deployment": {
        "deploymentURIsPublic": [
          "http://simplenode.keptn07project-dev.keptn07-agrabner.demo.keptn.sh/"
        ]
      },
      "labels": {
        "buildId": "1.0",
        "user": "noname"
      },
      "project": "demo-performance",
      "service": "appundertest",
      "stage": "performance",
      "test": {
        "teststrategy": "performance"
      }
    },
    "id": "f132f443-1011-4835-a7ff-8e2208764589",
    "shkeptncontext": "0d5bd574-f06f-4a07-90a7-e0647c713acf",
    "source": "my-automation-script",
    "specversion": "1.0",
    "time": "2021-03-05T10:45:29.638Z",
    "type": "sh.keptn.event.performance.testing.triggered"
  }
```

and here is the shipyard-controller event where the URL is duplicated
```
  {
    "data": {
      "deployment": {
        "deploymentURIsPublic": [
          "http://simplenode.keptn07project-dev.keptn07-agrabner.demo.keptn.sh/",
          "http://simplenode.keptn07project-dev.keptn07-agrabner.demo.keptn.sh/"
        ]
      },
      "labels": {
        "buildId": "1.0",
        "user": "noname"
      },
      "message": "",
      "project": "demo-performance",
      "result": "",
      "service": "appundertest",
      "stage": "performance",
      "status": "",
      "test": {
        "teststrategy": "performance"
      }
    },
    "id": "fc343aa3-a9bc-44ce-a744-b825f501cb0c",
    "shkeptncontext": "0d5bd574-f06f-4a07-90a7-e0647c713acf",
    "shkeptnspecversion": "0.2.0",
    "source": "shipyard-controller",
    "specversion": "1.0",
    "time": "2021-03-05T10:45:29.707Z",
    "type": "sh.keptn.event.test.triggered"
  },
```
