### ISSUE TITLE
Allow comma-separated list on event filters for distributors

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3577]
**Use-Case:**

![image](https://user-images.githubusercontent.com/729071/111774878-58c72580-88b0-11eb-9592-cc41d8169167.png)

For implementing the above use-case, I need two helm-services: (1) works on control-plane and deploys on `development`, `hardening`, `production`; (2) works on execution-plane and deploys on `production-remote`

**Limitation**: Filters on the distributor just allow a single value. 

**Improvement**: As a user, I would like to configure my distributor to listen to events, e.g., for multiple stages. In the example below, I would like to get events for the `dev` and `hardening` stage: 

```
distributor:
  projectFilter: ""                 
  stageFilter: "development,hardening,production"             
  serviceFilter: ""                     
```

**Implementation details:**
- This should work on project/stage/service-level
- The corresponding function is here: https://github.com/keptn/keptn/blob/master/distributor/cmd/main.go#L681
- Instead of doing a equals comparison, a contains could address this limitation

**Definition of Done:**
- [ ] When setting a filter, a distributor can process events for multiple stags/projects/services
- [ ] Update of Readme.md and keptn/docs (https://keptn.sh/docs/0.8.x/operate/multi_cluster/#how-to-deploy-an-execution-plane-services)
