### ISSUE TITLE
Split K8s role: `keptn-configure-bridge` by secret and pod management

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#3767]
The K8s role `keptn-configure-bridge` (see: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/rbac.yaml#L166) defines the rules as follows: 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-configure-bridge
  labels:
    app.kubernetes.io/name: keptn-configure-bridge
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
    helm.sh/chart: {{ include "control-plane.chart" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
    resourceNames:
      - "bridge-credentials"
```

**Task:**
Split role `keptn-configure-bridge` so it is clear who is allowed to handle secrets: 
* `keptn-manage-bridge-credentials` with:
```
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
    resourceNames:
      - "bridge-credentials"
```
* `keptn-manage-bridge-pod` with: 
```
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - deletecollection
```
