### ISSUE TITLE
Helm chart should support ability to set HTTP proxy for configuration-service

### ISSUE THREAD

**Issue by donovanmuller** [keptn/keptn#3806]
**Is your feature request related to a problem? Please describe.**
In a corporate network environment where public internet access is limited and all external traffic must go through a HTTP proxy, some services, like the `configuration-service`, are not able to communicate to GitHub (where the Git upstream repo is hosted) or other external resources.

**Describe the solution you'd like**
It's possible to enable access via a HTTP proxy for services, like the `configuration-service`, by adding additional environment variables to the [`Deployment`](https://github.com/keptn/keptn/blob/1e7b9b8276721c58a50ecc440ccd1decb9b352b8/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L552) as below:

```yaml
apiVersion: apps/v1
kind: Deployment
...
metadata:
  name: configuration-service
spec:
...
    spec:
      containers:
      - env:
        # ---
        - name: HTTPS_PROXY
          value: http://proxy:3128
        - name: NO_PROXY
          value: 172.20.0.1,localhost,127.0.0.1
        # ---
        - name: PREFIX_PATH
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DATASTORE_URI
          value: mongodb-datastore:8080
        image: docker.io/keptn/configuration-service:0.8.1
...
```

Therefore, it would be beneficial to enable the ability to add additional environment variables to the various services `Deployment` manifests via [chart values](https://github.com/keptn/keptn/blob/1e7b9b8276721c58a50ecc440ccd1decb9b352b8/installer/manifests/keptn/charts/control-plane/values.yaml#L66), to satisfy this use case and potentially others in future.

**Comment by christian-kreuzberger-dtx** [comment]
Re-opening as discussed in PR #3807.

Let's discuss the best way of introducing configuration for proxy settings for Keptn control-plane.

I propose to use the same approach that [Harbor](https://github.com/goharbor/harbor-helm/blob/2a1742269ea4e1e7e68587c3c753896264fa582f/values.yaml#L349-L354) is using, and introduce new variables in our values.yaml as follows:

```yaml
# Proxy settings for Keptn to communicate with code repositories (e.g., github.com) and https://get.keptn.sh for regular update checks 
proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
```
