### ISSUE TITLE
Writing an integration test in Go failed

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4019]
I just tried to write an Integration Test in Go. This is what I did:

Added to integration_test.yaml
```
      - name: Test Create Service
        id: test_create_service
        timeout-minutes: 5
        continue-on-error: true
        env:
          KEPTN_ENDPOINT: ${{ steps.authenticate_keptn_cli.outputs.KEPTN_ENDPOINT }}
        run: |
          cd test/go-tests
          go test -run CreateServiceWithTooLongName
          go test -run CreateServiceWithLongName
```

Added [`test/go-tests/createservice_test.go`](https://github.com/keptn/keptn/blob/89077f6341efe566edc725196725aaa335e6c7c4/test/go-tests/createservice_test.go) (started as a copy of [`test/go-tests/sequencestate_test.go`](https://github.com/keptn/keptn/blob/89077f6341efe566edc725196725aaa335e6c7c4/test/go-tests/sequencestate_test.go)).

Executing in the CI failed with the following error message:

![image](https://user-images.githubusercontent.com/56065213/117636554-38656a00-b181-11eb-9679-d32be66a34d0.png)

In addition, I'm not even sure how the existing sequence state test worked at all, as we never installed Go 1.16 in our integration test (I think Go 1.15 is included by Default in GH actions though).
