### ISSUE TITLE
Closed Loop Remediation fails due to missing start and end time in evaluation.triggered event

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4075]
During https://github.com/keptn/examples/issues/165 we've encountered a problem with the execution of a remediation, more spcifically the evaluation task ,which has no Evaluation field set.

The Lighthouse service fails with the error: `evaluation.triggered event does not contain evaluation timeframe`

![image](https://user-images.githubusercontent.com/72415058/118260771-ff940080-b4b2-11eb-960d-0144c96e4fd0.png)

Remediation sequence in `shipyard.yaml`:

```
        - name: "remediation"
          triggeredOn:
            - event: "production.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "2m"
```

**Comment by christian-kreuzberger-dtx** [comment]
IMO we should not use `triggeredAfter` as a property, but rather introduce a sleep task, whereas the shipyard looks as follows:

```
        - name: "remediation"
          triggeredOn:
            - event: "production.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "sleep"
              properties:
                 sleepTimeMinutes: "2m"
            - name: "evaluation"
```

This `sleep` task should be a builtin task of shipyard-controller, and it should send out a `sleep.finished` event that looks as follows:

```
{
  "data": {
    "sleep": {
      "end": "2021-05-14T07:59:23.000Z",
      "start": "2021-05-14T07:54:23.000Z"
    },
    "message": "",
    "project": "sockshop",
    "result": "",
    "service": "carts",
    "stage": "production",
    "status": "",
  },
  "id": "208609f2-3c6a-417a-b230-b4dcc066b1bc",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2021-05-14T07:59:23.734Z",
  "type": "sh.keptn.event.sleep.finished"
  "shkeptncontext": "01f8980c-53d1-4826-8a95-90ab60fe39f0",
  "shkeptnspecversion": "0.2.1"
}
```

If that's the case, we can easily adapt lighthouse-service here:
https://github.com/keptn/keptn/blob/94dfd0a13961ae89d276a892612a2647097363bb/lighthouse-service/event_handler/start_evaluation_handler.go#L145-L152

# Summary

- [ ] Add a `sleep` cloudevent to our spec
- [ ] Add built-in `sleep` function to shipyard-controller, send out a sleep.finished cloudevent with start/end time
- [ ] Adapt lighthouse-service to read those timestamps
- [ ] Add `sleep` visualization in Keptn Bridge (e.g., with an appropriate message)

**Comment by christian-kreuzberger-dtx** [comment]
Alternative idea:

shipyard-controller needs to stay as it is, and use the shipyard as follows:
```
            - name: "evaluation"
              triggeredAfter: "2m"
```

shipyard-controller however adds two timestamps to the task that's currently being executed, e.g.:

```
{
  "data": {
    "evaluation": {
      "taskStartedAfterWait": "2021-05-14T07:59:23.000Z",
      "taskStartedBeforeWait": "2021-05-14T07:54:23.000Z"
    },
    "message": "",
    "project": "sockshop",
    "result": "",
    "service": "carts",
    "stage": "production",
    "status": "",
  },
  "id": "208609f2-3c6a-417a-b230-b4dcc066b1bc",
  "source": "shipyard-controller",
  "specversion": "1.0",
  "time": "2021-05-14T07:59:23.734Z",
  "type": "sh.keptn.event.evaluation.triggered"
  "shkeptncontext": "01f8980c-53d1-4826-8a95-90ab60fe39f0",
  "shkeptnspecversion": "0.2.1"
}
```

Last but not least, lighthouse-service needs to be adapted to read `taskStartedBeforeWait` and `taskStartedAfterWait`.

**Comment by christian-kreuzberger-dtx** [comment]
Alternative idea:

shipyard-controller is extended, such that we can use properties as follows:
```
            - name: "evaluation"
              triggeredAfter: "2m"
              properties:
                start: time.now() - $triggeredAfter 
                end: time.now()
```

Even expressions that evaluate a previous task result could be needed, e.g.:

```
            - name: "test"
              properties:
                  teststrategy: "performance"
            - name: "evaluation"
              triggeredAfter: "2m"
              properties:
                start: ${data.test.start} 
                end: ${data.test.end}
```

**Comment by christian-kreuzberger-dtx** [comment]
Solution proposed by @bacherfl :

We can introduce a `timeframe` property to the evaluation cloudevent, same as we already have in api-service.

The corresponding shipyard would look as follows:

```
        - name: "remediation"
          triggeredOn:
            - event: "production.remediation.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks:
            - name: "get-action"
            - name: "action"
            - name: "evaluation"
              triggeredAfter: "5m"
              properties:
                 timeframe: "5m"  <-- A shorter (or longer) timeframe is possible here
```


We agreed on implementing this as it is the most explicit solution and provides most flexibility. Implementation task is in https://github.com/keptn/keptn/issues/4079.
