### ISSUE TITLE
lighthouse: Allow timeframe to be passed via cloudevent

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#4079]
Follow up of https://github.com/keptn/keptn/issues/4075

As a user, I want to be able to specify a timeframe for an evaluation, e.g.:
```
            - name: "evaluation"
              triggeredAfter: "10m"
              properties:
                timeframe: "5m"
```

This needs to be implemented in lighthouse-service, e.g., here:
https://github.com/keptn/keptn/blob/94dfd0a13961ae89d276a892612a2647097363bb/lighthouse-service/event_handler/start_evaluation_handler.go#L145-L152

Note: `start` should be inferred from the current cloudevent evaluation.triggered timestamp. `end` should be calculated as `start - timeframe`.
This is currently handled in API and should be refactored accordingly:
https://github.com/keptn/keptn/blob/069dd0f5c7b6f37a3737f4c0c9c7cf07a801b039/api/handlers/evaluation.go#L84-L131

# Definition of Done

- [ ] lighthouse-service accepts `evaluation.timeframe` in addition to `test.start`, `test.end`, `evaluation.start` and `evaluation.end`
- [ ] keptn/spec and keptn/go-utils `evaluation.triggered` cloudevent needs to be adapted to also include `timeframe`
- [ ] api-service refactored/changed to avoid duplicated code between lighthouse and api-service.
