### ISSUE TITLE
Shipyard controller: timestamps of delayed events are not set properly

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#4096]
When sending a delayed CloudEvent, the `time` property of the event is being set to the time when the event has been put into the queue. However, this behavior is not correct when the event should be sent with a delay - in this case the `time` property of the event should be set to the time when the event was actually sent.

**Current Behavior:**

Consider the following `shipyard.yaml`:

```
apiVersion: "spec.keptn.sh/0.2.0"
kind: Shipyard
metadata:
  name: "shipyard-echo-service"
spec:
  stages:
    - name: "firststage"
      sequences:
        - name: "echosequence"
          tasks:
            - name: "echo"
              triggeredAfter: "20s"
```

When triggering the `echosequence`, the sent events have the following timestamps:

```
{
  "type": "sh.keptn.event.firststage.echosequence.triggered",
  "time": "10:00:00" // simplified for easier readability
}
```

After 20s, the following event is sent:

```
{
  "type": "sh.keptn.event.echo.triggered",
  "time": "10:00:00" // should be "10:00:20"
}
```

**Desired Behavior:**

When triggering the `echosequence`, the sent events have the following timestamps:

```
{
  "type": "sh.keptn.event.firststage.echosequence.triggered",
  "time": "10:00:00" // simplified for easier readability
}
```

After 20s, the following event is sent:

```
{
  "type": "sh.keptn.event.echo.triggered",
  "time": "10:00:20" // time at which the event has actually been sent
}
```
