### ISSUE TITLE
Remediation-service lost fallback to `problem type: default`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4254]
### Bug

According to the spec: https://github.com/keptn/spec/blob/master/remediation.md#remediation, the `problemType: "default"` maps any problem to a remediation action. Hence, working as a fallback in case the type/title of the problem is unknown. 

*Issue:* This behavior is not supported anymore and missing in the function: https://github.com/keptn/keptn/blob/master/remediation-service/handler/get_action_event_handler.go#L83

### Acceptance criteria
- [ ] I can use the remediation.yaml (shown below) that maps any problem to the action: `escalate`
```
apiVersion: spec.keptn.sh/0.1.4
kind: Remediation
metadata:
  name: remediation-configuration
spec:
  remediations: 
  - problemType: "default"
    actionsOnOpen:
    - name: Escalate problem
      action: escalate
      description: Escalate the problem using a SlackBot
```

### Definition of Done
- [ ] A remediation.yaml with a `problemType: default` can be used as fallback for any problem type
- [ ] Integration test guarantees support of this fallback strategy
