### ISSUE TITLE
Provide a default value for "scope" in secrets API

### ISSUE THREAD

**Issue by warber** [keptn/keptn#4281]
# Action Item

Currently, the user **must** provide a valid scope in order to create or delete a secret. However, the user has no idea what shall be the value of that scope.

Per default, the SecretService is configured with the following `scopes.yaml` file:
```
Scopes:
  keptn-default:
    Capabilities:
      keptn-secrets-default-read:
        Permissions:
          - get
```

Hence, the `scope` API parameter for creating and reading a secret shall be optional and default to `keptn-default`
