### ISSUE TITLE
Show action name and description for a remediation action

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4410]
### User story

As a user, I would like to see the action and description as defined in my remediation.yaml: 

```
apiVersion: spec.keptn.sh/0.1.4
kind: Remediation
metadata:
  name: remediation-configuration
spec:
  remediations: 
  - problemType: "Response time degradation"
    actionsOnOpen:
    - name: Toogle feature flag
      action: togglefeature
      description: Toggle feature flag EnablePromotion from ON to OFF
      value:
        EnablePromotion: off
```

#### Details

* Currently: 
![image](https://user-images.githubusercontent.com/729071/122552478-a7629800-d036-11eb-9bec-8847dfa4643a.png)

* Add description + show action name (if available) (If the data is missing, don't show the information):
![image](https://user-images.githubusercontent.com/729071/122552830-18a24b00-d037-11eb-9b3a-415e331cd4eb.png)

#### Acceptance criteria
- [ ] I see action **name** and description as defined in the remediation.yaml
