### ISSUE TITLE
Deploy Mongodb as a `StatefulSet`

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#4526]
## Action Item
`mongodb` shall be deployed as a StatefulSet.

### Details

Currently, we are deploying our `mongodb` as a k8s `Deployment` with `Recreate` strategy and 1 replica.

To guarantee zero-downtime, and also high availability, it is recommended to use a `StatefulSet` for deploying the database.

As a proof of concept, I have deployed the database with the following configuration:

```
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        app: mongo
    spec:
      serviceAccountName: keptn-default
      securityContext:
        fsGroup: 184
      terminationGracePeriodSeconds: 10
      containers:
        - image: "docker.io/centos/mongodb-36-centos7:latest"
          name: mongo
          args:
            - run-mongod-replication
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-rs-volume
              mountPath: /var/lib/mongodb/data
          env:
            - name: MONGODB_DATABASE
              value: "keptn"
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-credentials
                    key: password
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-credentials
                    key: admin_password
            - name: MONGODB_REPLICA_NAME
              value: "mongodb-replicaset"
            - name: MONGODB_KEYFILE_VALUE
              value: "mykeyfilevalue"
            - name: MONGODB_SERVICE_NAME
              value: mongo
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/initialized
          securityContext:
            runAsNonRoot: true
            runAsUser: 184
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
  volumeClaimTemplates:
  - metadata:
      name: mongo-rs-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

after applying this `StatefulSet` in the `keptn` namespace, I verified that the three replicas have been created:

```
$ kubectl get pods -n keptn -lrole=mongo
NAME      READY   STATUS    RESTARTS   AGE
mongo-0   1/1     Running   0          71m
mongo-1   1/1     Running   0          71m
mongo-2   1/1     Running   0          70m
```

Afterward, I tried to update the database by changing the image tag: As expected the update was applied to one pod one after another, while always maintaining at least one running instance of the replica set.

In the services using the database, the connection string had to be adapted by appending the name of the replica set, e.g.:

```
mongodb://<user>:<password>@mongo:27017/keptn?replicaSet=mongodb-replicaset
```

**NOTE:** One drawback of deploying the database as a `StatefulSet` is that it is not straightforward to use `kubectl port-forward` to connect MongoDB compass to the database anymore, which has a negative impact on the developer experience. The reason for that is that when connecting to a replicaSet, the mongodb cluster returns a list of available Hostnames to connect to, e.g.:

```
mongo-0.mongo.keptn.svc.cluster.local (primary)
mongo-1.mongo.keptn.svc.cluster.local
mongo-1.mongo.keptn.svc.cluster.local
```

These URLs are then used by Mongodb Compass to connect to an instance of the replicaset, but of course these cluster-internal server names cannot be resolved on the local developer machine.
Maybe this can be addressed by using a proxy service within the cluster and connecting to that via MongoDB Compass.

**NOTE:** Maybe another option to consider is to use the mongodb K8s operator to deploy the database. As documented here, this one seems to handle upgrades to the database more efficiently, as documented here: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/architecture.md#example-mongodb-version-upgrade

## Acceptance Criteria
- [ ] `mongodb` deployed as a stateful set which also supports the `rollingUpdate` deployment strategy
- [ ] mongodb can also be accessed directly via port forwarding
- [ ] if possible , use an external helm chart as dependency in our installer chart (like it's done for NATS) (this should also be compatible with openshift)

## Definition of Done
- [ ] feature implemented and reviewed
- [ ] installer adopted
