### ISSUE TITLE
Make timeout configurable per task

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#4624]
Currently, the task timeout implemented in #3778 is configurable via an environment variable in the shipyard controller, which can also be set in the values.yaml file of the keptn helm chart (the default is 20min). However, for certain tasks it might be necessary to adapt this value, e.g. for a manual approval step, which might take longer.
This could be done by adding a `timeout` property that can be set for each task in the `shipyard.yaml` file, like in the following example:

```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
            - name: "evaluation"
            - name: "approval"
              timeout: 2h       // <---
```

**Definition of done:**

- [ ] The shipyard controller considers the timeout value for the given task when it checks for timed out sequences. If no value is set, it will use the default value defined by `TASK_STARTED_WAIT_DURATION` (like it is currently implemented)
- [ ] The new `timeout` property is documented in the spec and in the docs
- [ ] Feature is covered by an Integration test
