### ISSUE TITLE
Visualize tasks that are currently waiting for triggeredAfter

### ISSUE THREAD

**Issue by grabnerandi** [keptn/keptn#4657]
When having a sequence definition that includes a task with "triggeredAfter" it is not visible to the end user that the current sequence is currently waiting for that event to happen. Here is my shipyard with the tiggeredAfter: 10m for the evaluation task

```
  - name: staging
    sequences:
    - name: delivery
      tasks:
      - name: monaco
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: evaluation
        triggeredAfter: "10m"
```

And this is what I see in the bridge. Would be great to get any indication that the next tasks will be evaluation but its currently waiting for it. Otherwise I wonder what is happening right now
![image](https://user-images.githubusercontent.com/675886/125742617-b86bf79a-2866-4253-b725-9b1231954ceb.png)
