### ISSUE TITLE
Allow configuring a git user/email for the default Git user of the configuration-service

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#4669]
## Use case

As a user, I would like to configure a git user/email for the default git user; currently, the `keptn` user with the `keptn@keptn.com` email is hardcoded.  

**Details**

* Allow to set the data in the values.yaml (https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/values.yaml#L77) of the configuration-service:
```
configurationService:
  image:
    repository: docker.io/keptn/configuration-service
    tag: ""
  # storage and storageClass are the settings for the PVC used by the configuration-storage
  storage: 100Mi
  storageClass: null
  env:
    gitUser: 
    gitEmail: 
```

* This is then added to the deployment of the configuration-service: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/core.yaml#L630

* Use the environment variables for git `user` / `email` in this function (https://github.com/keptn/keptn/blob/master/configuration-service/restapi/configure_configuration_service.go#L134) 

### Acceptance criteria

- [ ] Allow configuring default git user/email via values.yaml of Helm Chart
