### ISSUE TITLE
Add stages after initial project creation

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/keptn#4693]
**Is your feature request related to a problem? Please describe.**
Ability to add stages after initial project creation.

Go from this:

```
---
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: dynatrace
spec:
  stages:
    - name: preprod
    - name: prod
```

To:

```
---
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: dynatrace
spec:
  stages:
    - name: preprod
    - name: qa
    - name: prod
```

Then run something like:

```
keptn update project dynatrace --shipyard=shipyard.yaml
```

Potentially Keptn could also periodically read the shipyard in the upstream Git repo and reflect changes automatically.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
