### ISSUE TITLE
Add a WebHook Service

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4736]
## User Story

As a user, I would like to configure a webhook that gets called for specific events.

### Details

The webhook service is a default Keptn-service that will live in the @keptn-contrib organization.

When the webhook service gets triggered by an event, it first sends a `sh.keptn.event.[task].started` event. After that, it looks for the `webhook.yaml` file. The lookup strategy searches the `webhook.yaml` in well-defined directories, based on the following priority:
- `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource`
- `/project/{projectName}/service/{serviceName}/resource`
- `/project/{projectName}/stage/{stageName}/resource`
- `​/project​/{projectName}​/resource`

If no file is found, the webhook service sets the result of the `.finished` event to `fail`.

The configuration (`webhook.yaml`) of the webhook service looks as follows:
```yaml
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
  - type: "sh.keptn.event.test.triggered"
    envFrom:
    - secretRef:
      name: mysecret
    requests:
    - "curl --header 'Content-Type: application/json' --header 'x-token: ${SECRET_KEY}' --request POST –data '{\"event\":\"{{.event.type}}\",\"service\":\"{{.event.data.service}}\",\"environment\":\"{{.event.data.stage}}\" https://api.mycompany.com"
```

When the file is found, the webhook service executes the `curl` command. Mind that, replacing `{{.value}}` with proper data will be done in (#4742).

The webhook service will set the result of the `.finished` event to `pass` if the HTTP webhook returned 2xx (200-299); if not, it will return `fail`.
The response body of the webhook call is added to the `data.[task]` section of the `.finished` event.

## Acceptance Criteria

- [ ] Webhooks are called for an event
- [ ] Secrets via env vars are visible by curl
- [ ] Make sure that only `curl` commands can be set in `webhook.yaml`

## DoD

- [ ] The webhook service is implemented
- [ ] Unit tests
- [ ] Integration tests

---

### Dependencies

- #4437
