### ISSUE TITLE
Controls to configure a webhook

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4750]
## User Story

As a user, I can enter the configuration for the webhook call and the configuration is stored in the Git repo. 

### Details

![webhook-basic](https://user-images.githubusercontent.com/992621/126762156-83ea59a9-b39a-4dd0-a78b-65b0dd144221.jpg)

Besides the task (e.g., `evaluation.triggered`) and filter (e.g. stage/service) of a normal integration, 
the Bridge should provide for the webhook service the possibility to configure the following properties:

- request method: [`POST`, `PUT`]
- request URL: the webhook endpoint that is called
- list of custom headers that are passed over to the endpoint (optional)
- payload
- proxy (optional)

The Bridge should notify the user about misconfiguration of the webhook service when:
- not a valid URL is provided in the URL and proxy fields
- ~localhost/internal cluster IP is used :question:~

After a user entered the information and clicked the [Save] button, a `webhook.yaml` is stored in the Git repository of this project. The content of the `webhook.yaml` file is the following:

```yaml
apiVersion: webhook.keptn.sh/v1alpha1
kind: Webhook
metadata:
  name: webhook-configuration
spec:
  requests:
  - "curl --header "Content-Type: application/json" --request POST –data '{"event":"{{.event.type}}","service":"{{.event.data.service}}","environment":"{{.event.data.stage}}' https://api.mycompany.com"
```

The stage and service filters define the exact location where the `webhook.yaml` is stored.

- If no service filter is selected, the config is stored on project level: `​/project​/{projectName}​/resource`
- If a stage filter is selected, it is stored on stage-level: `/project/{projectName}/stage/{stageName}/resource`
- If a service filter is selected, it is stored on service-level: `/project/{projectName}/service/{serviceName}/resource`
- If a stage & service filters are selected, it is stored on service-level: `/project/{projectName}/stage/{stageName}/service/{serviceName}/resource`

Furthermore, the Bridge should provide an example of the events the webhook service is subscribed to. This will facilitate the creation of a custom payload. For more details, see #4742.

## Acceptance Criteria

- [x] The webhook service can be configured
- [ ] A link with an event example is provided

## DoD

- [x] `webhook.yaml` is created via the Bridge
- [x] Unit tests
- [x] UI tests

## Dependencies

- #4736
