### ISSUE TITLE
Add secrets to webhooks

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#4751]
## User Story

As a user, I would like to use a secret value for the webhook call.

### Details

![webhook-secret](https://user-images.githubusercontent.com/992621/126771510-954b0470-4b22-46d7-9eb1-2e120530e291.jpg)

Detailed mockup:
![Add Subscription4](https://user-images.githubusercontent.com/2674029/133621696-95f46372-54c3-4198-8a0d-6a0bae28c84a.png)

When a user clicks on the :lock: icon, the value field is replaced with the possibility to select a secret and one of its keys. The list of secrets and their keys is implemented by #4749. 
As shown in the mockup for the "Custom payload" a popup overlay is opened that provides a list of secrets. The list is expandible, so for every secret, there will be the related keys in the expanded section.
❗ Only secrets with `scope` equal to `webhook-service` shall be presented. 

When a secret name (e.g., `mysecret`) and a secret key (e.g., `SECRET_KEY`) is selected, they should be reported in the `webhook.yaml` as follows:

```yaml
apiVersion: webhook.keptn.sh/v1alpha1
kind: Webhook
metadata:
  name: webhook-configuration
spec:
  envFrom:
  - secretRef:
    name: mysecret
  requests:
  - "curl --header "Content-Type: application/json" --header "x-token: ${SECRET_KEY}" --request POST –data '{"event":"{{.event.type}}","service":"{{.event.data.service}}","environment":"{{.event.data.stage}}' https://api.mycompany.com"
```

## Acceptance Criteria

- [x] The webhook service can be configured with secrets

## DoD

- [x] `webhook.yaml` with secrets is created via the Bridge
- [x] Only secrets with `scope` equal to `keptn-webhook-service` can be selected
- [x] Unit tests
- [x] UI tests

## Dependencies

- #4749 
- #4750
