### ISSUE TITLE
keptn trigger evaluation doesnt verify whether the shipyard file has a sequence named evaluation

### ISSUE THREAD

**Issue by nitishm** [keptn/keptn#4784]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 
* Keptn CLI version: 0.8.6
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`): 
* Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c18ff7bd5227b42c617cf371cf315d0423e91d5e", GitTreeState:"clean", BuildDate:"2021-05-25T17:38:04Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Docs
* [X] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

`keptn trigger evaluation` does not warn user if shipyard.yaml doesn't contain a sequence named "evaluation".

**To Reproduce**

Use shipyard.yaml with the following contents
```yaml
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-webserver"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "validation"
          tasks:
          - name: "test"
            properties:
              teststrategy: "functional"
          - name: "evaluation"
```

Use shipyard provided above.

**Expected behavior**

.

**Current behavior**

.

**Screenshots**

.

**Additional context**

.

**Comment by johannes-b** [comment]
Hi @nitishm,

I think I have to clarify an aspect that is not well documented yet.

The `keptn trigger evaluation` does not require an `evaluation` sequence in the shipyard file. The reason is that Keptn has a build-in `evaluation` sequence for each stage. In other words, the following Shipyard implicitly contains an `evaluation` sequence: 

```yaml
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-webserver"
spec:
  stages:
    - name: "dev"
 ```
 
In the "long" format, the above Shipyard would look as shown Shipyard below that behaves the same way: 
 
 ```yaml
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-webserver"
spec:
  stages:
    - name: "dev"
       sequences:
        - name: "evaluation"
          tasks:
          - name: "evaluation"
 ```
 
Consequently, it would not make sense to warn the user of a missing evaluation since a default (built-in) one is actually available. 

Does this clarify your question and help?
