### ISSUE TITLE
Implement keptn k8s operator for shipyard files

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#503]
Write operator that handles Shipyard CRs.

```
---
apiVersion: sh.keptn/v1alpha1
kind: Shipyard
metadata:
  name: project1
spec:
  stages:
  - name: "dev"
    deployment: "direct"
    test: "performance"
  - name: "production"
    deployment: "blue-green"
    test: "functional"
```

It should take care of creating the configuration needed (folder structure and template files).
Furthermore, the operator takes care of creating the namespaces for the app.

For example:
https://github.com/michaelHampel/shipyard-operator
