### ISSUE TITLE
deployment.finished should not be set when task is not available in shipyard

### ISSUE THREAD

**Issue by laneli** [keptn/keptn#5309]
Following shipyard.yaml is in use:
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-easytravel"
spec:
  stages:
    - name: "quality-gate"
      sequences:
        - name: "delivery"
          tasks:
            - name: "test"
              properties:
                teststrategy: "performance_5"
            - name: "evaluation"
        - name: "evaluation"
          tasks:
            - name: "evaluation"         
```
What is the setup:
* This shipyard is configured for quality gates
* The shipyard configures a delivery sequence but does not define the `deployment` task
* The bridge is configured for quality gates only use case

The symptom:
* The Environment screen / last sequence in the Sequence screen shows the last evaluation from the latest delivery sequence. The Services screen does not have the latest but a weird one. It has a different context id set than the one for the last executed delivery sequence. Also, there seems to be no sequence in the sequence screen accessible with this id.

Why is this happening:
* The bridge does not differ between quality gates only use case and continuous deployment use case when it gets to retrieving the context id of the last sequence. The logic is the following:
    * In the service screen the Bridge looks first for the context id of the `deployment.finished` task
    * If the `deployment.finished` task is not available, it takes the context id of `evaluation.finished`
* There is a `delivery` sequence configured without a `deployment` task. Nonetheless, in the backend the `deployment.finished` task is still set (and also with a weird context id that looks more like a placeholder - `6e756c6c-2020-4020-a020-202020202020`)
* So the Bridge takes this weird context id and loads the evaluations for that sequence (which is not the last one executed)
* In the service screen now this inconsistent sequence execution for the wrong id is shown.
* Also for the evaluation board coming from this sequence this wrong id is used, and suddenly weird behavior like 4 boards appear

How to fix this:
* The backend should not set any `deployment.*` task when no deployment is configured in the shipyard.
