### ISSUE TITLE
Core: Allow WebHook to do not send finished events

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5368]
## Action Item 

Add a configuration parameter to the webhook configuration for not sending the `finished` event.

## Technical Details

If this option is enabled, the webhook will only send a `started` event. The respective `finished` event is expected to be received from a remote execution plane via the `POST /event` API call. The webhook configuration should look like the following:

```
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      subscriptionid: my-sub-id
      sendFinished: false         # <- new field
      envFrom:
        - name: "secretKey"
          secretRef:
            name: "slack-secret"
            key: "endpoint"
      requests:
        - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Test triggered in {{.data.stage}}\"}' https://hooks.slack.com/services/{{.env.secretKey}}"
```

The SDK should be extended to support this. 

## DoD

- [ ] If `sendFinished` is true, the WebHook-service will send the `finished` event
- [ ] If `sendFinished` is false, the WebHook-service will **not** send the `finished` event
- [ ] Unit tests
