### ISSUE TITLE
Event message does not contain the `problemTitle`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#5548]
##

* A remediation sequence gets triggered using: 
```
{
  "data": {
    "labels": {
      "Problem URL": "https:///#problems/problemdetails;pid=-240816790436828345_1633506659151V2"
    },
    "problem": {
      "ProblemTitle": "Http monitor global outage",
    },
    "project": "musicshop",
    "service": "carts",
    "stage": "production"
  },
  "id": "d485ea90-e1ef-4ce2-af21-32d44c3cb3fb",
  "source": "dynatrace-service",
  "specversion": "1.0",
  "time": "2021-10-06T07:53:26.637Z",
  "type": "sh.keptn.event.production.remediation.triggered",
  "shkeptncontext": "2d323430-3831-4637-b930-343336383238",
  "shkeptnspecversion": "0.2.1"
}
```

* The remediation.yaml looks as follows: 

```
apiVersion: spec.keptn.sh/0.1.4
kind: Remediation
metadata:
  name: carts-remediation
spec:
  remediations:
    - problemType: Response time degradation
      actionsOnOpen:
        - action: scaling
          name: scaling
          description: Scale up
          value: "1"
    - problemType: response_time_p90
      actionsOnOpen:
        - action: scaling
          name: scaling
          description: Scale up
          value: "1"
``` 

* The `problemTitle` does not match any `problemType` remediation.yaml. This is intended. 

## Bug

* However, I get the following message where I'm missing the `probelmTitle` for more information:

![image](https://user-images.githubusercontent.com/729071/136343871-8cedd350-548d-44e0-93da-719c54866de2.png)

* An investigation into this situation depicted that just the `rootCause` is considered for writing this message: https://github.com/keptn/keptn/blob/master/remediation-service/handler/get_action_event_handler.go#L44

### Definition of Done
- [ ] An message is shown containing the `problemTitle` when available
