### ISSUE TITLE
Ability to add annotations to namespace creation

### ISSUE THREAD

**Issue by checkelmann** [keptn/keptn#557]
We are using Rancher to set up our clusters and manage secrets like certificates, registries etc. in Rancher Projects, which will be automatically distributed by Rancher in namespaces which will reside under this Project.

When keptn is dynamically creating namespaces for a workload, this namespace is not assigned to a project and could not use for instance pre-configured imagepullsecrets or certificates.

In Rancher a new namespace could be added to a project by a simple annotation in the namespace yaml. 

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
annotations: 
   field.cattle.io/projectId: c-sqc8w:project-2bmmx
``` 

It would be very helpful if there is any way to add extra annotations to the keptn create Namespace Template or a way to overwrite the internal manifests with one in my project GitHub branch.
