### ISSUE TITLE
shipyard-controller produces two test.triggered events

### ISSUE THREAD

**Issue by agrimmer** [keptn/keptn#5608]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): any
* Keptn Version (`keptn version`): 0.10.0-next.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): any
* Kubernetes version (`kubectl version`): any

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter
* [x] shipyard-controller

**Describe the bug**
The shipyard-controller produces two test.triggered events:
Shipyard:
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "evaluation"
          tasks:
            - name: "test"            
            - name: "evaluation"
              triggeredAfter: "11m"
```
<img width="2957" alt="Screen Shot 2021-10-11 at 10 53 24" src="https://user-images.githubusercontent.com/10980861/136761831-f764c5c3-a3f8-4836-9c0a-c5791d655b33.png">

**Expected behavior**
Only one test.triggered event is produced
