### ISSUE TITLE
Webhook configuration: Change of the task or task suffix is not reflected in the webhook.yaml 

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#5676]
**Environment**

* Client OS (e.g., Linux, macOS, Windows):
* Keptn Version (`keptn version`): `0.10.0-next.1`
* Kubernetes Cloud Provider (e.g., GKE, AKS):
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

Starting point in `webhook.yaml`:

```
    - type: sh.keptn.event.evaluation.started
      requests:
        - curl --request POST --data '{"text":"Evaluation finished 2
          {{.data.stage}}."}'
          https://hooks.slack.com/services/{{.env.secret_slacksecret_webhookidentifier}}
      envFrom:
        - name: secret_slacksecret_webhookidentifier
          secretRef:
            name: slack-secret
            key: webhook-identifier
      subscriptionID: 774088de-60ec-4c8e-bad2-1872bb15e4f3
```

Changing the task suffix from `evaluation.started` to `evaluation.finished` is not reflected in the `webhook.yaml`. (Please take a look that the custom payload was updated properly): 

![image](https://user-images.githubusercontent.com/729071/137100077-783db73f-716d-49e4-a37c-f92fbe866da9.png)

```
    - type: sh.keptn.event.evaluation.started
      requests:
        - curl --request POST --data '{"text":"Updated version
          {{.data.stage}}."}'
          https://hooks.slack.com/services/{{.env.secret_slacksecret_webhookidentifier}}
      envFrom:
        - name: secret_slacksecret_webhookidentifier
          secretRef:
            name: slack-secret
            key: webhook-identifier
      subscriptionID: 774088de-60ec-4c8e-bad2-1872bb15e4f3
```

**To Reproduce**

1. Go to the `webhook-service` and open a subscription.
2. Change the **Task** or **Task suffix**
3. Take a look into the `webhook.conf` 

**Expected behavior**
* The `webhook.conf` is properly updated.
