### ISSUE TITLE
updateDomain.sh creates duplicate entries in configmap

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#570]
When executing the `updateDomain.sh` script from the installer duplicate entries in the `manifests/gen/keptn-domain-configmap.yaml` are created.
Related to #553 

Here is an example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-domain
  namespace: keptn
data:
  app_domain: XXXXXXX
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-domain
  namespace: keptn
data:
  app_domain: XXXXXXX
apiVersion: v1
kind: ConfigMap
metadata:
  name: keptn-domain
  namespace: keptn
data:
  app_domain: XXXXXXX
```

Implement the bug fix:
truncate the file before adding the new configmap.
