### ISSUE TITLE
Invalid Shipyard File Breaks Bridge

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#5711]
**Environment**

* Client OS (e.g., Linux, macOS, Windows): macOS
* Keptn Version (`keptn version`): 0.9.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): k3d
* Kubernetes version (`kubectl version`):

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Uploading an invalid shipyard file causes "No projects available" to be shown in the bridge. Effectively breaking the bridge.

**To Reproduce**
Conduct this via the UI:

1. Create a new project using a valid shipyard.yaml file. Call it test1. Everything works as expected
2. Create a second project using an invalid shipyard file (see example below)
3. The bridge shows an error explaining that the project could not be created
4. `keptn get projects` shows the project *has* been created
5. Go to the bridge homepage and you'll  see that no projects are available
6. `keptn delete project test2` and the bridge will start working again

**Expected behavior**
A shipyard file is validated and unless it's entirely valid, the project is never created.

**Additional context**
```
keptn get projects
NAME		CREATION DATE			SHIPYARD VERSION
test1		2021-10-15T08:13:37+10:00	spec.keptn.sh/0.2.2

keptn get projects
NAME		CREATION DATE			SHIPYARD VERSION
test1		2021-10-15T08:13:37+10:00	spec.keptn.sh/0.2.2
test2		2021-10-15T08:15:32+10:00	spec.keptn.sh/0.2.2
```

<img width="810" alt="image" src="https://user-images.githubusercontent.com/26523841/137404102-d78998b6-7111-4276-b8e9-6fc78d56e597.png">

```
keptn delete project test2
Starting to delete project
Project deleted successfully
Shipyard of project test2 cannot be retrieved anymore. After deleting the project, the namespaces containing the services are still available. This may cause problems if a project with the same name is created later.
```

<img width="473" alt="image" src="https://user-images.githubusercontent.com/26523841/137404209-290db55e-fe4d-4bf5-9d47-d0b695cdf4f2.png">

## Valid Shipyard
```
---
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "dosomething"
          tasks:
            - name: "printtoconsole"
```

## Invalid Shipyard
```
---
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
stages:
    - name: "dev"
      sequences:
        - name: "dosomething"
```
