### ISSUE TITLE
Bridge: Add checkbox to set the `sendFinished` flag

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#5735]
## User Story

As a User, I would like my integration via WebHook to return the `*.finished` event.

## Technical Details
 
The Bridge should provide a checkbox to allow to configure this behavior for the WebHook integration.
The status of the checkbox should be saved in the webhook configuration, which looks like the following:

```
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      subscriptionid: my-sub-id
      sendFinished: false         # <- new field
      envFrom:
        - name: "secretKey"
          secretRef:
            name: "slack-secret"
            key: "endpoint"
      requests:
        - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Test triggered in {{.data.stage}}\"}' https://hooks.slack.com/services/{{.env.secretKey}}"
```
 
The flag has the following behavior:
- If `sendFinished` is true, the WebHook-service will send the `finished` event (default)
- If `sendFinished` is false, the WebHook-service will **not** send the `finished` event

This should be documented on hover. Mind to explain that if unchecked, the integration must provide the respective finished event.
 
## DoD

- [ ] UI Test
- [x] Feature implemented
- [x] On hover, present a small description of the feature

## Dependencies
 
- https://github.com/keptn/keptn/issues/5368
