### ISSUE TITLE
keptn update project results in OOMKill of configuration-service

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#5976]
This is with Keptn 0.10.0:

When I create a project and set an upstream I managed to OOMKill configuration-service:

**shipyard.yaml**
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "hardening"

```

**Watch Kubernetes pods**
```
watch -n1 kubectl get pods -n keptn
```

**Create project and update git upstream**
```
keptn create project example --shipyard=./shipyard.yaml
keptn update project example --git-user=wrong-user --git-token=wrong-token --git-remote-url=https://github.com/keptn/keptn.git
```

The CLI responds with
```
Starting to update project
Error: Update project was unsuccessful. Put "http://configuration-service:8080/v1/project/example": EOF

```

And if you watch the pods closely, you will see this at some point:
![image](https://user-images.githubusercontent.com/56065213/141137192-341640cf-eb10-4eff-83f3-47bf5b4085a5.png)
