### ISSUE TITLE
When declaring a subscription allow filtering for data.result of event

### ISSUE THREAD

**Issue by thschue** [keptn/keptn#6010]
To create more targeted notifications (e.g., send slack notification on deployment errored), it would make sense to allow filtering of the data result of an event.

**Comment by johannes-b** [comment]
Very similar to what the job-executor-service is capable of, I would like to filter on certain event properties: 

```
apiVersion: v2
actions:
  - name: "Run locust"
    events:
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "health"
```

Based on the above example, `sh.keptn.event.test.triggered` is forwarded when `teststrategy` = `health`
