### ISSUE TITLE
Bridge: Add checkbox to set the `sendStarted` flag

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6059]
## User Story

As a user, I would like my integration via WebHook to return the `*.started` event.

## Technical Details
 
The Bridge should provide a checkbox to allow to configure this behavior for the WebHook integration.
The status of the checkbox should be saved in the webhook configuration, which looks like the following:

```
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      subscriptionid: my-sub-id
      sendFinished: false         
      sendStarted: false         # <- new field
      envFrom:
        - name: "secretKey"
          secretRef:
            name: "slack-secret"
            key: "endpoint"
      requests:
        - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Test triggered in {{.data.stage}}\"}' https://hooks.slack.com/services/{{.env.secretKey}}"
```
 
The flag has the following behavior:
- If `sendStarted` is true, the WebHook-service will send the `started` event (default)
- If `sendStarted` is false, the WebHook-service will **not** send the `started` event

This should be documented on hover. Mind to explain that if unchecked, the integration must provide the respective started event.

## Acceptance criteria

- [x] Enable this only if the subscription is on a `triggered` type
- [x] Feature implemented
- [x] Default value is true
 
## DoD

- [x] UI Test
- [x] On hover, present a small description of the feature

## Dependencies

- [x] #6524
