### ISSUE TITLE
Keptn CLI: Trigger any sequence from my Shipyard

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#6060]
### Use case

As a user, I would like to be able to trigger any sequence from my shipyard (not only `delivery` and `evaluation`) using the CLI. 

**Shipyard:**

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "my-sequence"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
```

`keptn trigger sequence my-sequence --project=sockshop --stage=dev --service=carts`

**Details:**
- project, stage, and service are mandatory

### Definition of Done
- [ ] I can trigger a sequence just by sequence name
- [ ] Unit test provided
- [ ] Documentation for the CLI command provided at code-level

**Comment by afzal442** [comment]
@johannes-b, I'd like to look into it. thanks

**Comment by thisthat** [comment]
Hi @afzal442, thank you for your help :)  I am assigning this to you!

**Comment by afzal442** [comment]
hello there! 
> As a user, I would like to be able to trigger any sequence from my shipyard

Could you be a little more explicit here? It would be of great help.  thanks

What does this object ` shipyard ` work?

**Comment by Dynatrace-Adam-Gardner** [comment]
#4839

**Comment by johannes-b** [comment]
Hello @afzal442 

Right now, Keptn CLI supports just triggering a sequence with name `delivery` and `evaluation`. This is too opinionated and too restrictive because a Shipyard can have multiple sequences with an arbitrary name (`my-sequence-1`, `my-sequence-2`) in a stage as shown below. 

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "my-sequence-1"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"

        - name: "my-sequence-2"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
```

With this feature, an enhancement of the CLI is planned to trigger any sequence using: 

`keptn trigger sequence <SEQUENCE_NAME> --project=<PROJECT --stage=<STAGE> --service=<SERVICE>`

Technically, this command needs to send an event to the `/event` endpoint of the Keptn API that looks as follows: 

```
{
  "data": {
    "project": "PROJECT",
    "service": "SERVICE",
    "stage": "STAGE"
  },
  "source": "cli",
  "specversion": "1.0",
  "type": "sh.keptn.event.dev.<SEQUENCE_NAME>.triggered",
  "shkeptnspecversion": "0.2.3"
}
```
