### ISSUE TITLE
distributor/uniform: Changing PUBSUB_TOPIC does not have any effect

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#6394]
This is with Keptn 0.10.0, but I assume it's also valid for 0.11.x:

I have installed a third-party integration that uses `keptn/distributor:0.10.0` with the following configuration:
```yaml
        - name: distributor
          image: keptn/distributor:0.10.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.test.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: VERSION ...
            - name: K8S_DEPLOYMENT_NAME ...
            - name: K8S_POD_NAME ...
            - name: K8S_NAMESPACE ...
            - name: K8S_NODE_NAME ...
```

After that, I decided that `test.triggered` was the wrong event to listen to, so I changed the deployment manifest and set `PUBSUB_TOPIC` to `sh.keptn.event.get-sli.triggered,sh.keptn.event.monitoring.configure`.

Related Slack Discussion: https://keptn.slack.com/archives/CGS63H8G6/p1639581004018800

## Current Behaviour

Unfortunately this seems to be overwritten by distributor:
```
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Starting Event Forwarder"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Registering Keptn Intgration"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Registered Keptn Integration with id 5f20ac47baad8d1a095db158c01209993c3f4787"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Starting UniformLog for Keptn service with integration ID 5f20ac47baad8d1a095db158c01209993c3f4787"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Connection type: nats"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Starting NATS event Receiver"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Connecting to NATS server at nats://keptn-nats-cluster ..."
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Subscribing to topic <sh.keptn.event.get-sli.triggered> with queue group <>"
[distributor] time="2021-12-15T15:08:07Z" level=info msg="Subscribing to topic <sh.keptn.event.monitoring.configure> with queue group <>"
[distributor] time="2021-12-15T15:08:17Z" level=info msg="Unsubscribed from NATS topic: sh.keptn.event.get-sli.triggered"
[distributor] time="2021-12-15T15:08:17Z" level=info msg="Unsubscribed from NATS topic: sh.keptn.event.monitoring.configure"
[distributor] time="2021-12-15T15:08:17Z" level=info msg="Subscribing to topic <sh.keptn.event.test.triggered> with queue group <>"
```

I never received any get-sli.triggered or monitoring.configure event, but I did receive test.triggered events.

This can also be seen in Keptn Bridge:
![image](https://user-images.githubusercontent.com/56065213/146520040-7f8fa1db-64d2-4f24-9579-5760ec4bacf7.png)

## Expected Behaviour

I would expect that setting `PUBSUB_TOPIC` works. This is also stated in the docs: https://keptn.sh/docs/0.11.x/integrations/custom_integration/

![image](https://user-images.githubusercontent.com/56065213/146519756-84a3ad45-6619-4408-ae2a-80ae51209fe1.png)
![image](https://user-images.githubusercontent.com/56065213/146519817-66120a6d-bd02-4e4b-9bb3-2bb9f44db3e5.png)
