### ISSUE TITLE
Core: Allow WebHook to do not send started events

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#6524]
## Action Item 

Add a configuration parameter to the webhook configuration for not sending the `started` event.

## Acceptance Criteria

- [ ] If `sendStarted` is true, the WebHook-service will send the `started` event
- [ ] If `sendStarted` is false, the WebHook-service will **not** send the `started` event

The webhook configuration should look like the following:

```
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      subscriptionid: my-sub-id
      sendFinished: false         
      sendStarted: false         # <- new field
      envFrom:
        - name: "secretKey"
          secretRef:
            name: "slack-secret"
            key: "endpoint"
      requests:
        - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Test triggered in {{.data.stage}}\"}' https://hooks.slack.com/services/{{.env.secretKey}}"
```

The SDK should be extended to support this. 

## Acceptance criteria

- [ ] The default value is `true`.
- [ ] If the subscription type is != than `triggered`, ignore the flag.

## DoD

- [ ] Unit tests
- [ ] Integration tests
