### ISSUE TITLE
Error message: Can we improve error message on API errors due to shipyard parsing

### ISSUE THREAD

**Issue by kethahel99** [keptn/keptn#6592]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**
Any keptn installation

* Client OS (e.g., Linux, macOS, Windows): Windows
* Keptn Version (`keptn version`): 0.11.4
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`):1.20.9

 N/A

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [x] REST API
* [ ] Webhook

**Describe the bug**
If you shipyard.yaml is not properly formatted .e.g indentiation, then you will receive and API error  "sequence tasks not iterable" message . As a result, you might have later (e.g. webhook or job-executor service) when trying to configure event subscriptions in the bridge
![image](https://user-images.githubusercontent.com/25621492/149542491-9b01c157-8540-4926-a8ee-d912c8822a5c.png)

**To Reproduce**

1. Change you shipyard.yaml file and decrease the indentiation of a task or tasks under one or more sequences e.g:

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
  - name: "quality-gate"
    sequences:
      - name: evaluation
        tasks:
        - name: monaco
        - name: evaluation
      - name: simple_evaluation
        tasks:
      - name: evaluation
        triggeredAfter: "6m"
        properties:
          timeframe: "6m"      
```

Note, that the evaluation task in the simple_evaluation sequence should have indentation for this to work properly e.g.

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
  - name: "quality-gate"
    sequences:
      - name: evaluation
        tasks:
        - name: monaco
        - name: evaluation
      - name: simple_evaluation
        tasks:
        - name: evaluation
          triggeredAfter: "6m"
          properties:
            timeframe: "6m"      
```

2. Go to Uniform
2. Click on  e.g. webhook-service
3. Click on Add subscription
3. The bridge UI will show a loading screen and the console will eventually report an HTTP 500 error
![image](https://user-images.githubusercontent.com/25621492/149543333-e58cd0f5-4756-4dea-8c36-b95403c2b7cc.png)

**Expected behavior**
Perhaps a more clear error mesasge like:

"The API cannot iterate though the tasks in your sequence : {sequence name}. Please verify that your shipyard.yaml is correct. Ensure to check indentation and format."

**Current behavior**
API error given is  "sequence tasks not iterable" and error is not handled with clear message on the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/25621492/149543704-d77effe1-8340-46f5-a587-bd86d64af995.png)
![image](https://user-images.githubusercontent.com/25621492/149543765-9f884669-32a8-415c-8412-8267f6e393c2.png)
![image](https://user-images.githubusercontent.com/25621492/149543810-6669c1bb-24df-4e01-b753-b268dae70a5b.png)

**Additional context**
N/A
