### ISSUE TITLE
Cryptic error messages when creating project

### ISSUE THREAD

**Issue by gecube** [keptn/keptn#6615]
Hello!

I am trying to start with Keptn and created the sample k8s cluster. I was able to install keptn with cli utility (I thought so).

```
keptn install --use-case=continuous-delivery
Kube context has been changed to do-fra1-k8s-1-21-3-do-0-fra1-1634723915649
Do you want to switch to the new Kube context with the Keptn running there? (y/n)y
Info: You can turn off the Kube context check by executing: keptn set config KubeContextCheck false

Please confirm that the provided cluster information is correct: 
Cluster: do-fra1-k8s-1-21-3-do-0-fra1-1634723915649
Is this all correct? (y/n)
y
Installing Keptn ...
Helm Chart used for Keptn installation: https://storage.googleapis.com/keptn-installer/keptn-0.11.4.tgz
Start upgrading Helm Chart keptn in namespace keptn
Finished upgrading Helm Chart keptn in namespace keptn
Keptn control plane has been successfully set up on your cluster.
Installing execution plane services for continuous-delivery use case.
Start upgrading Helm Chart helm-service in namespace keptn
Finished upgrading Helm Chart helm-service in namespace keptn
Start upgrading Helm Chart jmeter-service in namespace keptn
Finished upgrading Helm Chart jmeter-service in namespace keptn
---------------------------------------------------
* To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI:
 - kubectl -n keptn port-forward service/api-gateway-nginx 8080:80
 - keptn auth --endpoint=http://localhost:8080/api --api-token=$(kubectl get secret keptn-api-token -n keptn -ojsonpath={.data.keptn-api-token} | base64 --decode)

* Alternatively, follow the instructions provided at: https://keptn.sh/docs/0.11.x/operate/install/#authenticate-keptn-cli

* To expose Keptn on a public endpoint, please continue with the installation guidelines provided at:
 - https://keptn.sh/docs/0.11.x/operate/install#install-keptn
```

As one may see there were no error messages during install.
But when I tried to add new repo, I got a cryptic error message via GUI (yes, I was able to port-forward and login to GUI):

![](https://habrastorage.org/webt/n9/cc/xg/n9ccxgdvip_zlosq2l5h2hj7oyk.png)

I checked a little and found that configuration service is not up:

```
kubectl get pods -n keptn
NAME                                     READY   STATUS    RESTARTS   AGE
api-gateway-nginx-7c94d884fd-rjbgj       1/1     Running   0          49m
api-service-76b6b586bf-vzm5w             2/2     Running   2          49m
approval-service-6fd65f7fd6-b7blh        2/2     Running   0          49m
bridge-f89855f64-j54lk                   1/1     Running   0          49m
configuration-service-6cdc845c5d-k4zlk   0/1     Pending   0          49m <-----
helm-service-696949947c-4j8cl            2/2     Running   0          39m
jmeter-service-746bb44957-4nlfl          2/2     Running   0          38m
keptn-mongo-86bddb97b-zvk7c              1/1     Running   0          49m
keptn-nats-cluster-0                     2/2     Running   0          49m
lighthouse-service-774757f59b-n79km      2/2     Running   0          49m
mongodb-datastore-77966f7c4f-97lp8       2/2     Running   2          49m
remediation-service-56bcd588cb-wmz7k     2/2     Running   0          49m
secret-service-6dd97cbb59-nwwzl          1/1     Running   0          49m
shipyard-controller-6558f7d94-7dsff      2/2     Running   0          49m
statistics-service-5fc5877fd7-vzz7r      2/2     Running   0          49m
webhook-service-7c954dc57f-zgrjc         2/2     Running   0          49m
```

### Expected behaviour:

Precise error message in GUI stating the particular issue (like that the necessary service is not available or something similar)

Trying to get working keptn further... Please stay tuned.

**Comment by gecube** [comment]
p.s. I'd like to talk about UI/UX and ask several questions - is there any slack channel or similar for keptn?

**Comment by thisthat** [comment]
Hi @gecube thank you for your feedback! Did the configuration service eventually come up? If not, could you please provide some information about your environment and the errors that prevent it from running? This can help us identify the error.

Furthermore, you can provide suggestions in our public slack, I'd suggest in the help channel: https://keptn.slack.com/archives/CNRCGFU3U

**Comment by gecube** [comment]
Hi! I found that DO disallow very small volumes:

```yaml
kubectl describe pvc -n keptn configuration-volume
Name:          configuration-volume
Namespace:     keptn
StorageClass:  do-block-storage
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/component=control-plane
               app.kubernetes.io/instance=keptn
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=configuration-volume
               app.kubernetes.io/part-of=keptn-keptn
               helm.sh/chart=control-plane-0.1.0
Annotations:   meta.helm.sh/release-name: keptn
               meta.helm.sh/release-namespace: keptn
               volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       configuration-service-6cdc845c5d-8mxhl
Events:
  Type     Reason                Age               From                                                                                                      Message
  ----     ------                ----              ----                                                                                                      -------
  Normal   Provisioning          5s (x6 over 36s)  dobs.csi.digitalocean.com_master-k8s-1-21-3-do-0-fra1-1634723915649_0e807960-1ca7-4f2c-a5da-f06601153b7e  External provisioner is provisioning volume for claim "keptn/configuration-volume"
  Warning  ProvisioningFailed    5s (x6 over 36s)  dobs.csi.digitalocean.com_master-k8s-1-21-3-do-0-fra1-1634723915649_0e807960-1ca7-4f2c-a5da-f06601153b7e  failed to provision volume with StorageClass "do-block-storage": rpc error: code = OutOfRange desc = invalid capacity range: required (100Mi) can not be less than minimum supported volume size (1Gi)
  Normal   ExternalProvisioning  1s (x4 over 36s)  persistentvolume-controller                                                                               waiting for a volume to be created, either by external provisioner "dobs.csi.digitalocean.com" or manually created by system administrator
```

So I recreated the volume with correct size.
Now all services are OK:

```bash
kubectl get pods -n keptn
NAME                                     READY   STATUS    RESTARTS   AGE
api-gateway-nginx-7c94d884fd-59vzm       1/1     Running   0          4d23h
api-service-76b6b586bf-6n67p             2/2     Running   3          4d23h
approval-service-6fd65f7fd6-d4c25        2/2     Running   0          4d23h
bridge-f89855f64-kr7lm                   1/1     Running   0          4d23h
configuration-service-6cdc845c5d-8mxhl   1/1     Running   0          4d23h
helm-service-696949947c-7wvqk            2/2     Running   0          4d23h
jmeter-service-746bb44957-gv9rp          2/2     Running   0          4d23h
keptn-mongo-86bddb97b-zqmht              1/1     Running   0          4d23h
keptn-nats-cluster-0                     2/2     Running   0          4d23h
lighthouse-service-774757f59b-2w79m      2/2     Running   0          4d23h
mongodb-datastore-77966f7c4f-sfvtt       2/2     Running   3          4d23h
remediation-service-56bcd588cb-tcz28     2/2     Running   0          4d23h
secret-service-6dd97cbb59-5g86t          1/1     Running   0          4d23h
shipyard-controller-6558f7d94-s7r8d      2/2     Running   14         4d23h
statistics-service-5fc5877fd7-d2jzl      2/2     Running   1          4d23h
webhook-service-7c954dc57f-t6ssw         2/2     Running   0          4d23h
```

Trying to login...

**Comment by gecube** [comment]
I began from un-existing project. The main page shown me 500 without any further details. I found them only in logs of bridge service:

```
kubectl logs api-gateway-nginx-7c94d884fd-59vzm -n keptn
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
...
127.0.0.1 - - [26/Jan/2022:12:01:02 +0000] "GET /bridge/assets/icons/delete.svg HTTP/1.1" 200 309 "http://localhost:8080/bridge/create/project" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
127.0.0.1 - keptn [26/Jan/2022:12:42:44 +0000] "POST /bridge/api/controlPlane/v1/project HTTP/1.1" 500 30 "http://localhost:8080/bridge/create/project" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
10.244.1.92 - - [26/Jan/2022:12:42:44 +0000] "POST /api/controlPlane/v1/project HTTP/1.1" 500 55 "-" "axios/0.24.0"
127.0.0.1 - keptn [26/Jan/2022:12:42:45 +0000] "POST /bridge/api/controlPlane/v1/project HTTP/1.1" 500 30 "http://localhost:8080/bridge/create/project" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
10.244.1.92 - - [26/Jan/2022:12:42:45 +0000] "POST /api/controlPlane/v1/project HTTP/1.1" 500 55 "-" "axios/0.24.0"
127.0.0.1 - keptn [26/Jan/2022:12:42:48 +0000] "POST /bridge/api/controlPlane/v1/project HTTP/1.1" 500 30 "http://localhost:8080/bridge/create/project" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
10.244.1.92 - - [26/Jan/2022:12:42:48 +0000] "POST /api/controlPlane/v1/project HTTP/1.1" 500 55 "-" "axios/0.24.0"
127.0.0.1 - keptn [26/Jan/2022:12:42:52 +0000] "POST /bridge/api/controlPlane/v1/project HTTP/1.1" 500 30 "http://localhost:8080/bridge/create/project" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
10.244.1.92 - - [26/Jan/2022:12:42:52 +0000] "POST /api/controlPlane/v1/project HTTP/1.1" 500 55 "-" "axios/0.24.0"
```

```
kubectl logs bridge-f89855f64-kr7lm -n keptn

> bridge-server@ start /usr/src/app/server
> node --experimental-specifier-resolution=node dist/server/server.js

Installing default Look-and-Feel
Installing Basic authentication - please check environment variables!
Running on http://0.0.0.0:3000
Access denied
{ response: { status: 401 } }
GET /api/bridgeInfo 401 3.942 ms - -
GET /api/bridgeInfo 200 2.195 ms - 350
GET /api/v1/metadata 200 20.655 ms - 141
GET /api/version.json 200 701.892 ms - 1808
GET /api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50 200 9.409 ms - 33
GET /api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50 304 8.883 ms - -
GET /api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50 304 12.836 ms - -
GET /api/controlPlane/v1/project?disableUpstreamSync=true&pageSize=50 304 6.745 ms - -
Error for POST /api/controlPlane/v1/project: Could not clone git repository
POST /api/controlPlane/v1/project 500 714.543 ms - 30
Error for POST /api/controlPlane/v1/project: Could not clone git repository
POST /api/controlPlane/v1/project 500 551.847 ms - 30
Error for POST /api/controlPlane/v1/project: Could not clone git repository
POST /api/controlPlane/v1/project 500 739.624 ms - 30
Error for POST /api/controlPlane/v1/project: Could not clone git repository
POST /api/controlPlane/v1/project 500 610.692 ms - 30
```

OK. Let's create the empty project under https://gitlab.com/gecube/test-nginx
The repo is empty. And I got again 500 in GUI without any explanation. So I go to the bridge service and see the next:

```
kubectl logs bridge-f89855f64-kr7lm -n keptn
...
Error for POST /api/controlPlane/v1/project: Could not create stage.
POST /api/controlPlane/v1/project 500 4961.262 ms - 23
Error for POST /api/controlPlane/v1/project: Could not create stage.
POST /api/controlPlane/v1/project 500 5472.016 ms - 23
Error for POST /api/controlPlane/v1/project: Could not create stage.
POST /api/controlPlane/v1/project 500 5656.828 ms - 23
Error for POST /api/controlPlane/v1/project: Could not create stage.
POST /api/controlPlane/v1/project 500 5472.856 ms - 23
```

It is really very weird. Do I probably have an issue with shipyard file? No idea

```
cat ~/shipyard.yaml 
apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-nginx"
spec:
  stages:
    - name: "main"
```

The details are in configuration service logs:

```
kubectl logs -n keptn configuration-service-6cdc845c5d-8mxhl
2022/01/26 11:52:18 Serving configuration service at http://[::]:8080
time="2022-01-26T12:42:44Z" level=error msg="Could not clone git repository during creating project test-nginx" error="Error executing command git clone https://gecube:********@gitlab.com/gecube/test-nginx.git test-nginx: exit status 128\nCloning into 'test-nginx'...\nremote: The project you were looking for could not be found or you don't have permission to view it.\nfatal: repository 'https://gitlab.com/gecube/test-nginx.git/' not found\n"
time="2022-01-26T12:42:44Z" level=info msg="Rollback: try to delete created directory for project test-nginx"
time="2022-01-26T12:42:45Z" level=error msg="Could not clone git repository during creating project test-nginx" error="Error executing command git clone https://gecube:********@gitlab.com/gecube/test-nginx.git test-nginx: exit status 128\nCloning into 'test-nginx'...\nremote: The project you were looking for could not be found or you don't have permission to view it.\nfatal: repository 'https://gitlab.com/gecube/test-nginx.git/' not found\n"
time="2022-01-26T12:42:45Z" level=info msg="Rollback: try to delete created directory for project test-nginx"
time="2022-01-26T12:42:48Z" level=error msg="Could not clone git repository during creating project test-nginx" error="Error executing command git clone https://gecube:********@gitlab.com/gecube/test-nginx.git test-nginx: exit status 128\nCloning into 'test-nginx'...\nremote: The project you were looking for could not be found or you don't have permission to view it.\nfatal: repository 'https://gitlab.com/gecube/test-nginx.git/' not found\n"
time="2022-01-26T12:42:48Z" level=info msg="Rollback: try to delete created directory for project test-nginx"
time="2022-01-26T12:42:52Z" level=error msg="Could not clone git repository during creating project test-nginx" error="Error executing command git clone https://gecube:********@gitlab.com/gecube/test-nginx.git test-nginx: exit status 128\nCloning into 'test-nginx'...\nremote: The project you were looking for could not be found or you don't have permission to view it.\nfatal: repository 'https://gitlab.com/gecube/test-nginx.git/' not found\n"
time="2022-01-26T12:42:52Z" level=info msg="Rollback: try to delete created directory for project test-nginx"
time="2022-01-26T12:52:55Z" level=info msg="creating stage main from base main"
time="2022-01-26T12:52:57Z" level=error msg="Could not create main branch for project test-nginx" error="Error executing command git checkout -b main: exit status 128\nfatal: A branch named 'main' already exists.\n"
time="2022-01-26T12:53:02Z" level=info msg="creating stage main from base main"
time="2022-01-26T12:53:03Z" level=error msg="Could not create main branch for project test-nginx" error="Error executing command git checkout -b main: exit status 128\nfatal: A branch named 'main' already exists.\n"
time="2022-01-26T12:53:10Z" level=info msg="creating stage main from base main"
time="2022-01-26T12:53:11Z" level=error msg="Could not create main branch for project test-nginx" error="Error executing command git checkout -b main: exit status 128\nfatal: A branch named 'main' already exists.\n"
time="2022-01-26T12:53:19Z" level=info msg="creating stage main from base main"
time="2022-01-26T12:53:20Z" level=error msg="Could not create main branch for project test-nginx" error="Error executing command git checkout -b main: exit status 128\nfatal: A branch named 'main' already exists.\n"
```

So the branch is already exists. Hm... It is logical... but why GUI didn't tell anything about it? OK.

I am changing the shipyard.yaml to the next content:

```yaml
apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "shipyard-nginx"
spec:
  stages:
    - name: "main-test"
```
and getting the first project in Keptn.

![](https://habrastorage.org/webt/uw/xf/tr/uwxftrvntspi6ebww4qr2nrkj9k.png)
