### ISSUE TITLE
Bridge or Webhook Service Doesn't URL Encode Input

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7000]
**Environment**
* Keptn Version (`keptn version`): 0.12.2

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [x] Webhook

**Describe the bug**
The bridge UI and / or webhook service does not URL encode input but rather truncates at the first whitespace.

```
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.hello-world.finished
      requests:
        - curl --request GET https://example.com?foo=bar this
      subscriptionID: 09bbde98-f956-4afc-a15e-a1efeca2f859
      sendFinished: false
```

**To Reproduce**
Create a webhook subscription with the URL set to:

```
https://example.com?a=foo bar
```

Edit the subscription and it has been truncated to:

```
https://example.com?a=foo
```

**Expected behavior**
Bridge and / or webhook is able to take the raw string and URL encode it:

```
https://example.com?a=foo%20bar
```

Update: I think this is a bridge issue:

Given a request of: `curl --request GET https://example.com?foo=bar this`

1. It is stored correctly in YAML:
```
requests:
        - curl --request GET https://example.com?foo=bar this
```
2. It appears to be unmarshalled correctly:
```
yaml.Unmarshal(data, webHookConfig)
for _, webhook := range webHookConfig.Spec.Webhooks {
  for _, request := range webhook.Requests {
    fmt.Printf("Request is: %s", request)
  }
}
```
Output is `Request is:  curl --request GET https://example.com?foo=bar this`
