### ISSUE TITLE
Webhook returns `could not retrieve Webhook config: no webhook config found`

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7094]
**Environment**

* Keptn Version (`keptn version`): `0.13.x`

Keptn 0.12.x doesn't have this problem. 

**Affected Component**

* [x] Webhook

**Describe the bug**

* After upgrading to 0.13.2, I have added a new Webhook config for the `notifiy` task:

![image](https://user-images.githubusercontent.com/729071/157236048-185a765d-e751-4e25-afb1-dee0d0019c34.png)

* This causes the problem of: `could not retrieve Webhook config: no webhook config found` as shown here: 

![image](https://user-images.githubusercontent.com/729071/157236211-0127022d-2242-423c-8e3b-521f7cc42992.png)

**Expected behavior**
* The webhook on my `notify` task is called. 

## More information

The configuration-service contains the webhook.yaml file under `/data/config/sockshop/webhook/webhook.yaml` (main branch) and its content is:

```
apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notify.triggered
      requests:
        - curl --request POST --data '{"notify":"{{.data.action.action}}"}'
          https://webhook.site/8edd369e-53bc-4e9d-81fd-f0b5ee97764b
      subscriptionID: 8f32c63f-c610-486f-823d-918b5c709160
      sendFinished: true
```

The webhook-svc logs are the following:

```
time="2022-03-08T12:26:36Z" level=info msg="Sending sh.keptn.event.notify.started event"
time="2022-03-08T12:26:37Z" level=info msg="Sending sh.keptn.event.notify.finished event"
time="2022-03-08T12:26:37Z" level=error msg="error during task execution could not retrieve Webhook config: no webhook config found"
```

In mongo, there are the following entries in the `keptn.Uniform` collection:

```json
{
   "_id":"5d64eb87c4ce3e23935758c418df9d980c16a3b1",
   "name":"webhook-service",
   "metadata":{
      "hostname":"-redacted-",
      "integrationversion":"0.13.2",
      "distributorversion":"0.13.2",
      "location":"control-plane",
      "kubernetesmetadata":{
         "namespace":"keptn",
         "podname":"webhook-service-yadayada",
         "deploymentname":"webhook-service"
      },
      "lastseen":{
         "$date":"2022-03-09T14:22:35.375Z"
      }
   },
   "subscription":{
      "topics":null,
      "status":"",
      "filter":{
         "project":"",
         "stage":"",
         "service":""
      }
   },
   "subscriptions":[
      {
         "id":"281c227d-9576-4968-97f7-afa98a59b035",
         "event":"sh.keptn.event.action.triggered",
         "filter":{
            "projects":[
               "sockshop-jb"
            ],
            "stages":[ ],
            "services":[ ]
         }
      },
      {
         "id":"8f32c63f-c610-486f-823d-918b5c709160",
         "event":"sh.keptn.event.notify.triggered",
         "filter":{
            "projects":[
               "sockshop"
            ],
            "stages":[ ],
            "services":[ ]
         }
      }
   ]
}
```
