### ISSUE TITLE
The Kind Keptn Tries to Bind to High Port and Fails

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7112]
```
The connection to the server 0.0.0.0:40813 was refused - did you specify the right host or port?
```

For some users, thekindkeptn attempts to bind to a high port and fails. Therefore kubectl never authenticates and thus everything else fails.

The line going wrong in the install_script.sh is: https://github.com/agardnerIT/thekindkeptn/blob/e870cb97b23456d32e99f07e2831673891383d02/install_script.sh#L36
`k3d cluster create mykeptn --config=/root/k3dconfig.yaml --wait`

Where the k3dconfig.yaml is:
```
---
apiVersion: k3d.io/v1alpha3
kind: Simple
name: mykeptn
servers: 1
#agents: 1
ports:
  - port: 80:80
    nodeFilters:
    - loadbalancer
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returning; same as `--wait` (default: true)
    timeout: "60s" # wait timeout before aborting; same as `--timeout 60s`
    #disableLoadbalancer: true
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server` command
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true # add new cluster to your default Kubeconfig; same as `--kubeconfig-update-default` (default: true)
    switchCurrentContext: true # also set current-context to the new cluster's context; same as `--kubeconfig-switch-context` (default: true)
```
