### ISSUE TITLE
Missiling use of the node name

### ISSUE THREAD

**Issue by bmaschio** [keptn/keptn#7115]
**Is your feature request related to a problem? Please describe.**
I have been trying your solution and I had noticed a small but confusing use of the term  `name`
```yaml
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
```
Now the sequence name actually trigger a specific behavior both in the case of sequences that of task

**Describe the solution you'd like**
I would add the node type if the value "delivery" or "deployment" is functional  
```yaml
    - name: "dev"
      sequences:
        - name: "someName"
          type: "delivery"
          tasks:
            - name: "deployment"
              type: "deployment"
              properties:
                strategy: "direct"
```
in this way, the property node will not need to repeat deployment

It is just a suggestion once understood the mechanism is pretty simple to use
