### ISSUE TITLE
Race-condition in shipyard-controller: Adding webhook to a task that runs on remote-execution-plane prevents remote-execution-plane from working

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#7184]
This is with Keptn 0.12.3 and the following setup:

* Installed Keptn control plane on cluster A
* Installed job-executor-service on cluster B, connected via distributor and remote-execution-plane with config shown below
* Created a new webhook task on `remote-task.triggered` that posts to webhook.site

*shipyard* 
```yaml
apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "shipyard-job-exec"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "remote-task"
```

*job/config.yaml*
```yaml
apiVersion: v2
actions:
  - name: "My remote task"
    events:
      - name: "sh.keptn.event.remote-task.triggered"
    tasks:
      - name: "Say Hello"
        image: "alpine:3.15"
        env:
          - name: PROJECT
            valueFrom: event
            value: "$.data.project"
        cmd:
          - echo
        args:
          - "Hello $(PROJECT)!"
```

# Current behaviour

## Before creating the webhook

job-executor is taking the task
![image](https://user-images.githubusercontent.com/56065213/158765948-f2bcf305-5112-475d-bbd8-686d63c47a5c.png)

## After creating the webhook

webhook-service is taking the task
![image](https://user-images.githubusercontent.com/56065213/158766039-dd03fb5a-31dc-49df-af3c-66554c8e08fd.png)
or
job-executor and webhook-service are taking the task
![image](https://user-images.githubusercontent.com/56065213/158766156-d9930117-85f5-4054-bbbc-c6edffa5850f.png)
(depends on the timing...)

# Expected behaviour

It should always be the case that job-executor and webhook-service take the task
