### ISSUE TITLE
keptn CLI: configure monitoring

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/keptn#721]
Add a command to the keptn CLI to configure the monitoring solution to be used.

`keptn configure monitoring prometheus --project=sockshop --service=carts --service-objectives=service-objectives.yaml --service-indicators=service-indicators.yaml --remediation=remediation.yaml` 

CLI creates new cloud event with values of the files in its payload.
Type of cloud event: `sh.keptn.event.monitoring.configure`

Contents of the files, e.g.:
```
indicators:
- name: cpu_usage_p95_sockshop_carts_production
  source: Prometheus
  query: avg(rate(container_cpu_usage_seconds_total{namespace="sockshop-production",pod_name=~"carts-blue-.*|carts-green-.*"}[1m]))
```

```
objectives:
- name: cpu_usage_p95_sockshop_carts_production
  threshold: 90
  timeframe: 5m
```

```
remediations:
- name: cpu_usage_p95_sockshop_carts_production
  actions:
  - action: scaling
    value: +1
```

Related to #706
