### ISSUE TITLE
Core: webhook-service improve configuration 

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7238]
## User Story

As a user, I would like to have more guidance in defining a webhook configuration.

## Acceptance Criteria

- The webhook configuration should be updated at version `v1alpha1` to `v1beta1`
- The webhook configuration should have the following parameters:
   - `URL`: string
   - `headers`: list of key-value pairs
   - `payload`: string
   - `options`: string

## DoD

- The webhook can deal with both configuration versions
- Unit tests

**Comment by jainammm** [comment]
Hello,

Currently, I am looking to get familiar with contributing to keptn. This issue got my interest and I'd like to discuss the deliverable for the same in detail. If this issue is going to be picked for the latest milestone and needs attention, I'd like to work on it. 

I went through the ReadMe file of webhook-service. And also skimmed through the code a little bit. Went through the [curl_executor.go](https://github.com/keptn/keptn/blob/master/webhook-service/lib/curl_executor.go) file and its tests. I can see that users can add any URL with headers and other options mentioned in the issue description. 

So for this version of `v1beta1`, are we changing the way of adding curl URLs in the `webhook/webhook.yaml` file? Would the YAML file look like shown below: 

```
apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: "sh.keptn.event.mytask.triggered"
      subscriptionID: my-subscription-id
      envFrom: 
        - name: "secretKey"
          secretRef:
            name: "my-k8s-secret"
            key: "my-key"
      requests:
       - URL: "http://shipyard-controller:8080/v1/project/{{.data.project}}"
         Method: "POST"
         headers: "Content-type: application/json"
         payload: `{\"text\":\"Hello, World!\"}`
         options: "--http3"
       - URL: "http://shipyard-controller:8080/v1/project/{{.data.project}}/stage/{{.data.stage}}"
         Method: "GET"
         headers: "Content-type: application/json"
         payload: `{\"text\":\"Hello, World!\"}`
```

Is my understanding of the deliverable correct? 

Thanks.
