### ISSUE TITLE
Getting gateway timeouts in nginx gateway during upgrade of services providing REST APIs

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#7301]
When testing the zero downtime capabilities of Keptn, i came across several occasions where calls to a service providing a REST API were resulting in a Gateway timeout in the nginx Gateway. 

The upgrade strategy for the affected services was as follows:

```
strategy:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
     rollingUpdate:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
       maxSurge: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
       maxUnavailable: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
     type: RollingUpdate
```

also, to make sure a terminating pod has enough time to complete its current request, the grace period should be set, e.g. to 30s:

```
terminationGracePeriodSeconds: 30
```

So this should - in theory - ensure that there is always at least one instance of the service pod that is able to receive traffic. 

This scenario can be reproduced relatively consistently (it does not always happen, but still often enough to cause problems):

1. Continuously send API requests to a service, e.g.2. 

```
GET /api/v1/metadata
```

3.Update the image of the service, e.g. using the following command:

```
kubectl -n keptn set image deployment.v1.apps/api-service api-service=keptndev/api:0.14.0-dev-PR-7266.202203280650
sleep 10
kubectl -n keptn set image deployment.v1.apps/api-service api-service=keptndev/api:0.14.0-dev
```
