### ISSUE TITLE
Installer: Configure upgrade strategy for deployments

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#7303]
Right now, most of the deployments in our installer chart use the `Recreate` upgrade strategy, which does not support zero downtime capabilities, as the old pod will be deleted before the pod with the updated config will be started.

Therefore, we should support the use of the `rollingUpdate` strategy, e.g. with the following settings:

```
strategy:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
     rollingUpdate:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
       maxSurge: 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
       maxUnavailable: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
     type: RollingUpdate
```

This would make sure that at no point in time there will be 0 pods available for a deployment, while the number of pod can temporarily increase to `replicas + 1` during the upgrade.

## DoD

- [x] The default strategy would be `RollingUpdate` with 1 max surge and 0 unavailable - this is for all services.
- [x] Manual tests
