### ISSUE TITLE
Trigger sequence: `Delivery` sequence not shown even though defined in Shipyard

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#7356]
### Bug

As a user, I have this shipyard:

```
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "keptn web service delivery"
spec:
  stages:
  - name: production
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
```

However, the **Trigger sequence** feature shows:

![image](https://user-images.githubusercontent.com/729071/161572054-3126410c-59f0-41a2-9013-aff7565fa065.png)

As depicted by this screenshot, a `delivery` sequence is available and was triggered. 

### Expected behavior

* I can see / trigger the delivery sequence
