### ISSUE TITLE
Keptn Helm Chart flexibility for setting image repository and tag at one point

### ISSUE THREAD

**Issue by sarahhuber001** [keptn/keptn#7578]
### Use Cases
- As a developer I want to test my keptn fork build artefacts in a local kubernetes cluster environment.
- As a developer I want to build and deploy my customized keptn fork at my kubernetes cluster environment.
- As a keptn contributor I want to fork keptn, build, deploy and test my enhancements locally in my kubernetes cluster before I open a Pull Request.
- As a mac book pro m1 (arm64) user, I want to build keptn locally and deploy it to my kubernetes cluster.
- As a developer I want to set the repository and image tag at one point for all keptn artefacts.

### Problem
All this use cases are depending on flexible and customizable helm charts. To be more specific, currently it is not possible to update the image repository and the image tag of the keptn services at one point. One has to go through different `values.yaml` and `Chart.yaml` files to hopefully find all the possible locations where to update the image repository and tag.

Example `installer/manifests/keptn/charts/control-plane/values.yaml`
```
shipyardController:
  image:
    repository: docker.io/keptn/shipyard-controller
    tag: ""
```
As we can see here, the repository and the tag are hardcoded properties. As there are a lot of services in keptn where it is necessary to update the repository and image tag, it is a huge source of error.

## Solution & Proposal
We can use the helm templating engine to set the desired image repository and image tag in `values.yaml` and `values-local.yaml` at one point. If we introduce global values, we can achieve a much higher flexibility.

Example
`/installer/manifests/keptn/charts/control-plane/values.yaml`
```
global:
  keptn:
    registry: docker.io/keptn 
    tag: "" 

...
apiService:
  ...
  image:
    registry: "" 
    repository: "api" 
    tag: "" 

distributor:
  ...
  image:
    registry: ""
    repository: "distributor"
    tag: "" 
```
`installer/manifests/keptn/charts/control-plane/templates/api-service.yaml`
```
...
app.kubernetes.io/version: {{ include "service.tag" ( dict "imageRoot" .Values.apiService.image "global" .Values.global.keptn "defaultTag" .Chart.AppVersion) }}
...
image: {{ include "service.image" ( dict "imageRoot" .Values.apiService.image "global" .Values.global.keptn "defaultTag" .Chart.AppVersion) }}
...
```
Optional: One can use a values-local.yaml for customizing the repository and the appVersion
```
global:
  keptn:
    registry: "test/it/like-a-dude"
    appVersion: mylocalVersion
```
Introducing a new helper template `_images.tpl` in `installer/manifests/common` in bitnami style, helps us to decide about the registry, repository or image tag.

In addition to the changes above, the `installer/airgapped/install_keptn.sh` script can be fully refactored and simplified. For example: one would not have to add the registry (repository) name as an input parameter but can only set a flag like `values-local.yaml=true`. 

The benefit of this feature would be, the charts are open for new future custom configurations. As the only thing a developer would have to do, is to add a values-local.yaml. 

This proposal has no incompatibilities within the current keptn helm charts but rather introduces a flexible extension point to use custom keptn builds.

I am open for feedback as well as for other solutions!
