### ISSUE TITLE
Understand Installation Dependencies

### ISSUE THREAD

**Issue by agardnerIT** [keptn/keptn#7580]
During initial installtion, Keptn can take some time to "become usable" by this I mean having all pods in a `Running` state.

Frequently pods will `CrashLoopBackOff` and `Error` until "something" becomes available and / or "settles down".

Main concerns:

1. A new user will attempt a `keptn install` see pods erroring out and think Keptn is broken - leave and never progress
2. A user wishes to rollout Keptn quickly and these delays cause startup delays
3. Any monitoring of Keptn will be throwing noisy alerts during an install and thus special "no alert" windows will have to be used. Increasing overhead to working with Keptn.

All 3 are risks to the adoption or use of Keptn.

If the dependencies can be understood then (via separate tickets) solutions can be sought.

**Comment by agardnerIT** [comment]
One example from the shipyard controller.

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  3m59s              default-scheduler  Successfully assigned keptn/shipyard-controller-68bb7f4899-bhl4c to docker-desktop
  Normal   Pulling    3m54s              kubelet            Pulling image "docker.io/keptn/shipyard-controller:0.14.2"
  Normal   Pulled     75s                kubelet            Successfully pulled image "docker.io/keptn/shipyard-controller:0.14.2" in 2m39.0605258s
  Normal   Created    34s (x4 over 75s)  kubelet            Created container shipyard-controller
  Normal   Pulled     34s (x3 over 74s)  kubelet            Container image "docker.io/keptn/shipyard-controller:0.14.2" already present on machine
  Normal   Started    33s (x4 over 75s)  kubelet            Started container shipyard-controller
  Warning  Unhealthy  33s (x4 over 75s)  kubelet            Readiness probe failed: Get "http://10.1.0.21:8080/health": dial tcp 10.1.0.21:8080: connect: connection refused
  Warning  BackOff    30s (x8 over 72s)  kubelet            Back-off restarting failed container
```

**Comment by agardnerIT** [comment]
![image](https://user-images.githubusercontent.com/26523841/170605364-2a5eee15-03d2-4f85-9b37-d4bfbf7db9dd.png)

**Comment by agardnerIT** [comment]
@grabnerandi as we discussed

**Comment by agardnerIT** [comment]
Confirmed this occurs on `0.17.0`: 
![image](https://user-images.githubusercontent.com/26523841/178936870-24322c1a-676c-41f0-bb5f-52815a27a27e.png)

**Comment by agardnerIT** [comment]
@thisthat I'm keen to work on this to stop the crashes. Init containers are new to me but it seems that (although they wouldn't help the startup time) they might prevent the crashes and errors.

1. Am I on the right track?
2. What condition should I be waiting for? [This page](https://dzone.com/articles/kubernetes-demystified-solving-service-dependencie) shows an example of waiting for an `nslookup` to resolve. Would that work here?

```
initContainers:
      - name: init-mysql
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
```

**Comment by thisthat** [comment]
Hey @agardnerIT, yes init containers are a good way to solve this problem :) 
For the logic implemented by the init container, I don't know on top of my head what would be the best. Maybe we can try out if the URL of NATS is reachable. The URL can be configured to the pod via the env var `NATS_URL`, if it is missing, the default value is used: `nats://keptn-nats`
Otherwise, we could implement a small "ping" using a NATS-client. They offer clients for many different languages here: https://github.com/orgs/nats-io/repositories?type=source

**Comment by agardnerIT** [comment]
```
initContainers:
  - name: wait-for-nats
        image: busybox
        env:
          - name: "NATS_ENDPOINT"
            value: "keptn-nats"
        command: ['sh', '-c', 'until nslookup $NATS_ENDPOINT; do echo waiting for $NATS_ENDPOINT; sleep 2; done;']
```

Works for me
