### ISSUE TITLE
Bridge :: Make use of Webhook `v1beta1`

### ISSUE THREAD

**Issue by thisthat** [keptn/keptn#7839]
## Technical Details

In #7238, we introduced a new version of the webhook format `v1beta1`. A webhook file in the new format looks like the following:

```
apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: "sh.keptn.event.mytask.triggered"
      subscriptionID: 0123456789
      sendFinished: true
      requests:
        - url: http://mykeptnendpoint.org/api/v1/project/{{.data.project}}/stage/{{.data.stage}}
          method: GET
    - type: "sh.keptn.event.mytask.triggered"
      subscriptionID: 0123456987
      sendFinished: true
      envFrom: 
        - name: "secretKey"
          secretRef:
            name: "my-webhook-k8s-secret"
            key: "my-key"
      requests:
        - url: http://mykeptnendpoint.org/api/v1/project/{{.data.project}}
          method: GET
          headers:
            - key: x-token
              value: "{{.env.secretKey}}"
        - url: http://mykeptnendpoint.org/api/v1/project/{{.data.project}}/stage/{{.data.stage}}
          method: GET`
```

## Acceptance Criteria

- [x] Bridge can read both `v1alpha1` and `v1beta1` webhook versions
- [x] Bridge saves webhooks only in `v1beta1` version using the `api/configuration-service/v1` REST API

## DoD

- [x] Unit tests
