### ISSUE TITLE
Cannot register additional Execution Planes on Multi-cluster setup

### ISSUE THREAD

**Issue by hflobao** [keptn/keptn#8055]
**Environment**

* Keptn Version (0.16.0):
* Kubernetes Cloud Provider (EKS):
* Kubernetes version (1.22):

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [x] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

When trying to deploy Keptn on a Multi-cluster setup, only the first Execution Plane deployed is shown on the Uniform > Integrations.
All later Execution Planes deployed get a "200 - ok: registration already exists" response on registration and start operating over the same id of the first Execution Plane.

**To Reproduce**

1. Deploy Keptn Control Plane on ClusterX 
2. Deploy Keptn Execution Plane (helm-service & jmeter-service) on ClusterA
3. Deploy Keptn Execution Plane (helm-service & jmeter-service) on ClusterB
4. Get the Uniform Integrations, via API or on Bridge Project Settings screen and only the Execution Plane from step 2 is displayed.
5. Get the logs for the distributor container on both clusters (A and B) and check that the ids are the same.
```
$ kubectl logs helm-service-rrrrrrrrrr-ppppp distributor -n keptn-exec
(...)
level=info msg="Starting Event Forwarder"
level=info msg="Registering Keptn Integration"
level=info msg="Registered Keptn Integration with id 8f4a1891e8aa031462e98475100666052955d0cf"
level=info msg="Starting uniform log for Keptn service with integration ID 8f4a1891e8aa031462e98475100666052955d0cf"
```
**Expected behavior**

Have the Execution Plane from ClusterB listed as a remote-execution-plane on the Uniform > Integrations

**Current behavior**

The list of remote-execution-plane's doesn't change after deploying the helm-service and jmeter-service on ClusterB.
Even after setting an unique deployment name for the Helm Charts for ClusterA and ClusterB, the behavior doesn't changed.

**Additional context**

I was able to manage the issue and get ClusterB execution plane registered and working after doing the following steps.

1. Deploy the Execution Planes with unique Helm deployment names on ClusterA and ClusterB. On my case I just added a sufix with the Stage name that each cluster would handle (e.g. helm-service-dev on ClusterA and helm-service-prd on ClusterB)
2. Edit the deployment on each of the Execution Plane clusters (kubectl edit deploy) and changed the following lines/values on the distributor container spec:
- From
```
        - name: K8S_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/name']
```
- To
```
        - name: K8S_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/instance']
```

This change allowed the variable K8S_DEPLOYMENT_NAME to have the unique names provided on the item 1.
