### ISSUE TITLE
Distributor customizations not picked up by cp-connector anymore

### ISSUE THREAD

**Issue by heckelmann** [keptn/keptn#8295]
**Environment**

* Keptn Version (`keptn version`): v0.16.x

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [X] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When keptn was shipped with the old distributor we were able to set the following variables within the deployment

```
distributor:
  metadata:
    hostname:
    namespace:
```

These settings are not assigned to the new cp-connector library.

The helpers function does not include any custom settings for the env vars anymore

```
{{- define "control-plane.common.env.vars" -}}
- name: K8S_DEPLOYMENT_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
- name: K8S_DEPLOYMENT_VERSION
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
- name: K8S_DEPLOYMENT_COMPONENT
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: 'metadata.labels[''app.kubernetes.io/component'']'
- name: K8S_NAMESPACE
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.namespace
- name: K8S_NODE_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: spec.nodeName
- name: K8S_POD_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.name
{{- end }}
```
