### ISSUE TITLE
Shipyard Controller: Event Dispatcher does not clean event queue items when sequence is aborted

### ISSUE THREAD

**Issue by bacherfl** [keptn/keptn#8570]
**How to reproduce:**

Trigger a sequence with a delayed task, using the `triggeredAfter` property, e.g.:

```
--- 
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata: 
  name: shipyard-sockshop
spec: 
  stages: 
    - 
      name: dev
      sequences: 
        - 
          name: delivery
          tasks: 
            - 
              triggeredAfter: "10m"
              name: mytask
```

After the sequence has been started, cancel the sequence within the 10m time frame, specified by the `triggeredAfter` property.

**Outcome:**

The sequence will correctly be cancelled, and no `mytask` event will be sent out, which is expected. However, the entries in the `shipyard-controller-event-queue` collection will not be cleaned up properly, leading the event dispatcher to periodically look for the event associated to the remaining queue item, as indicated by the following logs:

```
time="2022-08-03T05:31:50Z" level=info msg="Dispatching event with ID 79efde7f-f8e1-443c-9591-6f8a99841355"
time="2022-08-03T05:31:50Z" level=error msg="could not fetch event with ID 79efde7f-f8e1-443c-9591-6f8a99841355: no matching event found"
time="2022-08-03T05:31:50Z" level=info msg="Dispatching event with ID 1d62fea7-78aa-4f41-8707-4f03c950d01a"
time="2022-08-03T05:31:50Z" level=error msg="could not fetch event with ID 1d62fea7-78aa-4f41-8707-4f03c950d01a: no matching event found"
time="2022-08-03T05:32:00Z" level=info msg="Dispatching event with ID 39c4b359-7461-4f93-95d3-498eca2c1316"
time="2022-08-03T05:32:00Z" level=error msg="could not fetch event with ID 39c4b359-7461-4f93-95d3-498eca2c1316: no matching event found"
```

Note that this will not impact the functionality of the sequence execution, but should be fixed nevertheless because this leads to unwanted log pollution
