### ISSUE TITLE
Multi-cluser setup of helm-service (and other intergrations) broken since 0.16.0

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/keptn#8576]
# Description

When creating a [multi-cluster setup according to our docs](https://keptn.sh/docs/install/multi-cluster/), you usually have the following setup:

* cluster-a: Keptn control-plane
* cluster-dev: dev stage
* cluster-prod: prod stage

The setup would look as follows:

**cluster-a**
```bash
helm install keptn keptn --version 0.16.0 -n keptn --repo=https://charts.keptn.sh --create-namespace --wait \
  --set=control-plane.apiGatewayNginx.type=LoadBalancer
```
---
**cluster-dev**

```yaml
distributor:
  projectFilter: ""                     # set the project, e.g., "sockshop" to get events for this project.
  stageFilter: "dev"              # set the stage, e.g., "hardening" to get events for the stage.
  serviceFilter: ""                     # set the service, e.g., "carts" to get events for the service.
```

```bash
helm install helm-service https://github.com/keptn/keptn/releases/download/0.16.0/helm-service-0.16.0.tgz -n keptn-exec --create-namespace --values=values.yaml
```
---
**cluster-prod**

```yaml
distributor:
  projectFilter: ""                     # set the project, e.g., "sockshop" to get events for this project.
  stageFilter: "prod"              # set the stage, e.g., "hardening" to get events for the stage.
  serviceFilter: ""                     # set the service, e.g., "carts" to get events for the service.
```

```bash
helm install helm-service https://github.com/keptn/keptn/releases/download/0.16.0/helm-service-0.16.0.tgz -n keptn-exec --create-namespace --values=values.yaml
```

## Observation

Only **one** helm-service appears on the integration page in Bridge. Also both helm-services / distributors get the same integration ID.

**Worst**: helm-service for *prod* is reacting on events for *dev* 

## Expected behaviour

Both helm-services should appear on in the ingrations page in Bridge.

## Root-Cause

Usually, our Kubernetes manifests have several environment variables that are used for registering an integration with the Keptn Uniform:
https://github.com/keptn/keptn/blob/ff76afbc56636e5931a1d1a1810c2a4da45637e3/helm-service/chart/templates/deployment.yaml#L142-L157

However, with this PR https://github.com/keptn/keptn/pull/8006 (merged for 0.16.0 final release), which was intended to fix a problem with zero downtime upgrades, we removed `K8S_NODE_NAME` from the subscription / integration.

Every integration is now uniquely identified by just two parameters: `K8S_DEPLOYMENT_NAME` (which in this case is always `helm-service`) and `K8S_NAMESPACE` (which in this case is `keptn-exec`).

# Hotfix Solution

As we usually have a STAGE_FILTER set, we can leverage this in our manifests and just change  `K8S_DEPLOYMENT_NAME` accordingly. I consider this a very hacky hotfix though.

**Change**
```yaml
        - name: K8S_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/name']
```
**to**
```yaml
        - name: TEMP_K8S_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/name']
        - name: K8S_DEPLOYMENT_NAME
          value: "$(TEMP_K8S_DEPLOYMENT_NAME)-$(STAGE_FILTER)"
```

# Desired Solution

- [ ] Subscriptions/integrations are not lost during upgrades (ZDUs should still work)
- [ ] Multi-cluster setup still works for 0.16.x without having to change the Kubernetes manifests
