### ISSUE TITLE
Missing and wrong field in carts service view

### ISSUE THREAD

**Issue by dirkwall** [keptn/keptn#864]
keptn version 0.5.0.beta on GKE

The image shown [here](https://keptn.sh/docs/0.5.0.beta/usecases/onboard-carts-service/#view-carts-service) differs from what I see when I execute the use case.

In my case, the 'Deployment name' is empty and the wrong 'keptn project' is displayed in all three stages. Find an example below.
![image](https://user-images.githubusercontent.com/15996364/65235759-8a064000-dad7-11e9-9e4c-7d871870e10c.png)

**Comment by grabnerandi** [comment]
As discussed with Andreas. My requirement is similar where I need to define DT_CUSTOM_PROP with meta data that can be accessed by Dynatrace. For keptn 0.4 I modified my helm chart like this
```
env:
        - name: DT_TAGS
          value: "application={{ .Chart.Name }}"
        - name: DT_CUSTOM_PROP
          value: "keptn_project={{ .Chart.Name }} keptn_service={{ .Values.simplenodeservice.service.name }} keptn_stage=staging keptn_deployment=Direct"
```

I would like to come up with a "keptn Best Practice for Dynatrace" where the helm chart I provide for my services that I onboard contains the DT_CUSTOM_PROP with the above shown key/value pairs: project, service, stage & deplomyne.t What I would need is a generic way to also access STAGE and DEPLOYMENT as right now this is not available.
