### ISSUE TITLE
Sequence does not get triggered automatically

### ISSUE THREAD

**Issue by johannes-b** [keptn/keptn#8731]
### Setup 

I have the following shipyard:

```
apiVersion: spec.keptn.sh/0.2.2
kind: Shipyard
metadata:
  name: "fibonacci"
spec:
  stages:
  - name: staging
    sequences:
    - name: deployment
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      #- name: evaluation
      #- name: approval
      #  properties:
      #    pass: automatic
      #    warning: automatic
      - name: release
  - name: production
    sequences:
    - name: deployment
      triggeredOn:
      - event: staging.deployment.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
    - name: delivery
      triggeredOn:
      - event: staging.delivery.finished
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: user_managed
      - name: test
        properties:
          teststrategy: performance
      #- name: evaluation
      #- name: approval
      #  properties:
      #    pass: automatic
      #    warning: automatic
      - name: release
    - name: notify
      triggeredOn:
      - event: production.delivery.finished
#        selector:
#          match:
#            evaluation.result: "fail"
      tasks:
      - name: notify
```

I would like to support the use case to trigger the `notify` sequence after the `production.delivery` is finished. However, this is not working. 

The shipyard-controller says:
```
time="2022-08-24T09:20:14Z" level=info msg="Received event of type sh.keptn.event.production.delivery.triggered from https://github.com/keptn/keptn/cli#configuration-change for project fibonacci"
time="2022-08-24T09:20:14Z" level=info msg="Checking if sequence '.triggered' event should start a sequence in project fibonacci"
time="2022-08-24T09:20:14Z" level=info msg="Found matching task sequence delivery in stage production"
time="2022-08-24T09:20:17Z" level=info msg="Received event of type sh.keptn.event.deployment.triggered from shipyard-controller for project fibonacci"
time="2022-08-24T09:20:17Z" level=info msg="Received event of type sh.keptn.event.deployment.started from helm-service for project fibonacci"
time="2022-08-24T09:20:19Z" level=info msg="Received event of type sh.keptn.event.deployment.finished from helm-service for project fibonacci"
time="2022-08-24T09:20:19Z" level=info msg="Deleted event a8a52831-1eae-4a70-99b1-ec5e1f8f032e"
time="2022-08-24T09:20:22Z" level=info msg="Received event of type sh.keptn.event.test.triggered from shipyard-controller for project fibonacci"
time="2022-08-24T09:20:22Z" level=info msg="Received event of type sh.keptn.event.test.started from job-executor-service for project fibonacci"
time="2022-08-24T09:21:00Z" level=info msg="Received event of type sh.keptn.event.test.finished from job-executor-service for project fibonacci"
time="2022-08-24T09:21:00Z" level=info msg="Deleted event dcaf86a8-1f53-42ed-8a75-17e7aa268f65"
time="2022-08-24T09:21:00Z" level=info msg="Deleting all task.finished events of task sequence delivery with context 26ef8c47-e9c4-4d7c-9415-8922404e890c"        
time="2022-08-24T09:21:00Z" level=info msg="Deleted event 616f1a56-b61b-478a-b43b-67a29a7ea642"
time="2022-08-24T09:21:02Z" level=info msg="Received event of type sh.keptn.event.production.delivery.finished from shipyard-controller for project fibonacci"    
```

## Expected behaviour

* Having the `notify` sequence triggered as part of this sequence:
![image](https://user-images.githubusercontent.com/729071/186387457-8306ab0d-df0c-48a2-af5a-12ff00431153.png)

**Comment by bacherfl** [comment]
@johannes-b I just had a look at this issue - it seems like the notify sequence has not been triggered because the `test` task has failed (and therefore the `delivery` sequence has failed as well) - When considering the next sequence (`notify`) to be triggered, the next sequence will only be triggered if the preceding sequence has been successful, or if a selector has been defined for triggering the sequence after the preceding sequence has failed. E.g.:

```
    - name: notify
      triggeredOn:
      - event: production.delivery.finished
        selector:
          match:
            result: "fail"
      tasks:
      - name: notify
```
