### ISSUE TITLE
keptn-git-config-volume will not be applied when using extra volume mounts in shipyard-controller

### ISSUE THREAD

**Issue by heckelmann** [keptn/keptn#8948]
**Environment**
* Keptn Version (`keptn version`): 0.19.X

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [X] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When providing an `extraVolumeMount` for the shipyard-controller, the `keptn-git-config-volume` will not be applied as it is generating a duplicate `volume` and `volumeMount` entry in the deployment manifest.

**To Reproduce**
```
  shipyardController:
    extraVolumes:
      - name: myextravolume
        secret:
          secretName: mysecret
          defaultMode: 420
    extraVolumeMounts:
      - name: myextravolume
        mountPath: /tmp/mysecretthingy
```
