### ISSUE TITLE
Key SLI/SLO with zero weight

### ISSUE THREAD

**Issue by SuperClyder** [keptn/keptn#9021]
**Describe the problem**
There is no way to fail a test with an SLI that has no impact to the overall score.   For example if a disk file system fills up we want to invalidate the test as results would be untrustworthy (key sli/slo with pass threshold set to "< 100%"), but I don't care how much space is used if disk space is less then 100%.   Setting the weight to 0 still applies a score to the final results, which is not desired.

**Describe the solution you'd like**
Need a way to set a metric as a key indicator, but not have it affect the overall score (similar to what happens when a metric has no data)

**Describe alternatives you've considered**
I tried setting the key sli's weight to zero (which would have made sense that it would not affect the overall score), but that did not appear to give the desired results.

**Additional context**
Thanks for your consideration.

**Comment by agardnerIT** [comment]
Wouldn't a `pass` criteria of `=<100%` and `key_sli: true` work?

If the objective is a boolean pass / fail based on that metric then why care about the score and whether or not it is impacted by an SLI. If it **doesn't** fail, you care about the score.
 
```
objectives:
  - sli: your_disk_sli
     key_sli: true
     weight: 1
     pass:
       - criteria:
           - "<100%"
```

## Option 2: New Precheck Stage

Add a new stage which acts as a precheck. Here you have a quality gate with only one metric (the disk %). Your "real" stage only triggers if this precheck evaluation passes.


```
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: dummy-shipyard
spec:
  stages:
    - name: sanity
      sequences:
        - name: precheck
          tasks:
          - name: evaluation

    - name: proper-stage
      sequences:
        - name: existing-sequence
          triggeredOn:
          - event: sanity.precheck.finisheddev.delivery.finished
             selector:
              match:
                result: passed
          tasks:
          - name: your-existing-tasks
          - name: evaluation
```
